### ISSUE TITLE
Help required for installation of Visit

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#100]
In GitLab by KOUSIK MAKUR on 12 Nov 2020, 05:15 UTC (GitLab issue GL#2275)

I am new in EPOCH, I have installed EPOCH 4.17.10. I am trying to install the visit. I have unpacked the tar.gz file. I got stuck with the line given in manual 
" The actual name of the file will vary depending on which version you downloaded. This will unpack the VisIt
binary into a subdirectory named visit/. Now all that is necessary is to add this to your search path.
eg. export PATH=$HOME/visit/bin:$PATH "
Could anybody help me with this

**Comment by TomGoffrey** [comment]
I'm closing this, as I think the issue has been resolved.

I do note a couple of things:

1. I see no reason why you would need to edit `.bashrc` as root.
2. This thread is not related to the EPOCH code at all. The best place for support with VisIt is the users mailing list.

**Comment by hoaithanhbk** [comment]
when I command "make visit" in the epoch/epoch1d. there is a error 

See also "/home/somafoam/epoch/SDF/VisIt/CMakeFiles/CMakeOutput.log".
make[1]: Entering directory '/home/somafoam/epoch/SDF/VisIt'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/somafoam/epoch/SDF/VisIt'
ERROR: Failed to build VisIt reader.
Makefile:415: recipe for target 'visit' failed
make: *** [visit] Error 1

could you help me to fix it,please!
Thank you
