### ISSUE TITLE
quick question for QED block

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#103]
In GitLab by jiansheng on 30 Nov 2020, 13:07 UTC (GitLab issue GL#2282)

Hi

All, the QED block can simulate pair production, synchrotron emission and radiation reaction, all of these processes descibe the process that electrons produce the photons, but the inverse process (photons->electrons) haven't been included in the QED by now? In addition, I noiticed that the collision block cannot discribe the inverse process either.

**Comment by Status-Mirror** [comment]
Hi Jiansheng,

You are correct - photon attenuation and particle annihilation have not been included in the code. It is expected that these are negligible processes in the length and time-scales attainable in PIC simulation. 

These are features which may be added in the future (we will soon begin physics package development), but there is currently no work on adding this capability.

Cheers,
Stuart
