### ISSUE TITLE
Doubt regarding Ionization with laser

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#104]
In GitLab by saurabh kumar on 30 Nov 2020, 14:31 UTC (GitLab issue GL#2283)

I am running a 2D simulation which involves propagation of two color laser in nitrogen gas with ionization flag activated. As the laser pulses propagates in plasma, gas gets ionized and electrons are generated. The ionization is quite good up to the half length of the simulation box, as the laser propagates further, there is sudden divergence of electron density. The laser has not shown such divergence when propagates in vacuum. Can we explain this diverging ionization. I have attached the input file and the density image GIF for reference.[input.deck](../blob/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/7727bc26b0e1314bbc03ffb3e3599924/input.deck)![density](../raw/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/0f90017c9fd675023aeb862e45346795/density.gif)

**Comment by Status-Mirror** [comment]
Apologies for the late response. In the absence of additional diagnostics, I am satisfied with Toma's response.

Cheers,
Stuart
