### ISSUE TITLE
photons written in file

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#106]
In GitLab by Prokopis Hadjisolomou on 03 Dec 2020, 12:44 UTC (GitLab issue GL#2285)

Hi all,

I would like to know if there is some order in which photons are written in the output.
I'm interested in px,py,pz, to compare the several outputs.
There is a brute-force way to compare all elements, but if there is some relation in how px,py or pz are written (between two outputs), might make things faster.

Thank you in advance, Prokopis

**Comment by Status-Mirror** [comment]
Hi Prokopis,

You probably won't get this response as this is not linked to your original GitLab query, but I'll answer for those scanning through the completed issues.

There is no specific order to the outputting of particle properties. The i-th numbers in the list of output variables all refer to the same particle - for example, the first numbers in the px, py, pz lists are the 3 momentum components of the first particle to be output.

Particles are appended to different lists and have their order shuffled when moving between processors, or during collisions.

The best way of tracking the same particle over multiple output dumps is to compile the code with particle ID switched on. These ID values will not change during the run.

Hope this helps someone,
Stuart
