### ISSUE TITLE
Total fraction of absorbed laser energy in a target

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#107]
In GitLab by Pascal Boller on 07 Dec 2020, 11:17 UTC (GitLab issue GL#2286)

Dear EPOCH experts,

I siumlated a cold (300 K), neutral solid-target with some initial free electrons irradiated by a laser with a pulse duration of 500 fs and a maximum itensity of 1.2 * 10^15 Wcm^2 [input.deck](../blob/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/93b025cce3c4b44a8963b4e10945ba21/input.deck).

Is there an easy way to find out,the fraction of the absorbed laser input energy by the target from the field or the laser?

The .sdf file gives in this context two values the 'Absorption/Total Laser Energy Injected (J)' and the 'Absorption/Fraction of Laser Energy Absorbed (%)'. The first value indicates how much energy has been absorbed/emitted time integrated in the box size and the second value is the time-integrated Poynting flux through the laser boundary, divided by the total injected absorbed laser energy (first value). These values are plotted below.
[Absorption.pdf](../blob/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/67b97354e449215d5581b4a1bd224fd7/Absorption.pdf)

**Comment by TomGoffrey** [comment]
I'm not sure if this can be done in a very rigorous manner. The two possibilities I can think of would be looking at the change in total particle energy as a function of time, and comparing the Poynting flux through the laser boundary and other boundaries to calculate the net injection of EM energy into the simulation. Both approaches suffer from the fact that you're looking at the total Poynting flux, not just the laser Poynting flux, and the particle approach also includes any other sources of energy, including self-heating.

I'll close the issue for now, but if the original poster wants to re-open, they are welcome to.
