### ISSUE TITLE
output laser field and charge separation field separately

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#108]
In GitLab by wangxiaonan on 09 Dec 2020, 07:41 UTC (GitLab issue GL#2287)

dear developer!
i have a question, how to output the laser field and charge separation field in different .sdf file.

**Comment by TomGoffrey** [comment]
This isn't possible. There's no separation of EM fields according to source physics in EPOCH. The laser is introduced as a boundary condition, and the fields are solved self consistently from there. If this isn't clear, a basic reference on PIC codes (e.g. the EPOCH paper) should be consulted.
