### ISSUE TITLE
About the restart time

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#117]
In GitLab by Zhongwei on 19 Jan 2021, 12:51 UTC (GitLab issue GL#2300)

Dear developers,

I have a restart file (about 972G, generated on Jan 17 14:35, e.g., r0004.sdf). When I try to continue the run from the restart file r0004.sdf. 1 day past, the code is running, but the status is still reading...

Usually, there is a time-wall for jobs on HPC. 

So may I ask did you do some tests on the loading time for the Epoch code? If you could provide a Table, e.g.,

the size of the restart file,cost time to restart

100MB,10s

1GB,5min

1TB,?

etc.

It will be really appreciated.

**Comment by smallrainbow** [comment]
@keithbennett 
Dear developer,

The new version seems only can read the restart file named as, e.g., 0001.sdf instead of r0001.sdf or something else.
Could you help check why?
Thank you!

**Comment by TomGoffrey** [comment]
@smallrainbow could you please avoid asking unrelated questions on existing issues.

You should be able to specify `restart_snapshot = r0001.sdf` in the input deck. If this doesn't work, please open a new issue and I will investigate further.
