### ISSUE TITLE
using intensity instead of amp in input file doesn't automatically correct laser profile

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#120]
In GitLab by YoshiF7d on 25 Jan 2021, 15:07 UTC (GitLab issue GL#2304)

It's not like an issue with the code, but a thing that likely to mislead some users.
In epoch, when intensity is set instead of amp in an input file, it only changes the amp,
so the field is not set as sqrt(amp*profile), but sqrt(amp)*profile.

So for example, when the user wants to use a gaussain profile that is defined for intensity, 
the user should manually change the width of the gaussian by sqrt(2) factor.

Maybe a notice about this should be added to the manual.

**Comment by Status-Mirror** [comment]
Web documentation has now been updated to clear this ambiguity.
