### ISSUE TITLE
Question about the number density

### ISSUE THREAD

**Issue by smallrainbow** [Warwick-Plasma/epoch#121]
Dear developers,

Thanks for your notice. It's good to know that epoch has been moved to github.

I have a question about the input deck. When I use epoch to read an external file to set the initial particle number density distribution, does the epoch defaults to set the same weight of each super-particle, and have a spatial-distribution of number of particles per cell? Or does the epoch uniformly distribute the super-particles throughout the space, but change the weight of each particle to fit the given number density profile?

If the former is not the default, how to modify the Makefile and other files to use the former one, thank you!

**Comment by smallrainbow** [comment]
When I uncomment the appropriate DEFINES += $(D)PER_SPECIES_WEIGHT in the Makefile, and recompile the code.

It reports:

mpiifort -c -O3 -g -stand f03 -I../SDF/FORTRAN/include -module obj -o obj/diagnostics.o  -DPER_SPECIES_WEIGHT -DPARTICLE_SHAPE_BSPLINE3 -D_COMMIT='"v4.16.6-0-g77f7e800-clean"' -D_DATE=1613186891 -D_MACHINE='"mn01"' -Isrc/include src/io/diagnostics.F90
src/io/diagnostics.F90(2451): error #6460: This is not a field name that is defined in the encompassing structure.   [WEIGHT]
        .AND. current%weight < sub%weight_min) &
----------------------^
compilation aborted for src/io/diagnostics.F90 (code 1)
make[1]: *** [diagnostics.o] Error 1

The version used for the test is v4.16.6.
Please help check what is the problem, thank you!

**Comment by TomGoffrey** [comment]
I believe the behaviour you want would be enabled by the `PER_SPECIES_WEIGHT` compilation option, so you could compile with `make COMPILER=gfortran DEFINES=-DPER_SPECIES_WEIGHT`. Remember to `make clean` beforehand.
