### ISSUE TITLE
where PDFs of user and developer manuals can be found?

### ISSUE THREAD

**Issue by tsikd** [Warwick-Plasma/epoch#147]
where PDFs of user and developer manuals can be found?

**Comment by TomGoffrey** [comment]
Hi,

We're currently still in the process of porting over our documentation that was previously hosted on out GitLab server. In the meantime, the user manual is included in the 4.17.14 release:

https://github.com/Warwick-Plasma/epoch/releases/tag/v4.17.14

**Comment by TomGoffrey** [comment]
The developer manual is out of date, and I don't recommend its use.
