### ISSUE TITLE
strange Ex behaviour at domain edge

### ISSUE THREAD

**Issue by tsikd** [Warwick-Plasma/epoch#149]
Hi,
please see attached input.deck and idl visualization .pro file. Ex seems to drop to zero near the right domain edge. i.e. print,data.ex(*,5)
       50000.000       50000.000       50000.000       50000.000       50000.000
       50000.000       50000.000       50000.000       50000.000       0.0000000

even at t=0 Ex last point is zero. Seems like bug-type behaviour. Can you replicate this?
[input.deck.txt](https://github.com/Warwick-Plasma/epoch/files/6021092/input.deck.txt)
[snm.pro.txt](https://github.com/Warwick-Plasma/epoch/files/6021093/snm.pro.txt)

**Comment by TomGoffrey** [comment]
I think this is working as intended. The zero-value element `ex(nx,*)` is the element of the normal component at that boundary, which is set to zero for the boundary conditions you specify.

**Comment by tsikd** [comment]
If your comment is true then because bc_x_min and bc_x_max are the same ex(0,*) would be zero but it is 50000. seems odd behaviour isn't it?

**Comment by TomGoffrey** [comment]
EPOCH uses a staggered grid. In 2D Ex is defined at x-face of the cell. For ten cells you have 11 interfaces, Ex(0:10). The boundary values Ex(0) and Ex(10) are set to zero. The SDF file contains 10 values (1:10), so you only see one zero point.
