### ISSUE TITLE
about input file

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#178]
Hi all
I checked my input file but I couldn't detect the exact error
Could you help me please?

![220](https://user-images.githubusercontent.com/46644633/111670749-747eed00-8818-11eb-99d5-aadfd6521ac2.png)

[input.txt](https://github.com/Warwick-Plasma/epoch/files/6166118/input.txt)

**Comment by keithbennett** [comment]
The posted input deck does not produce the error shown in the screenshot. Also, this is not a bug report so should be in the issue tracker. Please open such questions in the Q&A discussions section.
