### ISSUE TITLE
About magnetic energy

### ISSUE THREAD

**Issue by mahdishp** [Warwick-Plasma/epoch#182]
Dear developers,
Hi
I want to get the density of magnetic energy ((b_x)^2)/2μ.
What method should I use?
The sum of the rows and columns of the matrix that any  cell of matrix is multiplied with itself ,sum(sum(bx.^2)) ? 
Or the sum of the rows and columns of the matrix that multiplied with transpose of the matrix ,sum(sum(bx*bx'))?
Thanks

**Comment by keithbennett** [comment]
The former.

**Comment by keithbennett** [comment]
This should have been opened as a q&a discussion. Moving it there.
