### ISSUE TITLE
Unknown error message from an EPOCH job

### ISSUE THREAD

**Issue by imer87** [Warwick-Plasma/epoch#200]
I use the code EPOCH for several years mostly applied in extreme laser plasma-interactions. 

I encounter an error message  -- when I attempt running a job on a supercomputer hosted by CEA (Paris, France)  -- that I cannot find the cause.

I have succeeded to run a numbers of jobs on this supercomputer (namely TGCC) but recently, there has been a significant upgrade on the different machines of this supercomputer.

And since that upgrade, the following error message is generated for any submitted job:

"[...]
  Name of species 3 is photon
  Processor subdivision is            1        1920
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
  BAD block          16           1           1           0
[...]"

Despite a strong support from the IT people, we cannot find the cause of this error message.

Would you have any suggestions about this error message and what could be the cause ?

Thanks,
Rémi

**Comment by keithbennett** [comment]
This looks like it might be a bug in the code. Please provide an input deck that can reproduce the error and the number of CPUs. From the error message it looks like 1920 CPUs. Is that correct?

**Comment by keithbennett** [comment]
Actually, on closer inspection I think that the number of CPUs is probably irrelevant. It looks like the code is unable to parse the input deck.

**Comment by imer87** [comment]
Thanks for your answer.
Yes it is performed on 1920 CPUs.
here [the]([url](url)) input deck :

begin:control
  nx =15000
  ny =2880*2
  
  # final time of simulation
  t_end = 600* femto
  

  # size of domain
 x_min = -50* micron
  x_max = 100 * micron
  y_min = -28.8 * micron
  y_max =  28.8 * micron

  nprocx = 1
  nprocy = 1920

  particle_tstart = 150 *femto


stdout_frequency = 500
end:control


begin:boundaries
  bc_x_min = simple_laser
  bc_x_max = simple_outflow
  bc_y_min = simple_outflow
  bc_y_max = simple_outflow
end:boundaries

begin:qed
qed_table_location=TABLES
use_qed=T
#classical_RR=F
#semi_classical_RR=F
produce_photons=F
photon_energy_min=1e6*(1.6e-19)
photon_dynamics=T
produce_pairs=F
end:qed

begin:constant
 # part=50
npart_per_cell=50
  lambda0 = 1.054 * micron
  omega=2.0*pi*c/lambda0 
  theta = 0
  crit_den=critical(omega)
  den_max=777*crit_den
  den_d=20e27
  thickness=50*micron
  tw=thickness/(2.0*sqrt(loge(2.0)))

  xle =(x_max - x_min)/nx
  xleft = x_min + xle/2.0
  xright = x_max - xle/2.0

  yle = (y_max-y_min)/nx
  yup = y_max - yle/2.0
  ydown = y_min + yle/2.0

  in_ang_deg =0.0
  in_ang_rad =in_ang_deg *pi/180.0

  pulse_width_FWHM = 5e-6
  pulse_width = pulse_width_FWHM/(2.0*sqrt(loge(2.0)))

  pulse_length_FWHM = 40e-15
  pulse_length = pulse_length_FWHM/(2.0*sqrt(loge(2.0)))

  xm0 = 0.0

#  ylaser = (yup+ydown)/2.0 - (xm0-xleft)*tan(in_ang_rad)
  ylaser = 0.0
  rayleigh = pi*pulse_width^2/lambda0

  dym = pulse_width*sqrt(1.0+((xm0-xleft)/rayleigh)^2)

  rx=(xm0-xleft)*(1.0+(rayleigh/(xm0-xleft))^2)

  phixm0 = atan((xm0-xleft)/rayleigh)
  area0 = pulse_width
  area = dym
  norm = area0/(area*sqrt(cos(phixm0)))
  T=28.107e-15
  F=0*10e-15
  F2=((T+F)/T)
 end:constant


 begin:laser
   boundary = x_min
   intensity_w_cm2 = 5e23
   lambda = lambda0 * cos(in_ang_rad)
   pol_angle = 0
#t_profile=if(time lt T,10*(time/T)^3-15*(time/T)^4+6*(time/T)^5,1)
#if(time lt T+F,1,if(time lt 2*T+F,10*(1-(time/T-1))^3-15*(1-(time/T-1))^4+6*(1-(time/T-1)),0)))
t_profile=if(time lt T,10*(time/T)^3-15*(time/T)^4+6*(time/T)^5,if(time lt (T+F),1,if(time lt (2*T+F),10*(F2-((time/T)-1))^3-15*(F2-((time/T)-1))^4+6*(F2-((time/T)-1))^5,0)))
#   t_profile = gauss(time,60e-15,pulse_length)
   profile = norm*gauss(y,ylaser,dym,5)
   phase = 2.0*pi/lambda0*(-y*sin(in_ang_rad)+(y-ylaser)^2/(2.0*rx))

end:laser

# begin:laser
#   boundary = x_min
#   intensity_w_cm2 = 5e23/2
#   lambda = lambda0 * cos(in_ang_rad)
#   pol_angle = pi/2
#t_profile=if(time lt T,10*(time/T)^3-15*(time/T)^4+6*(time/T)^5,if(time lt (T+F),1,if(time lt (2*T+F),10*(F2-((time/T)-1))^3-15*(F2-((time/T)-1))^4+6*(F2-((time/T)-1))^5,0)))
##   t_profile = gauss(time,60e-15,pulse_length)
##   profile = norm*gauss(y,ylaser,dym)
##   phase = 2.0*pi/lambda0*(-y*sin(in_ang_rad)+(y-ylaser)^2/(2.0*rx))
#  phase=-pi/2
#end:laser


begin:species
name=deuterium
charge=1.0
mass=1836.2*2
#npart=nint(nx*ny*part)
npart=nint(nx/2*ny*npart_per_cell/2)
density=den_d
density=if(x lt 0.0,0.0,density(deuterium))
density=if(x gt thickness,0.0,density(deuterium)

#density=den_d
#if(density(deuterium) lt 0.1*den_d,0.0,density(deuterium))

temp_x_ev=10
temp_y_ev=10

end:species 

begin:species
#electron
name=electron
charge=-1.0
mass=1.0
#npart=nint(nx*ny*part)
npart=nint(nx/2*ny*npart_per_cell/2)
density=density(deuterium)
identify:electron

temp_x_ev=10000
temp_y_ev=10000

end:species


begin:species
#photon
name=photon
identify:photon
end:species

begin:subset
name=sub
include_species=electron
include_species=deuterium
#include_species=photon
random_fraction=0.01
end:subset

begin:subset
name=sub_ph
include_species=photon
random_fraction=0.01
end:subset



begin:output
  # number of timesteps between output dumps
  name = Pdata
  file_prefix=pdata
  time_start=166.666 *femto
  dt_snapshot = 3.5133333* femto*5
#  full_dump_every = 25
  particles=sub+sub_ph+single
  px=sub+sub_ph+single
  py=sub+sub_ph+single
  pz=sub+sub_ph+single
  particle_energy=sub+sub_ph+single
  particle_weight=sub+sub_ph+single 
end:output

begin:output
  name = Ddata
#  file_prefix = ddata
  dt_snapshot = 3.51333* femto*5
  time_start=166.667 *femto
  grid = always+single
  number_density=always + species +single +no_sum
  particle_probes=never
  ekbar=always+species +single +no_sum
  ex=always +single
  ey=always +single
#  ez=always +single
#  bx=always +single
#  by=always +single
  bz=always +single
end:output


begin:output
  name = Jdata
#  file_prefix = jdata
  dt_snapshot = 3.51333* femto*5
  time_start=166.667 *femto
  grid = always+single
  jx=always + single
  jy=alwaays + single
end:output

**Comment by keithbennett** [comment]
Thanks. I can reproduce the error. I think there is more than one issue with this input deck. I will let you know when I have identified the problems.

**Comment by imer87** [comment]
That's great. Many thanks.

**Comment by keithbennett** [comment]
I have identified the following problems with this input deck:
1. On lines 86 and 87 there are variables named "T" and "F". These conflict with the built in constants for True and False.
2. On line 101 the "gauss" function has 4 arguments when it should have 3.
3. On line 215 "always" has been mistyped.
Item 2 was ultimately the culprit for the confusing error messages you saw. I will add some changes to improve the error reporting for such cases.
