### ISSUE TITLE
Collisional Ionization, Possible Bug for Non-Unity Electron Masses

### ISSUE THREAD

**Issue by josephrhsmith** [Warwick-Plasma/epoch#210]
Hi All,

I’ve been looking into adding a different collisional ionization model and found a potential bug. On lines 76 and 77 (physics_packages/collisions.F90), the variables e_rest and e_rest_ev are set ‘globally’ using the mass of one electron ‘m0’ 
```
REAL(num), PARAMETER :: e_rest = m0 * c**2
REAL(num), PARAMETER :: e_rest_ev = e_rest / ev
```
These variables are then used throughout the ‘preionise’ subroutine (~10 times). For example the kinetic energy on line 598 is calculated as
```
e_ke_i = c * (SQRT(e_p2_i + e_mass * e_rest) - e_mass * c) / ev
```
If the mass of the ‘electron’ species is not 1 then ```e_mass*e_rest``` will give ```m*m0*c^2``` rather than ```m^2*c^2```. This can lead to some rather nonphysical values for the kinetic energy and other calculations.   

Please let me know if I’m misinterpreting something. I think an easy fix would be to move the definition of the ```e_rest``` variables into the preionise subroutine (accounting for ```e_mass```). Perhaps this routine isn’t made for non-unity electron masses. Then maybe a warning/error would be helpful. Non-unity masses may be relevant to problem I’m modeling.   

Thanks!

**Comment by TomGoffrey** [comment]
I think, given the checking that goes on, for example:

```
          IF (.NOT. (species_list(ispecies)%electron &
              .AND. species_list(jspecies)%ionise)) CYCLE
```

there's an expectation throughout the routine that one of the species involved in the collisional ionisation is indeed an electron. I doubt the cross sections are correct for incident particles which are not electrons, and I don't know if this can be addressed by just changing the mass of the incident particle.

To be clear, these routines predate my time working on EPOCH, and the PhD student responsible has left academia, so my comments are only really educated guesses, but I would have little confidence in using these routines for non-electron impact ionisation.

I'm not sure how much more checking EPOCH should be expected to do - the user has (I think?) already explicitly stated that this species is an "electron". That being said, it wouldn't take much effort to add such a check when we overhaul the impact ionisation this summer.
