### ISSUE TITLE
Is the old git website for epoch  still open? 

### ISSUE THREAD

**Issue by Michael-Gong** [Warwick-Plasma/epoch#214]
Dear Keith,

I am a user of PIC code EPOCH. I remember that previously we can access to the website https://cfsa-pmw.warwick.ac.uk/EPOCH/epoch/wikis/Downloads to obtain the epoch code with different version and user manual. However, today I cannot access to that website. Is that git website closed? Does that mean we can merely obtain epoch code here?

Thank you for your time.
Best regards, 
Michael Gong

**Comment by TomGoffrey** [comment]
Hi Michael,

The old website is no longer accessible. GitHub will be the only place you can obtain EPOCH.

Previous releases are available on the releases page: https://github.com/Warwick-Plasma/epoch/releases
The user manual can be downloaded from the v4.14 release page: https://github.com/Warwick-Plasma/epoch/releases/tag/v4.17.14

**Comment by Michael-Gong** [comment]
Dear Tom,

Thanks for your useful information. That helps.

Best,
Michael Gong
