### ISSUE TITLE
Persistent subsets not working correctly

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#218]
Hello devs:

Recently, I am using using epoch-4.17.1 tracing electrons by specifying persist subset. (Attaches my input.deck, (please change the suffix of the file) ).  What I thought was that if I chose some percentage of  electrons (e.g. random_fraction=0.01) at some time point (persist_start_time=0.1, could be seen in bottom of input.deck), then output the recorded electrons per 0.05(dt_snapshot = 0.05) in an output block .
[inputdeck.txt](https://github.com/Warwick-Plasma/epoch/files/6501692/inputdeck.txt)

The results show that electrons in every output are not all the same. As if EPOCH choose 0.05 of electrons of the whole domain randomly at every output, which make trace particles impossible.

So, is there something wrong when I using the persist subset? 

And, if there are good ways to trace particles, please let me know.

Very thanks!

My post analysis script for matlab is attached. You could copy to matlab for analysis.
 [PostAnalysisForMatlab.txt](https://github.com/Warwick-Plasma/epoch/files/6501818/PostAnalysisForMatlab.txt)

_Originally posted by @FisherFy in https://github.com/Warwick-Plasma/epoch/discussions/217_

**Comment by keithbennett** [comment]
I think that I have identified and fixed the problems with pull request #219 . Please check and confirm that the problem is resolved.

**Comment by TomGoffrey** [comment]
Fixed by pull request #219
