### ISSUE TITLE
Reading SDF file using Python

### ISSUE THREAD

**Issue by skshrc123** [Warwick-Plasma/epoch#240]
Dear Sir/Madam,
I want to read the SDF files using python. Please guide how it can be done.

Thanks

**Comment by TomGoffrey** [comment]
You'll need to build the sdf reader. From one of the epoch1d/epoch2d/epoch3d directories run `make sdfutils`.

Assuming that works you can then do something like:

```
import sdf_helper as sh
data = sh.get_data(filename) # Replace filename with a string containing the file you want to load
```

`data` is an `sdf.BlockList`. You can access variables within the BlockList: `data.Electric_Field_Ey.data`

You can also use the sdf_helper module's plotting methods, for example `sh.plot1d(data.Electric_Field_Ey)`

**Comment by chiehjen** [comment]
I have very large output (~90 GB) files, and when I process the file it runs out of memory. So I have 2 questions regarding how the data is read and stored in sdf file:  

1. Does the command sdf.read(file) read everything at once and store them? or memory are allocated only when data are plotted. 

2. If the answer of 1 is the latter, then is there anyway to de-allocate a subset of the data once they are plotted?

Thank you in advance.
