### ISSUE TITLE
Issue with SDF file while running python program, ERROR: MODULENOTFOUND SDF_HELPER

### ISSUE THREAD

**Issue by mamtaplasma** [Warwick-Plasma/epoch#241]
Hi,

While running my python program, I am getting error: ModuleNotFoundError: No Module named  'sdf_helper'.

I have run following command to resolve my problem:
make sdfutils
but still getting the same error.
Screen shots are attached.
Kindly help.
![IMG-20210617-WA0014(1)](https://user-images.githubusercontent.com/86055949/122393420-7c266d00-cf92-11eb-9bdf-ec87a485f17c.jpeg)
![IMG-20210617-WA0016](https://user-images.githubusercontent.com/86055949/122393514-93655a80-cf92-11eb-9902-4beb82a21194.jpeg)

**Comment by TomGoffrey** [comment]
Your first screenshot shows that the python module isn't being built correctly. Could you try (from the root EPOCH directory):

```
cd SDF/utilities
./build -3
```

and let me know what output that produces?

**Comment by mamtaplasma** [comment]
Thanks for the response.
The output is attached.
![20210617_182229](https://user-images.githubusercontent.com/86055949/122400263-2f926000-cf99-11eb-95f9-4351520f1a3f.jpg)

**Comment by TomGoffrey** [comment]
That looks more promising. Can you try to load the data in python again?

**Comment by mamtaplasma** [comment]
Sir, I have run python again but it didn't work. 
I have also tried after upgrading Epoch as the error was indicating to upgrade it.  But still not working. Attaching the screen shot.

![20210620_190530](https://user-images.githubusercontent.com/86055949/122676321-46d08800-d1fb-11eb-888c-45c1f6ff501e.jpg)

**Comment by TomGoffrey** [comment]
What do you get from running:

```
import sdf
print(sdf.__version__)
```

**Comment by mamtaplasma** [comment]
dell@dell-G3-3579:~$ python3
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdf
>>> print(sdf.__version__)
0.3.5
>>>

**Comment by mamtaplasma** [comment]
dell@dell-G3-3579:~$ python3
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdf
>>> print(sdf.__version__)
0.3.5
>>> 
![20210621_093007](https://user-images.githubusercontent.com/86055949/122705491-7c18bc80-d273-11eb-9398-c2868ab5f7b2.jpg)

**Comment by TomGoffrey** [comment]
Based on this I suspect you have done `pip install sdf` at some point. This installs the package:

https://pypi.org/project/SDF/

which is unfortunately nothing to do with EPOCH and the SDF format we use. Please run `pip uninstall sdf` and try again.

**Comment by mamtaplasma** [comment]
Is running now. 
Thank you so much for help!!

**Comment by TomGoffrey** [comment]
No problem.

**Comment by Tar-phy** [comment]
i have same issue 
![Screenshot from 2024-10-23 11-01-30](https://github.com/user-attachments/assets/15ca0e64-95bd-4966-bccd-730139c3661a)
