### ISSUE TITLE
 two puzzling points in collision.F90

### ISSUE THREAD

**Issue by kazemardaneh** [Warwick-Plasma/epoch#242]
Dear Developers:

The figure below is a part of the preionize function in the collision.F90 of the EPOCH1D/EPOCH2D/EPOCH3d. We can see on it that it calculates two angles, rot_y and rot_z (lines 523 and 529) which are used to rotate the general frame in the ion frame (in which the ion velocity is directed along the x-axis). These two angles are then used for the first time to rotate the electron momentum in the ion frame, e_p_rot (lines 534-539), and then a second time, again e_p_rot (lines 542-547). I was wondering if the first rotation is not necessary because the second one will erase it? the vector e_p_rot is updated in the second rotation and I am puzzled but the one in the first rotation. Moreover, to rotate any vector in the x-axis, the two angles rot_y and rot_z seem the correct angles, but their signs have been modified to the opposite in the two lines 540 and 541.

Can you kindly let me know about these two puzzling points?

Thank you in advance.

![Untitled](https://user-images.githubusercontent.com/42587635/122944590-3eea2280-d378-11eb-81b6-b15572985a31.png)

**Comment by keithbennett** [comment]
This looks like a mistake to me. As far as I can see, the calculation at 534 is never used and is immediately replaced by the one on line 542. I will check it and remove the incorrect calculation.
