### ISSUE TITLE
Is it possible to impose an external current in EPOCH?

### ISSUE THREAD

**Issue by gmmfarrow** [Warwick-Plasma/epoch#248]
Hi, I'm trying to use EPOCH to measure 1 spatial dimension where ideally I'd like to impose a current profile that acts perpendicular to that dimension. Is this something that is even possible using EPOCH in 1D?

Many thanks

**Comment by TomGoffrey** [comment]
Apologies for not replying sooner.

This sounds like a use case for an antenna. Unfortunately that functionality is only available on the 5.0-devel branch. Whilst I don't know of any definite problems with that branch, it is very much experimental, and I doubt it's been used/tested much at all.

**Comment by gmmfarrow** [comment]
Hi @TomGoffrey , no worries, thank for you answer! That sounds interesting - is it possible to specify a current in a time dependent way, similar to the way that the laser works?
Thanks,
Griffin

**Comment by TomGoffrey** [comment]
Yes, I think that ought to be possible. There's some [documentation](https://epochpic.github.io/documentation/input_deck/input_deck_antenna.html) on the new feature.
