### ISSUE TITLE
target thickness

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#250]
Hi all,

 how can I put the thickness of my target  in the input deck ? I use epoch-4.17.15 version

![thick](https://user-images.githubusercontent.com/46644633/123835720-cac3f780-d900-11eb-82c5-9ce1f30f6950.png)

thank you in advance.

**Comment by ReemRad** [comment]
The details is written in the manual in species block section. You can find there an example show you how to define your target thickness.

**Comment by mimboch** [comment]
yes , I define my thickness target according to the manual, but to recognise it by the  code I can only use it  in the canstant block.
 I should put it in the species block because I have not a single foil target.
Maybe the problem with epoch version!
please help me because I need to define it correctly
Thank you

**Comment by keithbennett** [comment]
If you define a variable named "thick" in the constant block then this can be referenced in the species block. If this does not work for you, please post your input deck and we might be able to spot the error.

**Comment by mimboch** [comment]
it didn't work
you find my input in attached file
thank you

[input.txt](https://github.com/Warwick-Plasma/epoch/files/6833068/input.txt)

**Comment by keithbennett** [comment]
The species block does not have a keyword named "thickness". You must rewrite your density expression to account for the thickness

**Comment by mimboch** [comment]
for exemple :  if I have scale_x1 = 30.0 * micron , thickness = 2*micron
	scale_x2 = scale_x1 + thickness;  then:
 density = if((x gt scale_x1) and (x lt scale_x2) , H_dens, 0.0) 

I use the thickness like this exemple.

Thank you

**Comment by keithbennett** [comment]
Apologies for not getting back to you. As noted before, the species block does not have a keyword named "thickness". You can define your own variable named "thickness", but this must be done in a constant block. It can then be referred to from within the species block.

**Comment by mimboch** [comment]
I get it  Keithbennett,  thank you very much.
