### ISSUE TITLE
About the four-current

### ISSUE THREAD

**Issue by smallrainbow** [Warwick-Plasma/epoch#251]
Dear developers,

In order to obtain sharp B structures under the light-speed limit. Is it possible to consider the relativistic effect on the current calculation, i.e., to use gamma*v instead of v (https://en.wikipedia.org/wiki/Four-current) in the Epoch code?

Thank you very much!

**Comment by keithbennett** [comment]
EPOCH is fully relativistic. The gamma factor is already taken into account.
