### ISSUE TITLE
Segmentation fault with using collisions 

### ISSUE THREAD

**Issue by ReemRad** [Warwick-Plasma/epoch#252]
Dear developer

I'm running EPOCH (versions 4.8.5) with collisions. Some runs worked without any problem while others crashed with segmentation fault after generating few sdf's files outputs. As I understand from error message, this happens because EPOCH tries to use memory that it's not allowed to use and results in the program terminating. First I thought it might there a bug in the version that I'm using  so I tried several versions:
epoch-4.8.3 
epoch/4.8.5
epoch/4.8.5-intel-17.0.2
epoch/4.11.0-intel-17.0.2 

but all gave the same error.

After this I used:

#SBATCH --exclude=<node_name>

but this does not avoid the segmentation fault.
[errors.txt](https://github.com/Warwick-Plasma/epoch/files/6783410/errors.txt)

Any suggestion?

**Comment by TomGoffrey** [comment]
The most recent of the versions you tried is over 3 years old. Could you please try using a recent version of EPOCH?

**Comment by ReemRad** [comment]
Thanks Tom. I switched to 4.17.3 (since it is already compliled by scarf team) and it works. Do you think I need to need  4.17.15? I didn't see much difference between the two or Am I mistaken?

**Comment by keithbennett** [comment]
@ReemRad , it is always best to use the most recent version if possible since the minor releases are usually bugfixes and it is always possible that you might get caught out by a bug that has already been fixed. The code is usually quite straightforward to compile yourself.
