### ISSUE TITLE
Inflow boundary conditions in EPOCH

### ISSUE THREAD

**Issue by gmmfarrow** [Warwick-Plasma/epoch#258]
Hi there,
I wanted to check whether inflow boundary conditions have been implemented in EPOCH. If not, is this something that is generally quite tricky to do with particle-in-cell codes, for example if I tried to implement it myself?
Many thanks for any advice,
Griffin

**Comment by TomGoffrey** [comment]
Is what you want to do achievable using the [injector block](https://epochpic.github.io/documentation/input_deck/input_deck_injector.html)?

**Comment by gmmfarrow** [comment]
Reading about the injector block, it seems like it would be, thanks for your help!
