### ISSUE TITLE
Primary job terminated normally (EPOCH 4.17.16)

### ISSUE THREAD

**Issue by ReemRad** [Warwick-Plasma/epoch#259]
For this speific input.deck (attached), I've got the attached error and it is written in output.txt the following:

---------------------------------------------------------------------------------
/apps/eb/software/EPOCH/4.17.16-iomkl-2018b/bin/epoch1d/bin/epoch1d

�[32m Welcome to EPOCH1D version 4.17.16 (commit v4.17.16-0-g3088d845-clean)

�[39m�[0m The code was compiled with the following compile time options

Particle ID tracking (8-bytes) -DPARTICLE_ID
QED Effects -DPHOTONS

Code is running on 200 processing elements

Using data directory "."
Name of species 1 is Electron
Name of species 2 is Carbon
Name of species 3 is Hydrogen
Initial conditions complete and valid.
*** WARNING ***
The collision routine now uses the Nanbu-Perez scheme by default, rather than
Sentoku-Kemp. This method is faster and does not appear to suffer from some
unusual behaviour exhibited by Sentoku-Kemp under certain conditions.
To revert to Sentoku-Kemp, specify "use_nanbu = F" in the collisions block.
To remove this warning message, specify "use_nanbu = T".

Redistributing. Balance: 0.084, after: 0.981 (pre-load balance)
Attempting to load particles
Loaded 9599921 particles of species "Electron"
Loaded 1599920 particles of species "Carbon"
Loaded 1599920 particles of species "Hydrogen"
Skipping redistribution. Balance: 0.981 (initial setup)

Equilibrium set up OK, running code
Primary job terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

---------------------------------------------------------------------------------

If I complied the code with different compiler of openMPI, get different error (for the same input.deck). However, the code works normally with different input.deck. The only difference between this one and the worked one is:
scale_length = 4.0e-6 # plasma front surface length (i.e. 4 um)

I'm not sure what does "Primary job terminated normally" message mean? The code generates outputs til 0006.sdf

Thanks
Reem

[input.deck.txt](https://github.com/Warwick-Plasma/epoch/files/6865218/input.deck.txt)
[errors_EPOCH_4.17.16-iomkl-2018b.txt](https://github.com/Warwick-Plasma/epoch/files/6865219/errors_EPOCH_4.17.16-iomkl-2018b.txt)
[output_EPOCH_4.17.16-iomkl-2018b.txt](https://github.com/Warwick-Plasma/epoch/files/6865220/output_EPOCH_4.17.16-iomkl-2018b.txt)

**Comment by keithbennett** [comment]
The error message indicates that one of the parallel processes aborted unexpectedly. I have run the identical setup on a different machine and the code did not produce any error. I generated 8 outputs before interrupting the run. It is likely related to an issue with one of the compute nodes. Sadly, MPI does not handle errors particularly gracefully and does not provide useful diagnostics in the event of failure.

**Comment by ReemRad** [comment]
Thanks for your relpy! I will change the compiler then.
