### ISSUE TITLE
particle tracking for selected region 

### ISSUE THREAD

**Issue by Deepa64** [Warwick-Plasma/epoch#263]
Dear Developer,

Currently, I am working on the generation of THz radiation from the trapped particle inside the plasma dipole using EPOCH-4.17.12. I am interested in seeing the particle trajectory of a few of the selected particles inside the cavity. Is it possible to perform this simulation for the present version of the EPOCH code?  If yes, kindly guide me for the same. Your assistance in this regard would be highly appreciable.

Thank You!

**Comment by mdhabibi** [comment]
I have done something like your desired plan using making id for example for electrons. And then, in post-processing, I have made some subsets with the assistance of electrons' ids.

**Comment by mdhabibi** [comment]
> > I have done something like your desired plan using making id for example for electrons. And then, in post-processing, I have made some subsets with the assistance of electrons' ids.
> 
> Hi,
> 
> Where did you make changes inside the EPOCH code to trace particle id? I will be highly thankful for your help in this regard.

uncomment '-DPARTICLE_ID' in the makefile, then use id for the desired particle to track in the output block [see user manual, page 60]
