### ISSUE TITLE
SDF .mod files in /SDF/FORTRAN instead of /SDF/FORTRAN/include

### ISSUE THREAD

**Issue by SachCZ** [Warwick-Plasma/epoch#264]
Running
```
make COMPILER=mpif90
```
successfully compiles SDF, but the `.mod` files appear in `<path>/SDF/FORTRAN` instead of `<path>/SDF/FORTRAN/include`. This obviously results in an error:
```
Cannot open module file ‘sdf.mod’
```

Happens for:

- epoch: 4.17.14, 4.17.16 (and possibly all other releases)
- gfortran: 10.3.0
- mpich 3.4.1
- make 4.3

on Ubuntu 21.04. hirsure.

Manually copying the *.mod files to `<path>/SDF/FORTRAN/include` resolves the issue and epoch2d compiles successfully.

**Comment by keithbennett** [comment]
That should be "COMPILER=gfortran"

**Comment by SachCZ** [comment]
That resolved the issue.
