### ISSUE TITLE
the snapshot before interaction laser plasma

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#268]
Hi all,

my box of simulation is 80 µm long and 60 µm wide, where x_min = 0.

to have the snapshot before the interaction laser target, I must to take x_min < 0.

thank you in advance.

**Comment by TomGoffrey** [comment]
I'm sorry, I don't understand the question. What exactly are you struggling with? Perhaps you could include your current input deck and explain what you need to add/change?

**Comment by mimboch** [comment]
Thank you Tom
I want to see the snapshot of laser pulse before the interaction laser plasma, because the output 0000.sdf, 0001.sdf,... are obtained during the interaction

**Comment by TomGoffrey** [comment]
Is there a reason you can't just reduce dt_snapshot so outputs are produced more frequently?
