### ISSUE TITLE
dfloat can't be used in ic_module.f90 for version higher than v4.16.6

### ISSUE THREAD

**Issue by smallrainbow** [Warwick-Plasma/epoch#272]
Dear developers,

dfloat can be used in the ic_module file, e.g., epoch-v4.10.1 instead of v>=4.16.6 (it reports fortran2003 can't use dfloat ... during the compilation by intel fortran + openmpi)
Could you help check it, please? Thank you!

**Comment by TomGoffrey** [comment]
`dfloat` isn't part of any Fortran standard. It's listed as a GNU extension [here](https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gfortran/DFLOAT.html). EPOCH is written in standards compliant Fortran 2003, which does not include `dfloat`.

There are several standards compliant ways of converting integers to floats, but I would suggest using `REAL(a, num)` within EPOCH.
