### ISSUE TITLE
Diffusion

### ISSUE THREAD

**Issue by ZhixinFan-hub** [Warwick-Plasma/epoch#276]
When I set a laser beam along a certain direction, I found that it may propagate to another part, which is different with the consequence mentioned in the manual.
![image](https://user-images.githubusercontent.com/65019083/130339514-a070a5d5-55cb-43d0-a8f8-f095f2cebb97.png)
![image](https://user-images.githubusercontent.com/65019083/130339538-1f9c4aec-fbf4-4603-84c2-7dd1f1d6a6df.png)

**Comment by Status-Mirror** [comment]
Hi @ZhixinFan-hub

Sorry for the delay. I know this is probably too late, but for the benefit of anyone sifting through the issues, I believe this disagreement came from using a different input deck to the documentation.

For more detail on how to set up a Gaussian pulse, check the documentation example deck [here](https://epochpic.github.io/documentation/examples/basic_examples.html).

Cheers,
Stuart
