### ISSUE TITLE
adjust position of the laser pulse

### ISSUE THREAD

**Issue by Deepa64** [Warwick-Plasma/epoch#277]
Dear Developer,
I am interested in launching a Gaussian laser pulse at an angle from the end of the ymin boundary of the system rather than from its center.

 Kindly guide me where I need to make changes in the code for the same.

**Comment by YongMa1988** [comment]
Hi, 

Just wondering did you figure out how to launch a laser pulse at an arbitrary angle?

Thanks a lot!
Yong

**Comment by Deepa64** [comment]
> Hi,
> 
> Just wondering did you figure out how to launch a laser pulse at an arbitrary angle?
> 
> Thanks a lot!
> Yong

Dear Yong,
My query was related to the position of the laser pulse. I wanted to launch my pulse from the end of the boundary (ymin) rather than from the boundary center(y=0). For this, I change my axis limit from (-ymin, ymax) to (-ymin/2, ymax).

**Comment by YongMa1988** [comment]
> > Hi,
> > Just wondering did you figure out how to launch a laser pulse at an arbitrary angle?
> > Thanks a lot!
> > Yong
> 
> Dear Yong,
> My query was related to the position of the laser pulse. I wanted to launch my pulse from the end of the boundary (ymin) rather than from the boundary center(y=0). For this, I change my axis limit from (-ymin, ymax) to (-ymin/2, ymax).

Hi Deepa64,

Thanks for the reply!
I though you were interested in launching a Gaussian laser pulse at an angle? By any chance you have an example of that?

Thanks a lot!
Yong
