### ISSUE TITLE
How do reflective particle boundary conditions work in 1D?

### ISSUE THREAD

**Issue by gmmfarrow** [Warwick-Plasma/epoch#282]
I had a question about how reflective boundary conditions work on particles in 1D?
If a particle with a v_x, v_y and v_z component hits bc_x_min, is the v_x reversed and the v_y and v_z unchanged?
Or are the v_y and v_z reversed as well?
Many thanks,
Griffin

**Comment by TomGoffrey** [comment]
The former. Only v_x is reversed:

```Fortran
IF (bc == c_bc_reflect) THEN
  cur%part_pos = 2.0_num * x_min - part_pos
  cur%part_p(1) = -cur%part_p(1)
ELSE
  ...
```
