### ISSUE TITLE
Energy Conservation of EPOCH

### ISSUE THREAD

**Issue by Mr-Oro** [Warwick-Plasma/epoch#292]
Hey, I was wondering how to get an energy conservation estimate from EPOCH? Like if there is a 10 mJ laser that enters the system, how much gets lost throughout due to numerical issues.

**Comment by Status-Mirror** [comment]
Hey Mr-Oro,

Apologies for the late response, we're currently addressing the issue backlog. I'll write a response in case anyone scrolling through the issues has the same question.

I would advise using the output parameter: "total_energy_sum", which gives the total particle energy and total field energy in the simulation. Documentation is given here:
https://epochpic.github.io/documentation/input_deck/input_deck_output_block.html

Cheers,
Stuart
