### ISSUE TITLE
Time varying electric field

### ISSUE THREAD

**Issue by alexvirbank** [Warwick-Plasma/epoch#293]
Hello,

I am just getting started with EPOCH and wanted to run a test simulation of a plane electromagnetic wave propagating. Is it possible to specify a time-dependent electric (& magnetic field)? If so, how do you do this?

**Comment by Status-Mirror** [comment]
Hi @alexvirbank 

Apologies for the incredibly late response, we're currently working through the backlog of issues.

EPOCH has a specific laser block for injecting electromagnetic waves. The documentation is available here:
https://epochpic.github.io/documentation/input_deck/input_deck_laser.html

Cheers,
Stuart
