### ISSUE TITLE
Can‘t read sdf file using python.

### ISSUE THREAD

**Issue by jcyu96** [Warwick-Plasma/epoch#298]
Dear all,
When I tried to read the sdf file with python, there would be such an error, warning me that the version of my sdf library is too low.
![image](https://user-images.githubusercontent.com/57207865/136019718-4640e59c-a6f8-491e-a3e6-95776c3f33da.png)
The version of my sdf library is 0.3.5. [Here](https://pypi.org/project/SDF/) you can see that this is the highest version of the sdf library. How can I solve this problem? Thanks in advance.

**Comment by TomGoffrey** [comment]
The SDF library you have installed is not the SDF library used and developed by the University of Warwick. Please remove it (`pip uninstall sdf`), then build the correct library by changing to one of the epoch directories (e.g. `epoch/epoch1d`) and running `make sdfutils`

**Comment by jcyu96** [comment]
Still have this problem  when I try to `import sdf_helper`.This problem still occurs when I try to import sdf-help.

**Comment by TomGoffrey** [comment]
Please run:

```python
import sdf_helper
print(sdf_helper.__version__)
print(sdf_helper.__commit_id__)
```

and report the output.

**Comment by jcyu96** [comment]
I can't import sdf_helper, and this warning appears when I try to import.
![image](https://user-images.githubusercontent.com/57207865/136024878-c6f3b258-7d25-4e6e-87e1-dd3e67205234.png)

**Comment by TomGoffrey** [comment]
Did you remove the previous (incorrect) SDF library as I suggested in my first reply?

**Comment by jcyu96** [comment]
Yes, I remove the previous SDF library by the follow command.

> pip install sdf

**Comment by jcyu96** [comment]
`import sdf` can not work, the output like follow image:
![image](https://user-images.githubusercontent.com/57207865/136345722-c2856cdf-b67e-4ff2-a5b5-a26b677f17df.png)

**Comment by Status-Mirror** [comment]
The last comment in this chain seems to have been posted in 2021, so I'm guessing this is no longer an active issue. I will mark this as closed for now, but if there are any new insights we can re-open.
