### ISSUE TITLE
issue in getting the output of the selected particle

### ISSUE THREAD

**Issue by Deepa64** [Warwick-Plasma/epoch#301]
Hi,

I am trying to track selected particles. For that, I have provided selected particles id, position, and weight by using the particle_from_file block in EPOCH.  However, particle details are not available in the output files. I have attached my files to this issue.
How I can get the evolution of only these particles?

Kindly help me in this regard.

Thank you!

[iddata.txt](https://github.com/Warwick-Plasma/epoch/files/7345770/iddata.txt)
[xdata.txt](https://github.com/Warwick-Plasma/epoch/files/7345773/xdata.txt)
[ydata.txt](https://github.com/Warwick-Plasma/epoch/files/7345774/ydata.txt)
[input.txt](https://github.com/Warwick-Plasma/epoch/files/7345775/input.txt)
[wdata.txt](https://github.com/Warwick-Plasma/epoch/files/7345776/wdata.txt)

**Comment by tomdg1626003** [comment]
hi,Have you solve this question?I have this question,and the hints is that  does not appear to match the domain dimensions
.

**Comment by TomGoffrey** [comment]
@tomdg1626003 Could you open a new issue describing your problem please? Be sure to include what version of EPOCH you used, your input deck, any required post-processing code, and what you think is wrong/what you were expecting to be the result.
