### ISSUE TITLE
error while tracking the particle

### ISSUE THREAD

**Issue by Deepa64** [Warwick-Plasma/epoch#303]
Hi,
I am trying to track the selected particles by using EPOCH-4.17.16. For this, I have chosen 10 particles from the output data file and again run the code by using the particles_from_file subset. However, It gives following error-
![track_particle_error](https://user-images.githubusercontent.com/66676157/137636416-a8fd03de-66d8-4974-a5f5-a522771c4019.png)

Kindly help me with this regard.

**Comment by Status-Mirror** [comment]
I'm going to mark this issue as closed for now, but feel free to continue the message thread if you still have problems later.
