### ISSUE TITLE
There are some problems with the number density read from the file.

### ISSUE THREAD

**Issue by jcyu96** [Warwick-Plasma/epoch#307]
Dear all:
I want to import the number density from a [binary file](https://github.com/jcyu96/epoch/blob/main/ele_den.dat) in species block with `number_density = 'Data/ele_den.dat'`, but the image plot by the imported data is completely different from the image plot by the original data. Is this normal?
After import：
![image](https://user-images.githubusercontent.com/57207865/138136588-b48670e4-8e5c-4a50-8f9f-3b72f687bd46.png)
Before import：
![image](https://user-images.githubusercontent.com/57207865/138136842-eb370a7f-c3a6-4c55-8297-8e986873f380.png)

**Comment by tomdg1626003** [comment]
Hello, when you input the density with an external file, the density data is a 2D matrix and then saved as binary file?
