### ISSUE TITLE
EPOCH hangs when writing restart dumps

### ISSUE THREAD

**Issue by Vlasovian** [Warwick-Plasma/epoch#309]
Hi team,

I've been having some issues recently with EPOCH failing to write restart dumps. At first, this issue was restricted to final restart dumps, despite usually giving the code ~30 mins of write time after halting runs. Restarts during runs were written to disk (in typically under a minute) w/out any issues. 

Since increasing the global # of particles from ~3e8 to ~6e8, the code also seems to hang when writing restart dumps at intermediate times. For the deck attached, this happens at around 10 hours into the run (as specified in the input deck), and the restart dump remained stuck at 1.2 MB (restart ~ 20 GB, normal ~ 4 MB) for a few hours before I interrupted it. Before submitting the full job, I ran the deck for about 30 mins w/ restarts every 5 or so normal dumps, and everything seemed ok. I've tried freeing up space in my working directory on the cluster, but that doesn't seem to have helped. The code also outputs a restart dump at time zero, despite force_first_to_be_restartable=F by default. Could this be a bug?

I'm currently running epoch1d v4.17.16 on 23 Avon nodes.

input deck: [input_deck.txt](https://github.com/Warwick-Plasma/epoch/files/7534402/input_deck.txt)
epoch1d.dat: [epoch1d.txt](https://github.com/Warwick-Plasma/epoch/files/7534393/epoch1d.txt)
slurm script: [sbatch_script.txt](https://github.com/Warwick-Plasma/epoch/files/7534413/sbatch_script.txt)

Thanks in advance

**Comment by Garasyov** [comment]
Try to avoid using OpenMPI, MPICH is more stable with EPOCH.

**Comment by Vlasovian** [comment]
Thanks! I'll look into it.

**Comment by Status-Mirror** [comment]
Hi all,

Apologies for the big delay, we're currently trying to sort out our backlog of issues. Did you manage to resolve this restart problem?

Cheers,
Stuart

**Comment by Status-Mirror** [comment]
I'm going to mark this issue as closed for now, as it refers to an older version of EPOCH running on a private cluster. If problems persist, feel free to continue this thread.

Stuart
