### ISSUE TITLE
Error when initializing EPOCH-4.17.12

### ISSUE THREAD

**Issue by jcyu96** [Warwick-Plasma/epoch#311]
Dear team,
There is some issues recently with EPOCH failing to run. The input file and error message is attached below. I don't know how to fix this problem.If possible, can someone help me solve this issue？Thank you in advance.
![image](https://user-images.githubusercontent.com/57207865/141888008-e26150d1-93a9-4280-ba51-593413fe7924.png)
![image](https://user-images.githubusercontent.com/57207865/141888298-14b39a98-5f32-4e71-9b38-57a3ebc1619e.png)
![image](https://user-images.githubusercontent.com/57207865/141888235-7f2c71f2-1842-4d15-9c95-e26663b737fc.png)

Input file: [input.deck](https://github.com/jcyu96/epoch/raw/main/File/input.deck)

**Comment by keithbennett** [comment]
Is there a previous version of EPOCH that ran without errors on this input deck?

**Comment by jcyu96** [comment]
I also got errors when I ran it on version 4.17.8. When I was about to install the latest version, an error was reported during the compilation process like below:
![image](https://user-images.githubusercontent.com/57207865/141990643-f9d56b7b-0bfb-43d8-b0aa-a5b16e16ce7a.png)
What can I do for the compilation error?

**Comment by jcyu96** [comment]
> I also got errors when I ran it on version 4.17.8. When I was about to install the latest version, an error was reported during the compilation process like below: ![image](https://user-images.githubusercontent.com/57207865/141990643-f9d56b7b-0bfb-43d8-b0aa-a5b16e16ce7a.png) What can I do for the compilation error?

I solved it. This compilation error is because the gcc version I use is too high, and I need to use a lower version of the gcc compiler(like gcc-4.x.x).
