### ISSUE TITLE
There is problem when compiling 'drift_px' in 'species block'

### ISSUE THREAD

**Issue by jcyu96** [Warwick-Plasma/epoch#315]
Dear all,
It may be that I didn't represent `drift_px` correctly, but I don't know how to correctly represent `drift_px` in species block.
The error and [input file](https://cdn.jsdelivr.net/gh/jcyu96/epoch@main/File/input.deck) like below:
![image](https://user-images.githubusercontent.com/57207865/143421387-eaf35c6e-0f21-4865-acb1-6076d36e27a0.png)

Anyone can help me? Sincere thanks!

**Comment by yingchaolu** [comment]
It seems r1, r2, v1 and v2 are not constants. It might work if you replace those in species block by explicitly write the expressions for r1, r2, v1 and v2 in number_density drift_px, etc.

**Comment by jcyu96** [comment]
> It seems r1, r2, v1 and v2 are not constants. It might work if you replace those in species block by explicitly writing the expressions for r1, r2, v1 and v2 in number_density drift_px, etc.

Thank you for reply. I changed the indentation on line 77 and it worked fine, so I guess the error was due to indentation or some other weird little bug.

**Comment by Status-Mirror** [comment]
Hi all, excuse the late response on something already solved - we're just tidying up old issues at the moment.

The issue here was due to writing:
> 0,0 

instead of 

> 0.0

on line 77. This gave the "if" function too many arguments, and caused the code to break.

Cheers,
Stuart
