### ISSUE TITLE
can't restart the dump

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#316]
Hi all
my pc is turned off during the calculations.
I used restart_snapshot so that the code continues the calculations, but it doesn't work.
could you tell me how can I continue the simulation without start with 0000.sdf?

![snap](https://user-images.githubusercontent.com/46644633/143690710-d36320b4-9707-4bf2-8c7b-0a95e5cee881.png)

thank you in advance.

**Comment by Quickrix** [comment]
This is not possible unless you have a restart dump.
The 0012.sdf  dump you are trying to restart from is not the restart one (see the message in your screenshot).
Output of restart dumps should be configured in your deck file.

**Comment by mimboch** [comment]
Hi Quickrix
please, How can I configure the restart dump in my deck file? because I run my calculations in the server, and often it can't finish them.
I'm really blocked with , please answer me

thank you
