### ISSUE TITLE
issue about uniform particle loading

### ISSUE THREAD

**Issue by zwjlpi** [Warwick-Plasma/epoch#320]
The auto-loader is the default loader in Epoch codes, which places the particles in the cell by random positions. How could I realize the uniform particle loading instead? 

Thanks a lot!

**Comment by yingchaolu** [comment]
You can use manual_load for uniform particle loading. There is a subsection "Setting the particle properties" in the user manual which shows how to use manual_load. I don't think the input deck has any parameter for uniform particle loading.

**Comment by zwjlpi** [comment]
> You can use manual_load for uniform particle loading. There is a subsection "Setting the particle properties" in the user manual which shows how to use manual_load. I don't think the input deck has any parameter for uniform particle loading.

Thanks a lot. But the manual_load in the user manual just move all the particles in one cell to the same grid point. Therefore, the particles in one cell has the identical dynamics in the simulation, which makes the num_part_per_cell meaningless in my view.
