### ISSUE TITLE
How to output the properties of only one particle species?

### ISSUE THREAD

**Issue by jcyu96** [Warwick-Plasma/epoch#322]
Dear all,
I want to output only one particle properties through below code in output block.

> particles   = single + trace
> vx          = single + trace
> vy          = single + trace
> vz          = single + trace

But there are no particle properties in the final output, does anyone know how to write the input file correctly?
[input.deck.txt](https://github.com/Warwick-Plasma/epoch/files/7655177/input.deck.txt)

**Comment by Quickrix** [comment]
Not sure if it is possible to restrict output by particular spices.

Add species dumpmask to divide output by species.
E.g.
vx = single + trace + species

[See docs](https://epochpic.github.io/documentation/input_deck/input_deck_output_block.html)

**Comment by Status-Mirror** [comment]
Quickrix is correct. One possible work-around would be to define a new species, and populate it with a single particle. This way the species output would print the entire species, but this would just be the one particle of interest.
