### ISSUE TITLE
a question about the injector block

### ISSUE THREAD

**Issue by zwjlpi** [Warwick-Plasma/epoch#323]
I try to inject an electron slice with specific longitudinal momentum distribution drift_px=gamma0*me*c*f(r), of which the gamma0 is very high. And I found the total number of the injected electrons is not constant by changing the gamma0, when other parameters are constant.  And if I abandon the f(r) in the drift_px, the total number of the injected electrons could be constant. How does this happen?  And how can I realized the constant electron number injection by different spatial-varying drift_px distributions? Hope for your help.

**Comment by Status-Mirror** [comment]
Hi zwjlpi,

Apologies for the delay in getting back to you. I'm wondering if you had a temperature specified in the injector? 

Injectors consider the behaviour of a plasma-cell just beyond your simulation boundary. Temperature gives these external particles momenta in all directions, but the injectors only inject particles travelling through the boundary. When you apply a drift momentum, particles which originally pointed away from the boundary may now point towards it, and the number of particles injected through the boundary increases. The greater your drift velocity, the more particles will be injected.

If you weren't using temperature, could you attach the old input deck if you still have it lying around?

Cheers,
Stuart
