### ISSUE TITLE
Specifying a single tracker particle

### ISSUE THREAD

**Issue by gmmfarrow** [Warwick-Plasma/epoch#332]
Hi there,
I'm trying to get my head around EPOCH and would like to put together a little test problem - of just a single electron gyrating in a magnetic field. I'm going to make it a no current species and just output the particle position etc in every timestep. However, is there a way within the input deck to just specify a single particle with a known velocity/position so that I can view its trajectory?

**Comment by Status-Mirror** [comment]
Hi gmmfarrow,

Apologies for the incredibly late response. I think you've probably sorted this by now, but I'll add this comment to complete our records.

Your best method would be to create an electron species block, then you could specify the number density using if(...) statements to select where you want the particle to be. The number density will determine the weight of your macro-particle. You won't be able to set an exact (x,y,z), but you can determine the cell where you want to initialise your particle. Finally, you can control the number of particles added to the simulation in the control block, and this can be set to 1.

For a full set of input deck documentation, you can consult this URL:
https://epochpic.github.io/documentation/input_deck/input_deck.html

Cheers,
Stuart
