### ISSUE TITLE
Cicular polarization ?

### ISSUE THREAD

**Issue by dmargarone** [Warwick-Plasma/epoch#340]
Hi,

How to make a circularly polarized laser pulse ?
Any help or suggestion will be helpful. 

Thanks.

**Comment by Jkennedy1** [comment]
Hey, 
Circular polarization corresponds to φ = ±π/2 and Ex = Ey 
So you just want to create two lasers, have one laser with phase and polarisation :
phase = 0 
pol_angle = 0

And the other with phase and polarisation: 

phase = pi/2 
pol_angle = pi/2

Best, 
Jonny

**Comment by dmargarone** [comment]
Hi Jonny,
So nice of you. Thank you so much for your reply. It's really helpful.

Best regards,
DM
