### ISSUE TITLE
Will there be a cylindrical geometry version of EPOCH?

### ISSUE THREAD

**Issue by griffinfarrow** [Warwick-Plasma/epoch#351]
I remember seeing a talk about a year ago about EPOCH that said a cylindrical version was in development. Is this still the case? When might it be coming out?

**Comment by Status-Mirror** [comment]
You're right, but this is still in the early stages of development - the project was delayed due to switching up the staff. We now have a developer working on this full time. Based on the current state of the code, I would estimate early 2023.
