### ISSUE TITLE
Work done intergrated weird values

### ISSUE THREAD

**Issue by DoubleAgentDave** [Warwick-Plasma/epoch#364]
When loading dumped particles the particle variables 'Work_done_integrated' there are a small population of particles with wildly large values in particular directions. This seems to happen in 2D and 3D versions of the code (I've not tried 1D). When summing over the work done integrated for these specific particles the results do not equal the particle energy at that specific time. For the rest of the particles the results are physical and the summed values equate to the kinetic energy. Is there some population that isn't initialized properly? This seems like some sort of memory leak problem.

**Comment by Status-Mirror** [comment]
Hi there,

Apologies for the delay in this response, is this still an issue? If so, it would be useful if you could supply an input deck which generates these large work-done values.

Cheers,
Stuart

**Comment by DoubleAgentDave** [comment]
It is still an issue, as far as an input deck goes, pretty much any input deck I use when I save work_done_integrated does this. I talked to a colleague about this, they mentioned that it was due to the variables not being initialized properly and they had a fix for it. I've emailed them just now to see if they still have it. However, this problem is likely going to be compiler dependent if it's an uninitialized variable and so not easily reproducible.  

Here is the offending input deck, note it is specifically the "work_s_total" (where s=x,y,z) values that are problematic:

begin:control
	#makes it divisible by the number of cores I'm giving it
	nx=6144
	ny=12288
	t_end=1500*femto
	#t_end=6.*femto #shorttestsimulation
	x_min=-6.*micron
	x_max=12.*micron
	# widen the box a bit so there is room for laser diffraction with moving window
	y_min=-18*micron 
	y_max=-y_min
	stdout_frequency=10
	deck_warnings_fatal=T
	simplify_deck = T
	smooth_currents=T
end:control

begin:boundaries
	# cpml_thickness=16
	# cpml_kappa_max=20
	# cpml_a_max=0.2
	# cpml_sigma_max=0.7
	# bc_x_min=cpml_laser
	# bc_x_max=cpml_outflow
	# bc_y_min=cpml_outflow
	# bc_y_max=cpml_outflow
	# CPML boundaries don't work well with a moving window sadly
	bc_x_min=simple_laser
	bc_x_max=simple_outflow
	bc_y_min=simple_outflow
	bc_y_max=simple_outflow
end:boundaries

begin:window
	move_window = T
	window_v_x = 299792458
	window_start_time = 40*femto
	bc_x_min_after_move = simple_outflow
	bc_x_max_after_move = simple_outflow
end:window	

begin:constant
	las_lambda0=800*nano  #laserwavelength
	foil_thickness=200.*nano  #thicknessofthefoil
	foil_width=2000.*nano  #foilwidth
	scale_x=las_lambda0/60
	cell_xsize=las_lambda0/100
	nx_foil=foil_thickness/cell_xsize  #numberofcellsinfoil
	cell_ysize=las_lambda0/100
	ny_foil=foil_width/cell_ysize  #numberofcellsinfoil
	las_omega=2.0*pi*c/las_lambda0  #angularlaserfrequency
	las_time=2.0*pi/las_omega  #laserwaveperiod
	theta=0.0 #incidenceangle(inrad)
	fwhm0=3500.*nano  #laserbeamwidth(FWHM)
	
	w0=fwhm0/(2.0*sqrt(loge(2.0)))  #laserbeamwaist
	f_duration=30*femto  #fulllaserpulseduration
	xfocus=6.*micron  #distanceoflaserfocalspotalongx-axis
	yc=-xfocus*tan(theta)  #distanceoflaserbeamaxisfromcentralaxis
	zR=pi*w0^2/las_lambda0  #rayleighrange
	lfocus=xfocus/cos(theta)  #alonglaserpropagationdirection
	wl=w0*sqrt(1.0+(lfocus^2)/(zR^2))  #spotsizeatdistancelfocus
	w_y=wl/cos(theta)  #spotsizeintheprojectionony-axis
	r_curv=lfocus*(1.0+(zR^2)/(lfocus^2))  #radiusofbeamcurvature
	intensity_fac2d=1.0/sqrt(1.0+lfocus^2/zR^2)*cos(theta)
	n_crit=critical(las_omega) #electroncriticaldensity
	n_max=800*n_crit
	# ncrit = 1.7e21 cm-3, nAu=4.7e24 cm-3
end:constant

begin:species
	name=electron
	charge=-1.0
	mass=1.0
	npart_per_cell=4000

	# a square foil
	density=if((x lt foil_thickness)and(x gt 0)and (abs(y) lt (foil_width/2.0)),n_max,0.0)
	#add gradients

	#x left edge
	density = if(x lt 0 and abs(y) lt (foil_width/2.0), n_max * exp(x/scale_x),density(electron))
	# x right edge
	density = if((x gt foil_thickness) and abs(y) lt (foil_width/2.0), n_max * exp((foil_thickness-x)/scale_x),density(electron))
	#y edges
	density = if((x gt 0) and (x lt foil_thickness) and (abs(y) gt (foil_width/2.0)), n_max * exp(((foil_width/2.0)-abs(y))/scale_x),density(electron))
	#upper left corner
	density = if(x lt 0               and y gt  (foil_width/2.0), n_max * exp(-sqrt((x-0.)^2            +(y-foil_width/2.0)^2)/scale_x),density(electron))
	#upper left corner
	density = if(x lt 0               and y lt -(foil_width/2.0), n_max * exp(-sqrt((x-0)^2             +(y+foil_width/2)^2)/scale_x),density(electron))
	#upper right corner
	density = if(x gt foil_thickness  and y gt  (foil_width/2.0), n_max * exp(-sqrt((x-foil_thickness)^2 +(y-foil_width/2)^2)/scale_x),density(electron))
	#lower right corner
	density = if(x gt foil_thickness  and y lt -(foil_width/2.0), n_max * exp(-sqrt((x-foil_thickness)^2 +(y+foil_width/2)^2)/scale_x),density(electron))
	density_min=0.01*n_max

	temp_ev=0
	identify:electron
end:species

begin:species
	name=proton
	charge=1.0
	mass=1836.0
	npart_per_cell=500
	density=density(electron)*1.0/1.0
	# Density minimum not set automatically for some reason
	density_min=0.01*n_max*1.0/1.0
	temp_ev=0
end:species

begin:species
	name=gold
	charge=79.0
	mass=22032.0
	npart_per_cell=500
	density=density(electron)*1.0/79.0
	# Density minimum not set automatically for some reason
	density_min=0.01*n_max*1.0/79.0
	temp_ev=0
end:species

begin:laser
	boundary=x_min
	intensity_w_cm2 = intensity_fac2d*4.5e19
	#intensity_w_cm2 = intensity_fac2d*1.0e21
	lambda=las_lambda0*cos(theta)
	pol_angle=0  #normalincidence
	phase=-2.0*pi*(y-yc)*sin(theta)/las_lambda0+pi/(las_lambda0*cos(theta))*((y-yc)/cos(theta))^2*1.0/r_curv-atan(((y-yc)*sin(theta)+lfocus)/zR)
	profile=gauss(y,yc,sqrt(2)*w_y)
	t_profile=(sin(time/(f_duration)*pi))^2
	t_start=0.0
	t_end=30*femto
end:laser

begin:output
	name = fields
	file_prefix = fields
	dt_snapshot=3*femto

	# particles=always+species+single
	# px=always+single
	# py=always+single
	# pz=always+single
	
	# propertiesongrid
	grid=always+single
	ex=always+single
	ey=always+single
	ez=always+single
	bx=always+single
	by=always+single
	bz=always+single
	jx=always+single
	jy=always+single
	number_density=always+species+single
end:output

begin:subset
	name = E_sub
	random_fraction = 0.1
	persist_start_time = 50*femto
	include_species:electron
	gamma_min = 1.0
	x_min = 2.0*micron
	y_min = -4.0*micron
	y_max = 4.0*micron
end:subset

begin:output
	name = e_loc
	file_prefix = e_loc
	dt_snapshot = 1 * femto
	time_start = 50 * femto
	dump_first = T
	id = E_sub + single
	px = E_sub + single
	py = E_sub + single
	pz = E_sub + single
	work_x = E_sub + single
	work_y = E_sub + single
	work_z = E_sub + single
	work_x_total = E_sub + single
	work_y_total = E_sub + single
	work_z_total = E_sub + single
	particle_weight = E_sub + single
end:output

**Comment by DoubleAgentDave** [comment]
Just to be clear the following compile options were used:

 Third order B-spline particle shape -DPARTICLE_SHAPE_BSPLINE3
 Particle ID tracking (8-bytes) -DPARTICLE_ID
 Work done on each particle -DWORK_DONE_INTEGRATED

**Comment by ktangtar** [comment]
> It is still an issue, as far as an input deck goes, pretty much any input deck I use when I save work_done_integrated does this. I talked to a colleague about this, they mentioned that it was due to the variables not being initialized properly and they had a fix for it. I've emailed them just now to see if they still have it. However, this problem is likely going to be compiler dependent if it's an uninitialized variable and so not easily reproducible.

Hi,

I am in the same group as @DoubleAgentDave, and have checked the fix by our colleague (initializing the integrated work to 0):
In  /epoch-4.17.16/epoch3d/src/housekeeping/partlist.F90, there is a subroutine for init_particle (roughly line 555).  Here, many variables are initialized for particles.  By adding the following lines inside the subroutine, the work variables will be initialized to 0 when the code is compiled with the -DWORK_DONE_INTEGRATED option:

```
#ifdef WORK_DONE_INTEGRATED
    new_particle%work_x = 0_num
    new_particle%work_y = 0_num
    new_particle%work_z = 0_num
    new_particle%work_x_total = 0_num
    new_particle%work_y_total = 0_num
    new_particle%work_z_total = 0_num
#endif        
```

The simulation run with this edit completely solved the problem for me.  Without this fix, roughly 2% of the particles outputted had work initialized at greater than 1e27 mc^2.
