### ISSUE TITLE
how to obtain new SDF module for python

### ISSUE THREAD

**Issue by ldilucchio** [Warwick-Plasma/epoch#376]
Dear Sirs and Madams,
I am of course an EPOCH user and I am currently getting and error from my python scripts which are trying to import sdf.
Traceback (most recent call last):
  File "cep-exey.py", line 11, in <module>
    import sdf
ImportError: dynamic module does not define init function (initsdf)
I ave checked my python, SDF and FORTRAN version. However, I cannot download the new SDF package on macOS Big Sur. Is it possible to get it in another way from just downloading the zip folder? I have checked the partition sized on my Mac and the programs and it looks all fine.
Laura Di Lucchio

**Comment by cmoissar** [comment]
Hi Stuart,

I have followed the steps above (git clone --recursive https://github.com/Warwick-Plasma/epoch.git)

However, I get:
`pip3 install utilities/`

```
Defaulting to user installation because normal site-packages is not writeable
Processing ./utilities
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/clementmoissard/Desktop/Research/HEDP/epoch/SDF/utilities/setup.py", line 63, in <module>
          get_version()
        File "/home/clementmoissard/Desktop/Research/HEDP/epoch/SDF/utilities/setup.py", line 47, in get_version
          with open("commit_info.h") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'commit_info.h'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Thank you for your help,
Clement
