### ISSUE TITLE
How to add special function in math parser?

### ISSUE THREAD

**Issue by mayerpan** [Warwick-Plasma/epoch#377]
Hello everyone.
I am trying to add bessel special function in math parser just to get a bessel beam. I am new to Fortran so I just change the source code by looking into the supported gauss function. Here is what I do:
1) in the src/parser/evaluator_block.F90 add:
    IF (opcode == c_func_bessel) THEN
      CALL  get_values(2,values)
      CALL  push_on_eval(BESSEL_JN(values(1),values(2)))
      RETURN 
    END IF
2) in the src/parser/tokenizer_block.f90 add:
    ELSE IF (str_cmp(name,'bessel')) THEN
      as_function = c_func_bessel
3) in the src/constants.F90
  INTEGER, PARAMETER :: c_func_bessel = 48
While i am compiling I got the error:
       CALL  push_on_eval(BESSEL_JN(values(1),values(2)))
                         1
Error: Function ‘bessel_jn’ at (1) has no IMPLICIT type
make[1]: *** [evaluator_blocks.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/gpfs/share/home/1801110253/epoch/epoch2d'
make: *** [commit] Error 2
 It seems like bessel_jn function is not intrinsically supported in gfortran.
How could I add the special function in math parser?

**Comment by Status-Mirror** [comment]
Hi Mayer,

The Maths Parser is a complicated feature, and I agree that BESSEL_JN (or even BESJN) doesn't seem to be supported by GFORTRAN. I think an easier solution here would be to use the existing _interpolate_ feature in the Maths Parser, discussed in the documentation:
https://epochpic.github.io/documentation/code_details/maths_parser.html

Here you can simply tabulate the values of your Bessel function, and the code can interpolate between them. Let us know if this doesn't work for your application.

Cheers,
Stuart
