### ISSUE TITLE
Sinusoidal laser profile rather than gaussian

### ISSUE THREAD

**Issue by ReemRad** [Warwick-Plasma/epoch#383]
Dear developer,

Is it possible to define sinusoidal function in laser profile , i.e. profile = sin(y) ? if it is yes, how I should define t_profile to include time, laser_mean and laser_fwhm?

Regards,
Reem

**Comment by Status-Mirror** [comment]
Dear Reem,

Thanks for getting in touch. EPOCH does support sinusoidal functions for profiles. A full list of the functions available in the EPOCH maths parser is present here: https://epochpic.github.io/documentation/code_details/maths_parser.html

sin(y) would work, but this probably wouldn't give you your desired behaviour, as I think the argument is expected in radians, not metres. For example, if you wanted your y-profile to have a full-width-half-maximum y_fwhm, then the profile should read:

profile = cos( y * 2.0 * pi / (3.0 * y_fwhm))

As this function makes the profile 0.5 when y is +/- 0.5 * y_fwhm.

A similar trick may be done with the temporal profile. If t_peak is the time where the laser peak passes into the simulation window, then

t_profile = cos( (time - t_peak) * 2.0 * pi / (3.0 * t_fwhm) ) 

should give you the correct temporal profile. This peaks at time = t_peak (cos(0) = 1), and when (time - t_peak) is +/- 0.5 * t_fwhm, this becomes cos( pi / 3) = 0.5.

Let me know if this doesn't return the desired behaviour.

**Comment by Status-Mirror** [comment]
P.S. - Make sure you only use these profiles where the values are positive, as EPOCH may crash for negative profile values. This can be fixed using if(...) statements, as outlined in the Maths Parser page.

**Comment by ReemRad** [comment]
Hi Stuart,

Thanks for your reply. One question is there a particular value for  y_fwhm
to get cos( pi / 3) = 0.5 ?
I'm not sure if I have to make  y_fwhm = t_fwhm in ps

Many thanks,
Reem

**Comment by Status-Mirror** [comment]
Hi Reem,

When you have a laser pulse with spatial and temporal profiles, you tend to characterise these profiles in terms of the fwhm. Both y_fwhm and t_fwhm are set by you (e.g. set y_fwhm to 5.0e-6 to get a 5 micron fwhm on your spatial profile).

On units, the arguments of cos(...) must be dimensionless. For the lines:

profile = cos( y * 2.0 * pi / (3.0 * y_fwhm))
t_profile = cos( (time - t_peak) * 2.0 * pi / (3.0 * t_fwhm) )

we find y_fwhm must have the same units as y. In EPOCH, y is measured in metres. To see the y values of each cell, you can output the grid variable in the output dumps.

Similarly, for the temporal profile, t_peak and t_fwhm must have the same units as the simulation time, "time". In EPOCH, this are measured in seconds. 

I have attached an input deck which should produce the desired behaviour: [input_file.txt](https://github.com/Warwick-Plasma/epoch/files/9392850/input_file.txt). Be sure to change the name to input.deck before running.

Cheers,
Stuart
