### ISSUE TITLE
wrong values in dist_fn block

### ISSUE THREAD

**Issue by zhaoq2015** [Warwick-Plasma/epoch#387]
In order to test the dist_fn block, I tried to plot the distribution of photons in the x-y plane and got wrong values, can anayone help me?
Thank you very much for any advice.

![correct](https://user-images.githubusercontent.com/44223809/187380384-32dc7279-747d-44e6-94ec-602e96192974.png)
this is the correct plot of photon distribution plotted with normal SDF files
![incorrect](https://user-images.githubusercontent.com/44223809/187380595-fdd81c68-e212-46c7-86dd-5fb2eb8084aa.png)
this is the incorrect plot of photon distribution plotted with distribution function generated with dist_fn block
[input.txt](https://github.com/Warwick-Plasma/epoch/files/9450876/input.txt)
this is my input file

**Comment by zhaoq2015** [comment]
I got similar photon distribution by using "range1 = (1, 1)" & "range2 = (1, 1)", however the peak intensity is still incorrect.
![屏幕截图 2022-08-30 165033](https://user-images.githubusercontent.com/44223809/187393369-4081b2f4-09c3-401d-98bb-f24371051b4c.png)

**Comment by Status-Mirror** [comment]
Hi @zhaoq2015,

Apologies for the late response, we're currently sorting through our backlog of issues.

I was able to run your input deck and I generated this image:
![dist_fn](https://user-images.githubusercontent.com/38282483/216320810-acd3de23-7ca1-4d18-bb3a-117045ade42e.png)

This was run using the latest version of EPOCH, and was plotted using the MATLAB commands:
```perl
data = GetDataSDF('0012.sdf');
x_centres = data.dist_fn.x_y.photon.grid.x;
y_centres = data.dist_fn.x_y.photon.grid.y;
[x_plot, y_plot] = meshgrid(x_centres, y_centres);
surf(x_plot, y_plot, data.dist_fn.x_y.photon.data', 'EdgeColor', 'none')
colorbar
view(2)
```

I'm not sure what version you were running, but these numerical errors are no longer present in the code.

Cheers,
Stuart
