### ISSUE TITLE
Chirped pulse?

### ISSUE THREAD

**Issue by TrumeAAA** [Warwick-Plasma/epoch#390]
Hi,

How to make a chirped laser pulse ?
Any help or suggestion will be helpful.

Thanks.

**Comment by smax520** [comment]
Hi, TrumeAAA.
in laser block you can make lambda, or frequency not constant, but  time-dependent.
smth like:
lambda=1*micron*cos(time)  #  here you need to choose the appropriate periodic function

**Comment by Status-Mirror** [comment]
Hi all,

Thanks for the reply smax520! This is correct - EPOCH does support time-varying laser frequencies and wavelengths.

If you have switched on field ionisation in the control block, just be aware that the field ionisation rates are calculated using the laser frequency at the start of the simulation.

Cheers,
Stuart
