### ISSUE TITLE
reduce the group velocity of  laser

### ISSUE THREAD

**Issue by HLQzZ** [Warwick-Plasma/epoch#392]
Dear developers,

I want to reduce the group velocity of  laser to make it interact with the electron beam.Is there any way to reduce the group velocity of laser?
Any help or suggestion will be helpful.

Thanks.

**Comment by Status-Mirror** [comment]
Hi HLQzZ, 

The laser block won't be able to adjust the laser group velocity - laser propagation is determined using the Maxwell field solver, and will always be the speed of light (in a vacuum).

If the laser travels through a plasma, the laser group velocity can be reduced by changing the plasma density. See equation (1) in [Yoffe (2021) "Controlling the group velocity of an intense laser pulse using a pre-pulse"](https://strathprints.strath.ac.uk/76275/1/Yoffe_etal_SPIE_2021_Controlling_the_group_velocity_of_an_intense_laser_pulse_using_a_pre_pulse.pdf) for more physics insight.

Hope this helps,
Stuart

**Comment by HLQzZ** [comment]
Hi Stuart,


Thanks for your help. The plasma can only reduce the laser group velocity to 0.9992c, which is not enough for our&nbsp;simulation. We are considering using the Field block to simulate a laser with the group velocity of about 0.5c.&nbsp;Can the Field block complete the simulation?


HLQ






------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Stuart ***@***.***&gt;;
Send time:&nbsp;Tuesday, Sep 20, 2022 6:39 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [Warwick-Plasma/epoch] reduce the group velocity of  laser (Issue #392)





 
Hi HLQzZ,
 
The laser block won't be able to adjust the laser group velocity - laser propagation is determined using the Maxwell field solver, and will always be the speed of light (in a vacuum).
 
If the laser travels through a plasma, the laser group velocity can be reduced by changing the plasma density. See equation (1) in Yoffe (2021) "Controlling the group velocity of an intense laser pulse using a pre-pulse" for more physics insight.
 
Hope this helps,
 Stuart

**Comment by Status-Mirror** [comment]
Hi HLQ,

The field block can only set fields at the start of the simulation. These fields would then evolve according to Maxwell's equations, and I don't know if they would travel at the speed you'd want them to.

If you want to manually specify the fields in each cell, at each time-step, then I think you would need to edit the source code. I would advise you only attempt this if you're comfortable coding in FORTRAN.

In the epoch1d.F90, epoch2d.F90 or epoch3d.F90 files, you'll find the core PIC loop. This calls the commands which update the fields - there are two.
-  CALL update_eb_fields_half
-  CALL update_eb_fields_final

To overwrite the field solve, you need to comment these out, and (for epoch2d) replace them with something like:
do iy = 1, ny
  do ix = 1, nx
     ex(ix,iy) = something 
   end do
end do

If you're doing this, it may be helpful to know:
- x_grid_min_local: cell-centred x position of the cell with ix = 1 on the local rank
- dx: length of a cell in the x direction
- time: time of the current time-step

Hope this helps,
Stuart
