### ISSUE TITLE
A question about the number density read from the file

### ISSUE THREAD

**Issue by tomdg1626003** [Warwick-Plasma/epoch#393]

**Comment by TomGoffrey** [comment]
@tomdg1626003 did you get this sorted? Sorry for the slow response, I was away at a conference last week.

**Comment by tomdg1626003** [comment]
Thank you very much for your reply. The problem has been solved. I hope to continue to learn from you in the future. Keep in touch.



---Original---
From: "Tom ***@***.***&gt;
Date: Mon, Sep 26, 2022 19:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Warwick-Plasma/epoch] A question about the number density readfrom the file (Issue #393)




 
@tomdg1626003 did you get this sorted? Sorry for the slow response, I was away at a conference last week.
