### ISSUE TITLE
About adding new QED block "radiative spin-polarization effect"

### ISSUE THREAD

**Issue by Michael-Gong** [Warwick-Plasma/epoch#395]
Dear epoch developer,

We implemented the new QED block about radiative spin-polarized electron in EPOCH and obtained some interesting results. A relevant publication can be found: https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.127.165002
A more original publication about the QED model of radiative spin polarization can be seen: https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.122.154801

Last week, we presented this work in a QED laser plasma conference. People thought these were very interesting results and asked me whether we could add our new model in EPOCH's open source version.  
I ask myself why not. 

I have the revised files including the new model in my ./epoch2d/src directory of epoch-4.14.8 version, but I am not very familiar with the pull requests.  
Can I just sent my ./src directory to you through private email and you update this QED model in the new version of EPOCH.

Thank you for your time.
Best regards,
Zheng Gong

**Comment by TomGoffrey** [comment]
Hi @Michael-Gong, can you send over the source code to t.goffrey.1@warwick.ac.uk and I'll take a look and discuss at our next dev meeting? Thanks.

**Comment by Michael-Gong** [comment]
Hello @TomGoffrey, thank you for providing your email.

**Comment by Status-Mirror** [comment]
Hi all,

I'm going to close this issue page for now, as I believe this topic will switch to private discussions within the QED PIC group. I'm lead to believe they've been in touch? Feel free to continue posting to this thread if you can't seem to get through to people.

Thank you for the contribution,
Stuart

**Comment by amarsarari** [comment]
Hi is spin -polarization for particle is included in epoch. How it will work could you please guide me.
