### ISSUE TITLE
Why does the x_max boundary reflect 5-10% of the electromagnetic field? 

### ISSUE THREAD

**Issue by xinyingyixia** [Warwick-Plasma/epoch#398]
When I try to set the x_max boundary open (simple outflow or conduct or cpml_outflow), I find the  boundary will reflect **5-10%** of the electromagnetic field which makes me very confused. I really hope someone can help find the answer.

Here is my input card and my field data: 
[input.txt](https://github.com/Warwick-Plasma/epoch/files/9831500/input.txt)

begin:constant

  lambda0 =1.0*micron   #laser wavelength  8e-6
  lambdaL=0.8*micron
  omega0 = 2.0*pi*c/lambdaL  #laser frenquency
  # plasma critical density
  n_c = critical(omega0)        # /m3
   n0 = 5e24
  #n0 = 1.0*n_c
  #n1 = 2.0*n_c
  omega_p = sqrt(n0*qe*qe/me/epsilon0)
  lambda_p = 2*pi*c/omega_p
  period0=lambda0/c
  periodL=lambdaL/c    #laser period
# laser 1 
  # laser amplitude
  a_peak0 = 2.0 
  E_peak0 = a_peak0*me*omega0*c/qe
  intensity_w_cm2_t = a_peak0*a_peak0*1.37e18/(lambdaL*1e6)^2
# guass function parameter for space envelop
   Tau = 40 * femto
# constant intensity duration
   d= 400 * femto
# guass function parameter for space envelop
  w_0 = 5*lambda0  # Beam waist size FWHM=2w0*sqrt(ln2)
  x_spot = 25.0*lambda0  # Distance from x_min to spot 
  x_R = pi * w_0^2 / lambdaL # Rayleigh range
  RC = x_spot * (1.0 + (x_R / x_spot)^2)  # Radius of curvature on x_min
  w_bnd = w_0 * sqrt(1.0 + (x_spot/x_R)^2) # Spot size at x_min
  gouy = atan(x_spot/x_R) # Gouy phase shift at x_min  
# positions in x,y directions
  x0 = 0.0*lambda0
  x1 = 100*lambda0
# positions in flat
  flat0 =30.0*lambda0
  flat1 =130.0*lambda0
end:constant

begin:control
# global number of gridpoints   box  100*40 
  nx = 900     #15/cell
  ny = 240     #15/cell
# global number of particles
  t_end = 600* femto
# size of simulation domain 
  x_min = 0.0*lambda0
  x_max = 80.0*lambda0
  y_min = -25.0*lambda0
  y_max = 25.0*lambda0
  #field_order=4
  smooth_currents = T
  #dt_multiplier=0.95
  stdout_frequency = 40
  print_constants = T
  use_more_setup_memory = T
end:control

begin:boundaries
  cpml_thickness = 16
  cpml_kappa_max = 20
  cpml_a_max = 0.2
  cpml_sigma_max = 0.7
  bc_x_min = cpml_laser
  bc_x_max = cpml_outflow
  bc_y_min = cpml_outflow
  bc_y_max = cpml_outflow
end:boundaries

begin:laser
  boundary = x_min
  id = 1 
  #amp = E_peak0 * w_0 / w_bnd   # amplitude on boundary 
  intensity_w_cm2 = intensity_w_cm2_t
  lambda = 1.0*lambdaL
  pol_angle = 0.0*pi   # 0.0*pi:p   
  #phase = 0.0*pi + 2.0 * pi/ lambdaL * y^2 / (2.0* RC) - gouy 
# 聚焦在xmin,RC应是无穷大,w_bnd=w_0;gouy=0;phase = 0.0*pi
  phase = 0.0*pi 
  #profile = supergauss(y,0,w_bnd,4)
  #profile = gauss(y, 0, w_bnd)  
  #profile = gauss(y, 0, w_0) 
  profile = 1 
  #t_profile= semigauss(time, 1 ,0.001, 20e-15 )
  t_profile=gauss(time,30e-15,30e-15/1.7/1.6651)  #Tau=2w0*sqrt(ln2)
  #t_profile = if(time lt Tau, time/Tau,if(time lt Tau+d,1,if(time lt (2*Tau+d),(2*Tau+d-time)/Tau,0)))
  #t_profile =1
  t_start = start
  t_end = 60 * femto
end:laser
##################foil#################

begin:species
   name = electron1
   charge = -1.0
   mass = 1.0
   npart_per_cell = 20
   #density = if( x gt x0 and x lt x1 and  y gt y_min  and y lt y_max,  n0, 0) 
  # density = if( y gt y_min and y lt y_max,  density(electron1), 0) 
  #density = if( x gt x0 and x lt x1 and  y gt y_min  and y lt y_max,  if(x lt flat0, (x-x0)/(flat0-x0),if(x lt flat1,1,if(x lt x1,(x1-x)/(x1-flat1),0))), 0)*n0
  #density = if( x gt x0 and x lt x1 and  y gt y_min  and y lt y_max,  if(x lt flat0, (x-x0)/(flat0-x0),if(x lt flat1,1,0)), 0)*n0
  #density = if( x gt x0 and x lt x1 and  y gt y_min  and y lt y_max, 1 ,0)*n0
  density = if( x gt x0 and x lt x1 and  y gt y_min  and y lt y_max,  if(x lt flat0, (x-x0)/(flat0-x0),if(x lt flat1,1,0)), 0)*0
   #temperature_ev=1e4
end:species

begin:species
   name = He1
   charge = 1
   mass = 1836*4
   npart_per_cell = 20
   density = density(electron1)
   #temperature_ev=10
end:species

begin:subset
   name = selected0
   random_fraction = 0.01
   include_species = electron1
   include_species = He1
end:subset

begin:output
 # information of field
  name=laser
  file_prefix=field
  dt_snapshot = 25* femto
 # Properties on grid
  grid = always +single
  ex = always + single
  ey = always + single
  ez = always + single
  bx = always + single
  by = always + single
  bz = always + single
end:output

https://user-images.githubusercontent.com/94546775/196989123-ca9544f9-e384-4f34-a350-b3c6378675d2.mp4

**Comment by Status-Mirror** [comment]
Hi Xinyingyixia,

It does seem like odd behaviour. I notice you're using CPML boundaries, which are quite complex. If you want better laser transmission at the boundaries, I suggest using simple_outflow instead of cpml_outflow. A full list of the available boundaries is here:
https://epochpic.github.io/documentation/input_deck/input_deck_boundaries.html

In the meantime, I'll pass this onto the developer who worked on the CPML boundaries to see if this is desired behaviour, or a bug which needs correcting.

Thanks,
Stuart

**Comment by xinyingyixia** [comment]
> Hi Xinyingyixia,
> 
> It does seem like odd behaviour. I notice you're using CPML boundaries, which are quite complex. If you want better laser transmission at the boundaries, I suggest using simple_outflow instead of cpml_outflow. A full list of the available boundaries is here: https://epochpic.github.io/documentation/input_deck/input_deck_boundaries.html
> 
> In the meantime, I'll pass this onto the developer who worked on the CPML boundaries to see if this is desired behaviour, or a bug which needs correcting.
> 
> Thanks, Stuart

Hi, Stuart. Thanks a lot for your attention. In fact, the problem confuses me a lot because I've tried almost all the  boundaries(include simple_outflow ). And it always shows the behaviour like in the video above.

**Comment by Status-Mirror** [comment]
You're right, I'm able to reproduce this behaviour with both cpml and simple boundaries.

I believe this is caused by numerical errors with the finite difference field solver, so while I can't remove the false reflection, I can suggest ways to minimise it.

Using simple_outflow instead of cpml_outflow seemed to reduce the reflected wave to a magnitude of ~250 T, or about 1% of the initial pulse. I was able to reduce this to ~150 T by introducing a spatial Gaussian profile, which prevented the pulse from touching the y min/max boundaries. It's not ideal, but it seems better than the 5000T pulse in the CPML simulation.

**Comment by xinyingyixia** [comment]
Thank you for your suggestions, and I'll try to make the reflection smaller. Your ways are great.
