### ISSUE TITLE
How to use EPOCH to export local strength a of drive laser profile？

### ISSUE THREAD

**Issue by xinyingyixia** [Warwick-Plasma/epoch#407]
As shown in the figure below. 
![1668496764425](https://user-images.githubusercontent.com/94546775/201854531-0c1c9ec2-5b5b-463c-872f-0d9d1bd7be38.png)

**Comment by Status-Mirror** [comment]
Hi Xinyingyixia,

The normalised vector potential is defined as: 
- a0 = e * E / (omega * me * c)

where e is the electron charge, E the electric field, omega the laser angular frequency, me the electron mass, and c is the speed of light. Using the equations:
- I = eps0 * c * E^2
- omega = 2 * pi * c / lambda

where eps0 is the permittivity of free space, lambda the laser wavelength, and I is the instantaneous (not cycle-averaged) intensity, then we may express a0 as:
- a0 = sqrt(0.25 * e^2 * I * lambda^2 / (pi^2 * c^5 * eps0 * me^2))

or approximately
- a0 = 6.03e-6 * sqrt(I * lambda^2)

where intensity and wavelength are in SI units. You may see this more commonly written with the cycle-averaged intensity, yielding 8.5e-6 as the pre-factor, but this form is not useful here.

For the wakefield problem shown here, you may assume that the laser wavelength lambda does not change over the simulation, so this may be taken to be 800e-9. To get the instanteous intensity in each cell, you may output the Poynting vector grid variable S, as the magnitude of this vector is equivalent to the instantaneous intensity. Once you have I and lambda, you may deduce a0 in each cell.

To output the Poynting vector add the line:
`poynting_flux = always` 
to the output block. The full output block documentation may be found here:
https://epochpic.github.io/documentation/input_deck/input_deck_output_block.html

Hope this helps,
Stuart

**Comment by xinyingyixia** [comment]
I got it! Thank you, Status.
