### ISSUE TITLE
Is there any tricks that could get the magnetic field data that only generated by ions or electrons （no laser field）?

### ISSUE THREAD

**Issue by xinyingyixia** [Warwick-Plasma/epoch#416]
Dear developer!
How can I output the magnetic field data that only generated by ions or electrons, I mean without the electromagnetic field of the input laser which is very large. 
 I have a headache about it. Maybe it's impossible I guess.

**Comment by Status-Mirror** [comment]
Hey @xinyingyixia 

This is a complicated issue. The EM fields evolve according to Maxwell's equations - the laser causes charge motion, resulting in currents which update the field. Even though particle current causes the field change, it's still indirectly driven by the laser. There's also a lot of noise in PIC codes which is neither the laser nor the particles.

If you knew the input laser profile, you could subtract these fields from the E, B output - but plasma can change the laser profile, so you may subtract the wrong thing.

Is there a particular field configuration you're interested in seeing?

Cheers,
Stuart

**Comment by Status-Mirror** [comment]
Hi again,

I'm going to mark this issue closed for now - but feel free to continue commenting if you have any further questions!

Cheers,
Stuart
