### ISSUE TITLE
possible issue about the output when use the subset module to select particles

### ISSUE THREAD

**Issue by zwjlpi** [Warwick-Plasma/epoch#423]
Hi,
When I use the subset block to select specific particles, all the particle variables in the output SDF file could contain the positions of these particles, even the 'particles=never' was set in the output block. These repeat data would occupy large memory space and lead to the extremely large size of the SDF file. How can I avoid this problem?

**Comment by Status-Mirror** [comment]
Hi @zwjlpi 

Do you have an input deck which is writing subset particle positions you didn't ask for? I think you should be able to choose which subset particle properties you want to output.

Cheers,
Stuart
