### ISSUE TITLE
sdf modules for Windows

### ISSUE THREAD

**Issue by sivovivanov** [Warwick-Plasma/epoch#425]
Hello,

I wanted to ask whether there is a way to compile and use the sdf/sdf_helper modules on Windows? Just now I am resorting to using WSL2 to use the two modules. Ideally, I'd like to be able to run them in my native Windows environment, as it is where my main Python development happens.

As I mentioned, I do have an alternative so it is not a major problem if the answer is "no". I thought it'd be best to ask, as I have not figured out a way to get the sdf module working under Windows. Thanks!

**Comment by Status-Mirror** [comment]
Hi @sivovivanov 

Another developer may swoop in to correct me, but I'm not aware of any Windows installer for the SDF_helper. All the information on the Python libraries seems to be present here:
https://epochpic.github.io/documentation/visualising_output/python.html

Cheers,
Stuart

**Comment by sivovivanov** [comment]
Hi Stuart,

Yes, that is the resource I have been referring to during my usage of the sdf_helper and underlying sdf modules for Python. 

As I mentioned, it works just fine under WSL2 so it is not a real problem for me. EPOCH in general compiles and runs perfectly well in WSL2, being able to utilise all cores of my system when using mpirun/mpiexec to launch it.

Thanks for taking the time to respond! 

All the best,

Slav
