### ISSUE TITLE
Electron beam out of shape

### ISSUE THREAD

**Issue by TrumeAAA** [Warwick-Plasma/epoch#426]
Hi, I tried to add a bunch of electron with gaussian form both in time and space as follow:
`
begin:constant
  lambda = 0.8 * micron
  omega = 2 * pi * c / lambda
  cycle = lambda/c
  den_cone = 0.3*critical(omega)
  # particle beam parameters
  ne = 0.03*critical(omega)
  density_ebeam = gauss( y , 0*lambda, 2*lambda/2/sqrt(loge(2)) )
  tprofile_beam = gauss( time , 6*cycle , 2*cycle/2/sqrt(loge(2)) )
end:constant

begin:injector
  boundary = x_min
  species = electron
  number_density = ne*density_ebeam*tprofile_beam
  temperature_x = 10.0
  drift_px = drift_p
  nparticles_per_cell = 48
end:injector
`
However, in the result, the shape of the electron beam changes wile travelling as follows:
![8](https://user-images.githubusercontent.com/94948250/205445012-cc93dff8-6aba-4708-b7f2-d96dd6f49885.png)
![13](https://user-images.githubusercontent.com/94948250/205445020-8fefd0a5-89ed-4a25-a40b-52922cf4310b.png)
![15](https://user-images.githubusercontent.com/94948250/205445028-ca017f4b-6997-47b1-a642-3554a0dc40b3.png)
![20](https://user-images.githubusercontent.com/94948250/205445034-ece720d7-8ca9-41e3-97e2-8948549a5f9c.png)
There must be something wrong, but I cant figure out.
Does anyone know about it?
Any suggestion will be helpful!

**Comment by Status-Mirror** [comment]
Hi @TrumeAAA

I'm not immediately convinced this is unphysical. This seems to be a very high density for an electron bunch - the currents formed by this charge bunch would form large fields, changing the bunch shape. Is this in a plasma or a vacuum?

Our group were co-authors on a paper which studied how bunch shapes changed over large distances: https://iopscience.iop.org/article/10.1088/1361-6587/ac0b9d/meta

To test if this is a problem with the code, increase the particle momentum, and drastically reduce the density (say 10/m3). The fields should now be too weak to affect the bunch shape in a vacuum, and you should see the shape maintained.

Hope this helps,
Stuart

**Comment by Status-Mirror** [comment]
I'm going to mark the issue as closed now, but feel free to ask any further questions you have in this chain.

Cheers,
Stuart

**Comment by TrumeAAA** [comment]
Hi, in strong-field QED, for extremely relativistic electron beam in vaccum, the effective field should be very small so the beam will propagate in vaccum with its shape almostly unchanged [DOI: 10.1103/PhysRevLett.126.064801] at the same time the beam should not experience strong-field QED radiation.
So I performed 2 2D simulations(gamma factor = 100, 20000) and turned off the photon_dynamics to see the position it was generated. the result are as follow:
![100](https://user-images.githubusercontent.com/94948250/218293205-d2318a59-8d5a-496e-9026-8e808863c59f.png)
![20000](https://user-images.githubusercontent.com/94948250/218293207-dc012187-3b06-4f7c-9ee6-f116ebd0c46f.png)
The first fig: gamma factor=100; The second fig: gamma factor = 20000.
The shape of the electron beam did keep unchanged for higher gamma factor case wihch is easy to understand. However, in both cases there is radiation and the process happens in the area close to the boundary where the beam is launched. The process will not happen in the right part of the simulation box as we can expect.
I dont understand this. Did I make any mistakes?
Any suggestion will be helpful!
All the best,
H.Ai
