### ISSUE TITLE
plot electric field Ex over the spot size

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#427]
Hello,
I tried to plot Ex using a mean function in MATLAB but I'm making some mistake.
Please, how can I plot the average of the longitudinal electric field over the spot size?

Does anyone know about it?
Any suggestion will be helpful.

Thank you in advance.

**Comment by Status-Mirror** [comment]
Hi @mimboch 

I'm away from my workspace at the moment, but I may be able to give you some MATLAB code when I return (in about a week).

In the meantime, it's not clear to me what you want to plot. What axes do you want in the figure, and what data needs averaging (space or time)?

Cheers,
Stuart

**Comment by mimboch** [comment]
Hello Stuart,
Thank you very much for you quick reply.
I want to plot **data.Electric_Field.Ex_averaged** versus **x**. I think , I should plot it over the spot size , but I don't know how can I do it?
All the best.

**Comment by RatulSabui** [comment]
in python, you can do an sdf.read() to read the file onto a variable (say x).
a = getattr(x,<Ex variable name>) #should extract the data from x.
array = numpy.array(a.data) #will give you the field data as a numpy array
average along the axes to get a spatial average.

you can also take line cuts or isolate individual planes.

If I am not wrong, this should solve your issue. Just take care to orient your array the correct way.

**Comment by Status-Mirror** [comment]
Assuming you're using the 2D version of the code, you could use:

```
Ex = data.Electric_Field.Ex_averaged.data;
x_edges = data.Electric_Field.Ex_averaged.grid.x;
y_edges = data.Electric_Field.Ex_averaged.grid.y;
x_centres = 0.5*(x_edges(2:end) + x_edges(1:end-1));
y_centres = 0.5*(y_edges(2:end) + y_edges(1:end-1));
```

where a cell with indices ix, and iy has a position given by x_centres(ix), y_centres(iy), and an averaged field value Ex(ix, iy).

Let us define a window over your focal spot, characterised by upper and lower cell indices x2 and x1 for x, and y2 and y1 for y. After you set values for the variables x1, x2, y1, y2, you could then do:

```
window_x = x_centres(x1:x2);
window_y = y_centres(y1:y2);
window_Ex = Ex(x1:x2,y1:y2);
```

Then finally, you can make your plot:

```
[x_plot, y_plot] = meshgrid(window_x, window_y);
surf(x_plot, y_plot, window_Ex','EdgeColor','none');
view(2);
colorbar;
```

Hope this helps,
Stuart

**Comment by mimboch** [comment]
Hi Status,
My apologies for the delayed response, I couldn't answer you earlier.
Thank you very much for your help, I used your code, because I want to plot Ex versus x not image .
please see the code used by me and the attached figure to understand me better




```
data=GetDataSDF('/home/bou/epoch-4.17.16/epoch2d/0010.sdf');
Ex = data.Electric_Field.Ex_averaged.data(:,end); % the the error is located at this level, because I can't take all the values of Ex.
f = 0.01;            % cell size in nm
e = 1:7999;       %grid number
x = f*e;              length of my box simulation
plot (x,Ex)
```
![Ex_220](https://user-images.githubusercontent.com/46644633/209147723-98c580c2-a379-4794-90fd-53822834086f.png)
.
