### ISSUE TITLE
issue about the work of id_min and id_max in the subset block

### ISSUE THREAD

**Issue by zwjlpi** [Warwick-Plasma/epoch#431]
Hi,
I just try to use the id_min and id_max to track some particles in the simulation, but the data of the particles who's id is between the id_min and id_max  would not output, until I add the 'always' dumpmask before the selected subset in the output block.  The input.deck is as follows. When I remove the 'always' in the output block, the output SDF file would be empty. And other restrictions in the subset block work normally. In the situation when the number of total macroparticles is extremely large, it will take too much memory waste on these unwanted 'id' data. Looking forward for your help.

begin: control
  nx = 600
  #nparticles = 4e6
  t_end = 100 * femto
  x_min = -20 * micron
  x_max = 100 * micron
end: control

begin: boundaries
  bc_x_min = simple_laser
  bc_x_max = open
end: boundaries

begin:window
  move_window = T
  window_v_x = c
  window_start_time = 0*femto
  window_stop_time = 1000*femto
  bc_x_min_after_move = simple_outflow
  bc_x_max_after_move = simple_outflow
end:window

begin:laser
    boundary = x_min
    id = 1
    intensity_w_cm2 = 1e20
    lambda = 1.06 * micron
    pol_angle = 0.0
    phase = 0.0
    t_profile = gauss(time, 120e-15, 40.0e-15)
end:laser

begin:species
  charge = -1.0
  mass = 1.0
  name = Electron
  npart_per_cell = 100
  #fraction = 0.5
  number_density = if((x gt 40*micron)and(x lt 1000*micron),1e30,0.0)
end:species

begin:species
  charge = 1.0
  mass = 1836
  name = Proton
  npart_per_cell = 100
  number_density = if((x gt 40*micron)and(x lt 1000*micron),1e30,0.0)  
  dumpmask = never
  #fraction = 0.5
end:species

begin: constant
  lambda0 = 1.053 * micron
  freq = c / lambda0
  omega = 2 * pi * freq
  nc = epsilon0 * me * omega ^ 2 / qe ^ 2
  Tau_FWHM = 60 * femto
  wt0 = Tau_FWHM / 2.0 / sqrt(loge(2.0))
end: constant

begin:subset
  name = tracking
  id_max = 2000
  id_min = 10
  include_species = Electron
end:subset

begin:output
  name = o1
  file_prefix = tracking
  dt_snapshot = 10.0 * femto
  particle_grid = tracking
  particle_energy = tracking
  id = always+tracking
end:output

**Comment by Status-Mirror** [comment]
Hi @zwjlpi 

I can reproduce your issue, and I think it's a problem with the code. Current working theory - particles are only assigned ID when you tell the code to dump them, and as your subset relies on ID, it only contains particles when you dump all ID. This isn't ideal.

I'll reply on this thread when the fix goes up. In the meantime, there's a work-around which you may be able to use. You can split your electron species into two species, where the number densities in each sum to the original. Then, you can have one low density species with few particles, and one high density species for your bulk. Finally, you could only output the positions and ID for the smaller electron species, to save memory.

Hope this helps,
Stuart

**Comment by Status-Mirror** [comment]
Apologies for the delay - I believe I have fixed this issue, and I'm currently merging the fix into the main branch. Subsets are now capable of writing their own partilce ID values if nothing else has done this already. This means particles will always have ID values for `id_min` and `id_max` to use. Previously this was only the case if a different diagnostic wrote IDs, like when you included the `always` key in the `id` output.

Hope this helps,
Stuart
