### ISSUE TITLE
QED bloch and Fields of generated photons

### ISSUE THREAD

**Issue by TrumeAAA** [Warwick-Plasma/epoch#432]
Hi, I used the QED block to study the generation of photons by charged particles in strong laser fields, Is it possible to plot the electric and magnetic fields of the generated photons?
Any suggestions will be help, Thank you very much!

**Comment by Status-Mirror** [comment]
Hi @TrumeAAA 

The generated photons are treated as particles in the simulation. The QED routines typically produce photons with high energy, and a wavelength smaller than the simulation grid. As a result, the EPOCH field solver does not have the resolution required to propagate these as waves, so the particle treatment is a necessity. If you wanted to convert these X-rays/gamma-rays to an EM wave, this would have to be done in post-processing using the particle information.

Hope this helps,
Stuart

**Comment by TrumeAAA** [comment]
Hi, I'm unfamiliar with the process of converting the X-rays/gamma-rays to EM wave in post-processing with the particle information. So would you please tell me more about the details or is there any references? Thank you very much for kind reply!

**Comment by Status-Mirror** [comment]
From what I've read, I don't think there's a simple conversion.

You can get the wavelength from E = h*c/lambda, where E is the photon energy, h the Planck constant, c the speed of light and lambda the wavelength.

The EM wavevector, k, is also simple, p = h*k, where p is the momentum, and

**Comment by TrumeAAA** [comment]
Hi, I tried to generate some x-ray or gamma ray photons in laser plasma interaction. And I find that the distribution of the genarated photons is longitudinally localized or longitudinally short which looks like a laser pulse so I wonder if it is possible to get the EM fields of the generated photons and I think it may be difficult to consider Wave-particle duality in simulation.

**Comment by TrumeAAA** [comment]
I want to konw if they are coherent, If yes then it will be a laser pulse. I think if I know the EM field then it is easy to judge if they are coherent.

**Comment by TrumeAAA** [comment]
Yes, in some scheme the photon generation is due to Radiation-Reaction, in which the electrons are trapped in the intense laser pulses and then photons are generated when the electrons moves to the peaks of laser pulses. But I'm still not sure about the coherence of the generated gamma photons.

**Comment by Status-Mirror** [comment]
It might be possible to check for coherence, but I think this would come from theory and not EPOCH. I don't think this is information which can be extracted from the code in its present state.

Sorry we couldn't be more helpful,
Stuart
