### ISSUE TITLE
Collisions/ionization not active?

### ISSUE THREAD

**Issue by bzdjordje** [Warwick-Plasma/epoch#433]
I am trying to run Epoch with collisions and ionization concurrently and it seems as if the laser is not seeing the plasma at all, below are figures of the laser field and unionized ion density. The input deck is attached and this was tested with Epoch 4.17 and 4.18. 
![image](https://user-images.githubusercontent.com/4984500/210465121-1145445a-a476-437c-9a40-d8dba96f707f.png)
![image](https://user-images.githubusercontent.com/4984500/210465130-3853f806-a824-460a-832e-13a8e274a42e.png)

[input_deck.txt](https://github.com/Warwick-Plasma/epoch/files/10340725/input_deck.txt)

**Comment by Status-Mirror** [comment]
Hi Bzjordje,

If you're using 4.17 or 4.18, this input deck will not trigger ionisation. You've specified the energies, but you haven't switched on the flags which run ionisation. These are:

field_ionisation - control block
collisional_ionisaton - collisions block (this will NOT give the correct collisional ionisation in versions 4.17 or 4.18 - update to the latest version to use this accurately)

Without these, your neutral particles are never ionised, and neutral particles can't be seen by the EM field solver - hence the laser passes straight through.

Note that if you re-download the code, you'll have version 4.19, with different syntax in the species blocks and collisions block for ionisation.

Hope this helps,
Stuart

**Comment by Status-Mirror** [comment]
I'm going to mark this issue as closed for now, but feel free to continue messaging on this thread if you have any further issues.

Cheers,
Stuart

**Comment by bzdjordje** [comment]
Hi Stuart,
Thank you addressing this issue. I have compiled version 4.19 but am now getting a new error:

*** ERROR ***
 Unable to find the file:
 src/physics_packages/TABLES/ionisation_energies.table

I have tried copying the src directory to the executable path as well as the target output folder but it still does not find the table. Am I supposed to specify something in the Makefile or execution command for this to work?

Thank you,
Blagoje

**Comment by Status-Mirror** [comment]
Hi Blagoje,

When looking up physics tables, EPOCH assumes you are running the code from the directory which has the bin folder in it - e.g., a command like:

`mpirun -np 4 ./bin/epoch2d`

However, sometimes users are unable to run from this directory. In these cases, the user must tell the code where the folder is, using the control block parameter "physics_table_location". Something like:

`physics_table_location = /work/epoch/epoch2d/src/physics_packages/TABLES`

Note that this path must point to the TABLES directory, and not the src directory. I've also realised I need to add this feature to the documentation.

Hope this helps,
Stuart
