### ISSUE TITLE
Detailed deffinition of dir_xy_angle in dist_fn block

### ISSUE THREAD

**Issue by TrumeAAA** [Warwick-Plasma/epoch#434]
Hi, I tried to calculate the angular spectrum of specific particle (photon for example) in a 2D simulation in order to know the emittance of    
that particle. I initially did that by output the dir_xy_angle in the dist_fn block. But I don't know the deffition of dir_xy_angle in the documentation. It says " The flags "dir_xy_angle", "dir_yz_angle" and "dir_zx_angle" calculate the distribution of particle
momentum directions in the X-Y, Y-Z and Z-X planes.". I think I didn't fully understand. 
My question is : does " the particle momentum directions in the X-Y planes " means the angle between the particle momentum and the unit vector in X direction? does it ranges from 0 to pi or from 0 to 2pi or from -pi to pi ?

**Comment by Status-Mirror** [comment]
Hi @TrumeAAA 

You're right that the documentation is a little vague here - I will update it soon.

From reading the source-code file dist_fn.F90, it appears that for `dir_xy_angle`, we have:

```perl
p = SQRT(px**2 + py**2)
IF (p < c_tiny) CYCLE
theta = ASIN(py / p)
IF (px < 0.0_num) theta = SIGN(1.0_num,py) * pi - theta
```

The pattern here seems to be that for `dir_ij_angle`, we collapse the particle momentum onto the $ij$ plane, and return the angle of the particle with respect to the positive $i$ unit vector. Angles range from $-\pi$ to $\pi$, where rotations towards the positive $j$ unit vector give positive angles, rotations towards the negative $j$ unit vector are negative, and particles parallel to the positive $i$ unit vector have an angle of 0.

I'll leave this issue open until I correct the documentation.

Cheers,
Stuart
