### ISSUE TITLE
 calcul of conversion efficiency from laser energy to particles 

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#437]
Hello,
 I want to calculate the conversion efficiency , so I should calculate it by KE/max(Bz), where KE is the Average_Particle_Energy and Bz is the magnetic field along z axis or I have to use  another formula.
Please I really need to calculate it.
Thank you in advance.

**Comment by Status-Mirror** [comment]
Hi @mimboch,

For conversion of laser energy to particle KE, you need to do calculate (total particle KE)/(total laser energy).

To get the total laser energy, add the line:
`absorption = always`
to your output block. This should then output the total laser energy injected into the simulation window for each SDF file.

To get total particle energy, you can output add the lines:
```perl
px = always + species
py = always + species
pz = always + species
weight = always + species
```
Then you can calculate the KE, $E_k$ per macro-particle by using the calculation:
$E_k = \left(\sqrt{(p_x^2 +p_y^2 + p_z^2)c^2 + m^2c^4} - mc^2\right)W_i$
where $m$ is the mass of a single particle of this species (or 0 for photons), and $W_i$ is the macro-particle weight. Finally, you can sum all the kinetic energies together to get a total energy for the species.

Note: If you start with a heated collection of particles, then they will have an initial kinetic energy before the laser arrives. This total must be subtracted from the final total to estimate the kinetic energy gain.

Hope this helps,
Stuart
