### ISSUE TITLE
run the script in test mode

### ISSUE THREAD

**Issue by Sanjeev273** [Warwick-Plasma/epoch#439]
Hi I am new to the Epoch, First, I want to check the corretness of the scipt. Could anyone in the group suggest me that how to run script in test mode ?

**Comment by Status-Mirror** [comment]
Hi @Sanjeev273 

We provide a few input decks for testing applications, along with visualisation instructions for MATLAB, Python, IDL and Visit. This introduction can be found here: https://epochpic.github.io/documentation/examples/workshop_examples.html

The site is still in development, but it contains all the documentation for running the code.

Hope this helps,
Stuart

**Comment by Sanjeev273** [comment]
> 
Hi Staurt, Thak you so much.
