### ISSUE TITLE
some reflection occurs from the boundary 

### ISSUE THREAD

**Issue by MKR100** [Warwick-Plasma/epoch#444]
Hello,
I tried to send a laser pulse from the left side boundary into the simulation box, but when the laser pulse leaves the right side boundary, some reflection from the boundary occurs. Why? Please see attached PDF and input files.

[laserField.pdf](https://github.com/Warwick-Plasma/epoch/files/10703626/laserField.pdf)
[input.txt](https://github.com/Warwick-Plasma/epoch/files/10703645/input.txt)

**Comment by Status-Mirror** [comment]
Hi @MKR100, 

This is a numerical issue with the field-solver method. It's worth pointing out that your reflection has fields around 1% of the injected pulse, which translates to a reflected intensity reduced by a factor of 1.0e-4.

This false reflection can be reduced further by increasing the grid resolution. When I modified your input deck to include 20 cellls per wavelength (instead of 10), I found the reflected Ez amplitude dropped from around 5e9 V/m to around 1e9 V/m.

Hope this helps,
Stuart

**Comment by MKR100** [comment]
Thanks a lot for reply @Status-Mirror. Can we reduce it further with other things. I tried with CPML boundary but could not succeed to minimize it more from the boundary.

**Comment by Status-Mirror** [comment]
CPML isn't something I've looked at before in EPOCH, so I can't personally comment on any improvements I would expect from it.

I teseted a few things, but found little improvement. EPOCH supports higher-order field solvers. When I added the line:

```perl
field_order = 6
```

to the control block of your input deck, I achieved a slight reduction in the reflected Ez amplitude (around 4e9 V/m). When I combined a higher field order with the 20 cells per wavelength, I achieved an amplitude of around 3e9 V/m - actually worse than the default field order at 20 cells per wavelength. Hence, I don't think `field_order` will be of much help.

I also tried changing the field solver using the control block command:

```perl
maxwell_solver = pukhov
```
but this had no effect.

From my testing, the only way to reliably reduce the numerical reflection was to increase the number of cells per wavelength. If these small numerical reflections are problematic, it may be computationally cheaper to extend the x_max boundary to prevent reflection over the simulation run-time, although this is quite extreme.

Apologies I couldn't be of more help,
Stuart

**Comment by MKR100** [comment]
Thank you @Status-Mirror. Yes, you are right. Nothing is working rather than increasing the number of cells per wavelength. For 40 cells per wavelength, I obtained a reflected pulse amplitude of approximately 3e8 V/m. However, that thing makes the system so heavy for long plasmas (~300 µm). Not sure, but for long laser pulses (> 500fs), numerical reflections can be problematic. Note that these numerical reflections are long-lived in the system as it is reflected after some time from the left boundary. It would be very helpful if you find a way to reduce it. Thanks again.

**Comment by Status-Mirror** [comment]
There are limitations to PIC codes - a 300µm plasma is a very large job, you would probably need a cluster to run it. Depending on your simulation, I wouldn't expect a reflected wave with 0.01% the intensity of the driving pulse to be significant to the plasma dynamics. I would advise testing in quick 1D simulations to see if this has any effect on what you wish to model. Unfortunately there isn't much more support I can offer at this time.
