### ISSUE TITLE
warnings in QED block

### ISSUE THREAD

**Issue by TrumeAAA** [Warwick-Plasma/epoch#445]
Hi, I tried to calculate the QED process and get some warnings, but the epoch still works. The warnings are as follows:
![屏幕截图 2023-02-11 145621](https://user-images.githubusercontent.com/94948250/218245386-585695af-e46f-4da4-96c0-907643697c78.png)
![屏幕截图 2023-02-11 145529](https://user-images.githubusercontent.com/94948250/218245392-eb55f4a7-9fc0-4435-affd-9e282c3fb463.png)
![屏幕截图 2023-02-11 145601](https://user-images.githubusercontent.com/94948250/218245398-eb0a56dc-40ae-4e1a-a001-e99c81eeb2f7.png)
By the way, the simulation is a 2D case with 30um in x direction with 1500 grids and 20 um in y direction with 500 girds. Firstly, I calculated the QED radiation in the self-generated field when propagating in vacuum. With 20 and 8 particles per cell for electron and photon respectively. And I used 10 nodes ( with 96 cores for each node and 4G memory for each node ). When calculation, the node memory reaches its upper limit. How will it cost memory when using QED block? How can I reduce unnecessary memmory usage when using the QED block?
Any suggestion will be helpful! Thanks a lot!

**Comment by Status-Mirror** [comment]
Hi @TrumeAAA 

The QED model in EPOCH uses look-up tables to determine photon emission cross sections. These tables are characterised by QED parameters which don't span the full QED parameter space. Specifically, tables look up $\eta^2$,

$\eta^2 = \frac{1}{E_s^2} \left( \left| \gamma \pmb{E} + \frac{1}{m_e c} (\pmb{p} \times c\pmb{B})\right|^2 - \frac{1}{(m_e c)^2}(\pmb{E}\cdot\pmb{p})^2 \right)$

And have values for $10^{-5} < \eta < 10$. The warning was likely triggered for a small $\eta$, but this is unimportant as low $\eta$ particles don't radiate strongly. Hence, I would not worry about these warnings - they are just reminders of the limitations of the look-up tables.

Secondly, you cannot specify `n_part_per_cell` for the photon species. This key is used to assign macro-particles when you give the species a density, but initially there are no photons in the system, so this key does nothing. The QED routines can generate many macro-photons, and this is what is causing your memory issues.

To limit memory run-away, consider using the key `photon_energy_min` in the [qed block](https://epochpic.github.io/documentation/input_deck/input_deck_qed.html). Most of the photons you create will be low energy - we don't need to add these to the simulation window as they don't do anything. EPOCH would still calculate electron recoil from lower energy photons, but the photons themselves wouldn't take up memory as EPOCH wouldn't track them.

Hope this helps,
Stuart

**Comment by TrumeAAA** [comment]
I understand that, Thanks a lot!
