### ISSUE TITLE
output the electric field data that only generated by laser

### ISSUE THREAD

**Issue by HLQzZ** [Warwick-Plasma/epoch#448]
Dear developer!
How can I output the electric field data that only generated by laser without electrons and ions.
Thanks!

**Comment by TomGoffrey** [comment]
This isn't possible. EPOCH solve's Maxwell's equations (+ Lorentz force on the particles) for the entire system. There's no separate "laser field" or "particle field".

Similar questions have been asked before. See, for example #416
