### ISSUE TITLE
Re-positioning the laser pulse origin closer to the corner when propagating at an angle 

### ISSUE THREAD

**Issue by HollyHuddle** [Warwick-Plasma/epoch#451]
Hi there,

I'm trying to inject a gaussian laser pulse in 2D from a position other than 0 on the boundary it is defined. How would I correctly shift the pulse closer to the corner of the box? I am doing this for both the x_min and y_min boundary. Thanks

**Comment by TomGoffrey** [comment]
What does your input deck for the case where the laser is positioned at 0 look like? It should be straightforward to move it. Do you still want the laser propagating parallel to the boundaries?

**Comment by HollyHuddle** [comment]
I'm propagating 45 degrees to the boundary. 

begin:constant 

#runtime
runtime = 100 * femto

#length of grid in each dimension
xlength  = 18 * micron
ylength  = 18 * micron 

#resolution 
cells_per_x = 40 / micron
cells_per_y = 40 / micron

#minimum positions of domain
grid_x_min = -9 * micron
grid_y_min = -9 * micron

#laser wavelength (same for both x and y)
las_lambda = 0.8 * micron 

#angle of incidence
las_angle = 45 * (pi / 180) 

#peak normalised vector potential 
las_a0 = 10

#polarisation angles
las_polanglex = 0 
  
#laser transverse spotsize 
las_fwhm = 4 * micron

#pulse duration 
las_fwhmt = 7 * femto


#Laser Peak Intensity 
las_intensity_peak = las_a0 ^ 2 * 1.368167127e6 / las_lambda ^ 2

#CONVERSIONS TO LASER CO-ORDINATES#
#X_MIN LASER 
#axial direction
z_lasx = x
#radial direction
r_lasx = sqrt(y^2+z^2)

#conversions to e/e^2 radii

#pulse duration
las_widtht = 0.849322 * las_fwhmt

#fwhm 
las_width  = 0.849322 * las_fwhm 

#rayleigh range 
las_rayleigh = pi * (las_width ^2) / las_lambda

#wavenumber 
las_k  (2.0 * pi ) / las_lambda

#xmin laser 
las_wx = las_width * sqrt( 1+ (z_lasx / las_rayleigh)^2)
end:constant 

begin:control 
t_end = runtime 
particle_tstart = 0 * femto 

nx = xlength * cells_per_x
ny = ylength * cells_per_y


x_min = grid_x_min
x_max = x_min + xlength 
y_min = grid_y_min
y_max = y_min+ ylength 
 
stdout_frequency = 50
end:control 

begin:boundaries 
bc_x_min = simple_laser
bc_x_max = simple_outflow 
bc_y_min = simple_outflow
bc_y_max = simple_outflow 
end:boundaries 

begin:laser
boundary = x_min
lambda= las_lambda * cos(las_angle) 
intensity_w_cm2 = (las_width / las_wx)^(ndims-1) * las_intensity_peak
phase = - (( 2 * pi * y) / las_lambda )* sin(las_angle)
profile = gauss( r_lasx , 0, las_wx)
end:laser 


begin:output
dump_first=T
  
  dump_last=T
  
  dt_snapshot = 10 * femto
 
  grid = always
  
  ex = always
  ey = always
  ez = always
 
  bx = always
  by = always
  bz = always 
end:output

**Comment by TomGoffrey** [comment]
The following (based on your now deleted (?) input deck appears to work:

```
begin:constant

#runtime
runtime = 100 * femto

#length of grid in each dimension
xlength = 18 * micron
ylength = 18 * micron

#resolution
cells_per_x = 40 / micron
cells_per_y = 40 / micron

#minimum positions of domain
grid_x_min = -9 * micron
grid_y_min = -9 * micron

#laser wavelength (same for both x and y)
las_lambda = 0.8 * micron

#angle of incidence
las_angle = 45 * (pi / 180)

#peak normalised vector potential
las_a0 = 10

#polarisation angles
las_polanglex = 0

#laser transverse spotsize
las_fwhm = 4 * micron

#pulse duration
las_fwhmt = 7 * femto

#Laser Peak Intensity
las_intensity_peak = las_a0 ^ 2 * 1.368167127e6 / las_lambda ^ 2

#CONVERSIONS TO LASER CO-ORDINATES#
#X_MIN LASER
#axial direction
z_lasx = x
# Laser y position
laser_y_pos = -8 * micron
#radial direction
r_lasx = sqrt((y - laser_y_pos)^2+z^2)

#conversions to e/e^2 radii

#pulse duration
las_widtht = 0.849322 * las_fwhmt

#fwhm
las_width = 0.849322 * las_fwhm

#rayleigh range
las_rayleigh = pi * (las_width ^2) / las_lambda

#wavenumber
las_k (2.0 * pi ) / las_lambda

#xmin laser
las_wx = las_width * sqrt( 1+ (z_lasx / las_rayleigh)^2)
end:constant

begin:control
t_end = runtime
particle_tstart = 0 * femto

nx = xlength * cells_per_x
ny = ylength * cells_per_y

x_min = grid_x_min
x_max = x_min + xlength
y_min = grid_y_min
y_max = y_min+ ylength

stdout_frequency = 50
end:control

begin:boundaries
bc_x_min = simple_laser
bc_x_max = simple_outflow
bc_y_min = simple_outflow
bc_y_max = simple_outflow
end:boundaries

begin:laser
boundary = x_min
lambda= las_lambda * cos(las_angle)
intensity_w_cm2 = (las_width / las_wx)^(ndims-1) * las_intensity_peak
phase = - (( 2 * pi * y) / las_lambda )* sin(las_angle)
profile = gauss( r_lasx , 0, las_wx)
end:laser

begin:output
dump_first=T

dump_last=T

dt_snapshot = 10 * femto

grid = always

ex = always
ey = always
ez = always

bx = always
by = always
bz = always
end:output
```

I've not quite positioned the laser exactly in the corner, but I'm sure you can see how to adjust it

**Comment by HollyHuddle** [comment]
Yes apologies I had meant to upload a more up to date version then forgot! This is exactly what I was missing thank you very much for your help!

**Comment by DanRRRR** [comment]
Thanks, i also planned to ask that. 
Now comes this tricky question:  and how the example above and more complex ones with focusing (cited above from 2014) will look for s- and p-polarizations ?

**Comment by DanRRRR** [comment]
I tried the code above and do not see the laser is at angle. It goes strictly vertically, isn't it?
