### ISSUE TITLE
effect of both circular polarization and incidence angle

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#472]
Hello,
I want to see the effect of both circular polarization and incidence angle, for this I'm attaching you my input file to know if I'm right or I should add another parameters.

Another point please, does the laser-target distance have an influence in ion acceleration ?
Thank you in advance.

[input.txt](https://github.com/Warwick-Plasma/epoch/files/11062397/input.txt)

**Comment by Status-Mirror** [comment]
Hi @mimboch

From a quick glace it seems like this will work - but its better to test it first. You can check the Ex, Ey and Ez outputs in a vacuum simulation to see if this has worked.

Physically, the laser-target distance has no effect. In EPOCH, a tightly focused laser may de-focus before reaching the target, so this would affect the laser-solid interaction. Again, I recommend you look at the laser in a vacuum before running a laser-target simulation.

Hope this helps,
Stuart
