### ISSUE TITLE
Unable to find the ionisation_energies.table

### ISSUE THREAD

**Issue by ljt0640p** [Warwick-Plasma/epoch#475]
Hi All,

When I tried to set up a 2D simulation including ionisation process.
The execution reports the error:
`*** ERROR ***
 Unable to find the file:
 src/physics_packages/TABLES/ionisation_energies.table`

However, I'm quite sure the table exists in the path. 
I tried to re-make the code and use different versions of the EPOCH code (4.18.0 or 4.19.1), but the error remains.
Ps. The 2D simulation without ionisation works quite well.
From the manual, the ionisation energy is now forced to be read from the look-up table. So it seems to me, I can't manually enter the binding energy.
Is there any suggestions on this? 

Thanks,
YK

**Comment by Status-Mirror** [comment]
Hey YK,

For 2D EPOCH, we advise you to run the code from the `epoch2d` directory, such that you run it using the command:

```perl
mpirun -np 4 ./bin/epoch2d
```

When you run epoch2d, it has paths relative to this directory. If you can't run from this directory, then you need to tell the code where the library files are. This is achieved by adding a command like:

```
physics_table_location = "/absolute/path/to/epoch/epoch2d/src/physics_packages/TABLES"
```

to your control block.

I've just realised that this key is undocumented, so I will keep this issue open until I add it to the website.

Hope this helps,
Stuart

**Comment by ljt0640p** [comment]
Hi Stuart,

I tried to add the absolute path into the control block and it works!
Really appreciate your help.

BTW, about the documentation, in the section of ionisation, some example code about the control block is shown:
`...
use_multi_photon = T
...`
However, with EPOCH v4.19.1 (the latest release code). 
The execution (epoch2d) complains about this line with a warning message:
` Unrecognised element "use_multi_photon" in input deck.`.

If I use the flag from the old version manual: `use_multiphoton = T`, then there is no complaint. Not sure this is a typo or some other concern.

Best,
YK

**Comment by Status-Mirror** [comment]
I see it - we have incorrectly used `use_multi_photon` in the ionisation example deck in the ionisation section of: https://epochpic.github.io/documentation/input_deck/input_deck_species.html

I will also correct this when I'm back in the office.

Good spot!
Stuart

**Comment by ljt0640p** [comment]
Thank you for the kind help : )

Best,
YK
