### ISSUE TITLE
Unexpected write_field behaviour when extending diagnostics.F90

### ISSUE THREAD

**Issue by Status-Mirror** [Warwick-Plasma/epoch#481]
I'm working on an EPOCH extension which requires new field diagnostics. I'm experiencing issues writing data in the SDF format when one diagnostic needs to write several arrays. I'll provide a simplified example to demonstrate my problem:

Suppose I wanted to change the `Ex` diagnostic in epoch2d, so it writes 3 copies of the `ex` array to the SDF file. I could go to `diagnostics.F90`, find the line:

```
      CALL write_field(c_dump_ex, code, 'ex', 'Electric Field/Ex', 'V/m', &
          c_stagger_ex, ex)
```

and I could replace it with:

```
      CALL write_field(c_dump_ex, code, 'ex1', 'Electric Field/Ex/copy1', 'V/m', &
          c_stagger_ex, ex)
      CALL write_field(c_dump_ex, code, 'ex2', 'Electric Field/Ex/copy2', 'V/m', &
          c_stagger_ex, ex)
      CALL write_field(c_dump_ex, code, 'ex3', 'Electric Field/Ex/copy3', 'V/m', &
          c_stagger_ex, ex)
```

After compiling the new code, we can test it using the input deck:

```
begin:control
    nx = 20
    ny = 20
    t_end = 1.0e-15
    x_min = 0
    x_max = 20.0e-6
    y_min = 0
    y_max = 20.0e-6
end:control

begin:boundaries
    bc_x_min = open
    bc_x_max = open
    bc_y_min = open
    bc_y_max = open
end:boundaries

begin:fields
    ex = 1.0
end:fields

begin:output
    dt_snapshot = t_end
    ex = always
end:output
```

This sets up a small grid, with ex = 1.0 in each cell. We expect the `ex = always` flag to generate 3 arrays in the SDF file, with block names: `Electric_Field/Ex/copy1`, `Electric_Field/Ex/copy2` and `Electric_Field/Ex/copy3`, and this is what we find.

When we run the code in serial, we successfully write all 3 copies. When running on 4 cores, the copies are written but the output is wrong. I have attached two figures demonstrating the `Electric_Field/Ex/copy1` output for `0000.sdf`.

![copy1_comparison](https://user-images.githubusercontent.com/38282483/231550627-24ba2e8e-5864-4aed-b7c0-560153a6d595.png)

We can verify that the fields are correct inside EPOCH by adding the line: `IF (STEP == 0) print*, rank, ex(1:nx,1:ny)` just before the `write_field` calls - this is an issue with the SDF writer.

Have I made an obvious mistake here, or is there a smarter way to output these new arrays instead of going through `write_field`? Happy for any SDF developers to shed some light onto this problem.

Cheers,
Stuart

**Comment by Status-Mirror** [comment]
I was not able to solve the problem, but I have found a work-around for cases relevant to me.

Instead of printing multiple copies of the same 2D array, we can print a single 3D array. In the simplest implementation, this was achieved by replacing the `write_field` lines with:

```
CALL sdf_write_plain_variable(sdf_handle, 'ex', 'Electric Field/Ex', 'V/m', &
     (/nx_global, ny_global, 3/), c_stagger_ex, & 
    'copy_grid', ex_copy, subtype_field, subarray_copy, .FALSE.)
```

Some of the arguments of this function require further explanation.
- `(/nx_global, ny_global, 3/)`: dimensions of the 3D array to print
- `'copy_grid'`: name of the grid associated with the 3D array (not used in my example)
- `ex_copy`: the 3D array
- `subtype_field`: the MPI data-type of the variable to print
- `subarray_copy`: an MPI subarray integer which contains information about which local indices to output

For `(/nx_global, ny_global, 3/)`, we have specified the number of array elements in each direction. The final element is `3`, as we want 3 copies of `Ex` in this example.

The array `ex_copy` is created by adding the lines:
```
      ALLOCATE(ex_copy(1-ng:nx+ng,1-ng:ny+ng,3))
      ex_copy(:,:,1) = ex
      ex_copy(:,:,2) = ex
      ex_copy(:,:,3) = ex
```
before the `sdf_write_plain_variable` call, and adding `DEALLOCATE(ex_copy)` after. The array is defined at the start of the `output_routines` subroutine, with the line: ` REAL(num), ALLOCATABLE :: ex_copy(:,:,:)`.

Here, `subtype_field` is a `shared_data` integer, and is set to `MPI_DOUBLE_PRECISION` in the `create_current_field_subarray` function of `housekeeping/mpi_subtype_control.f90`.

Finally, `subarray_copy` was added as an extension to the `mpi_subtype_control` module. Firstly, the subarray is defined in `shared_data.F90` with:
```
  INTEGER :: subarray_copy
```
Next, the integer is assigned a value by adding this line to the `create_subtypes` subroutine:
```
    subarray_copy = create_field_subarray(mpireal, ng, nx, ny, 3)
```
where `nx`, `ny` and `3` are the sizes of the output array. Then all that remains is to tell the code that there are no "ghost cells" in the "`z`" direction, which can be achieved by adding the lines:
```
    IF (PRESENT(n3)) THEN 
      start(3) = 1
      n_global(3) = 3
    END IF
```
just before the lines which call the `create_{n}d_array_subtype` in the `create_field_subarray` function. This makes the SDF file output 1:3 in the final array indices, which refers to our 3 copies of the data.
 
When running the code with this extension, we get my desired behaviour.

**Comment by DanRRRR** [comment]
I have even more strange related to the fields problem exactly in this routine too.

Let's just add the following PRINT*  line to this subroutine before or after these lines  (line around 436)

<      ! open the file
      CALL sdf_open(sdf_handle, full_filename, comm, c_sdf_write)>

The line is telling what indices  of 3D e-field array each core is dealing with 
`print*, 'cell_x_min(rank+1),cell_x_max(rank+1), cell_y_min(rank+1),cell_y_max(rank+1), cell_z_min(rank+1),cell_z_max(rank+1)=', & 
         cell_x_min(rank+1),cell_x_max(rank+1), cell_y_min(rank+1),cell_y_max(rank+1), cell_z_min(rank+1),cell_z_max(rank+1)
`
and let's run the standard 3D demo deck called cone.deck from epoch3d samples.
With 1 core we get of course the entire array 1 250 1 250 1 250 and all looks fine.

Now let's run with  2 cores. Naturally exapect that the entire domain will be divided by two equal parts. And what we get is 
```cell_x_min(rank+1),cell_x_max(rank+1), cell_y_min(rank+1),cell_y_max(rank+1), cell_z_min(rank+1),cell_z_max(rank+1)=           1         250           1         250           1         125```
for first core which is exactly what we expected. What we get for another core though will shock you
``` cell_x_min(rank+1),cell_x_max(rank+1), cell_y_min(rank+1),cell_y_max(rank+1), cell_z_min(rank+1),cell_z_max(rank+1)=       22050           5       32739       32739         126         250```

**Comment by Status-Mirror** [comment]
Hey Dan,

I did see this comment, but you were right to open a separate issue as this is a little different to my original problem. I get email alerts whenever someone comments on an issue or discussion I have contributed to. I think the other developers have a similar setup.

Cheers,
Stuart
