### ISSUE TITLE
How do I convert SDF data file to ASCII data file?

### ISSUE THREAD

**Issue by MKR100** [Warwick-Plasma/epoch#491]
Hi, Could you please let me, is it possible to convert SDF data file to ASCII data file for field and particle? If yes, please let me in detail, how can I do that. Thanks

**Comment by Status-Mirror** [comment]
Hi @MKR100 

There are no ways to quickly convert an SDF file into an equivalent ASCII file, but we offer [several SDF readers](https://github.com/Warwick-Plasma/SDF) in different languages.

As quite a few users are familiar with Python, we offer [detailed documentation](https://epochpic.github.io/documentation/visualising_output/python.html) on how to read SDF files using this language. I personally use MATLAB, as I find the "GetDataSDF" function quite straightforward to use.

Alternatively, documentation on how an SDF file is organised can be found in the tex file [here](https://github.com/Warwick-Plasma/SDF_documentation/tree/a46893c53497fa6e9a3e92f94b22e98644b51d82). Using the information in this document, you should be able to create your own converter in whichever language you choose.

I'm going to close the issue as I've answered the main question, but if you need any further support on a particular method, feel free to continue messaging in this chain.

Cheers,
Stuart
