### ISSUE TITLE
Something strange with simple laser propagation

### ISSUE THREAD

**Issue by Misery7100** [Warwick-Plasma/epoch#494]
Hello developers

I faced strange issue when running very simple input on HPC cluster using EPOCH 3D. I tried to tweak it many ways, but nothing helps so now I think it might be related to computation infrastructure. Basically there is input:

```julia
begin:control

    nx = 200
    ny = 200
    nz = 200

    t_end = 10.0 * femto

    x_min = -2.5 * micron
    x_max = 2.5 * micron
    y_min = -2.5 * micron
    y_max = 2.5 * micron
    z_min = -2.5 * micron
    z_max = 2.5 * micron

    stdout_frequency = 20
  
end:control

begin:boundaries

    # particle boundary settings

    bc_x_min_particle = reflect
    bc_x_max_particle = simple_outflow

    bc_y_min_particle = simple_outflow
    bc_y_max_particle = simple_outflow

    bc_z_min_particle = simple_outflow
    bc_z_max_particle = simple_outflow

    # field boundary settings

    bc_x_min_field = simple_laser
    bc_x_max_field = open

    bc_y_min_field = open
    bc_y_max_field = open

    bc_z_min_field = open
    bc_z_max_field = open
  
end:boundaries

begin:laser

    boundary = x_min

    id = 1
    intensity_w_cm2 = 1.0e22
    lambda = 1.064 * micron

    t_profile = gauss(time, 10.0 * femto, 10.0 * femto)
    t_end = 20.0 * femto

end:laser

begin:output

    dt_snapshot = 2.5 * femto
    
    name = standard

    grid = always
    ex = always
    bx = always
    by = always
    bz = always

end:output
```

I expect to get linearly polarized gauss pulse propagating, but I obtain following for longitudinal magnetic field (which is quite strange for me) 

![image](https://github.com/Warwick-Plasma/epoch/assets/68801526/bbc454ee-f455-4b87-bdf7-acfb43a739b6)

And following for normal component

![image](https://github.com/Warwick-Plasma/epoch/assets/68801526/0ecff569-43d8-42aa-92da-e5d846c19e4a)

Is there a way to explain it or fix? I'm able to remove that only using v4.15.2 with cpml boundary conditions, but it works only under 400x400x400 grid (for me) and with some specific cpml thickness. I also tried to fix that by adding gauss spatial profile, but then it becomes like that:

![image](https://github.com/Warwick-Plasma/epoch/assets/68801526/4eded68d-9392-4e54-83f7-5e38114f90af)
![image](https://github.com/Warwick-Plasma/epoch/assets/68801526/ac9decdf-a31e-408e-ae1a-8ba26600d3bd)

It seems to be right according to https://github.com/Warwick-Plasma/epoch/issues/142, but what's wrong with simple plane wave then :/

code version is v4.19.1-8-g6b027ed-dirty

**Comment by Misery7100** [comment]
Small upd: checked it on local computer, the same behavior, so seems like it's not computation infra related

**Comment by Status-Mirror** [comment]
Hey @Misery7100 

Your Gaussian pulses look sensible, but I agree that you're seeing numerical artefacts on the boundaries of the plane wave. The `simple_outflow` boundary conditions in EPOCH are based on theory which assumes the laser is propagating normal to the boundaries. For your plane wave, this is satisfied on `x_min` and `x_max`, but this is not true on `y_min`, `y_max`, `z_min`, `z_max`. You don't see this in the Gaussian pulse as the laser has decayed away by this boundary.

Despite this, the EPOCH boundaries usually do a good job at outflowing generic waves, but I think yours may be an extreme case. I'd be interested to see if you still observe weird behaviour if you set `t_profile` to 0.

Cheers,
Stuart

**Comment by Misery7100** [comment]
> Hey @Misery7100
> 
> Your Gaussian pulses look sensible, but I agree that you're seeing numerical artefacts on the boundaries of the plane wave. The `simple_outflow` boundary conditions in EPOCH are based on theory which assumes the laser is propagating normal to the boundaries. For your plane wave, this is satisfied on `x_min` and `x_max`, but this is not true on `y_min`, `y_max`, `z_min`, `z_max`. You don't see this in the Gaussian pulse as the laser has decayed away by this boundary.
> 
> Despite this, the EPOCH boundaries usually do a good job at outflowing generic waves, but I think yours may be an extreme case. I'd be interested to see if you still observe weird behaviour if you set `t_profile` to 0.
> 
> Cheers, Stuart

Hey @Status-Mirror 

FYI I see no problems with `t_profile = 0`. Many thanks for the clarification :)

Best,
Lev
