### ISSUE TITLE
Time signal about E/B

### ISSUE THREAD

**Issue by USTCxiaoxixi** [Warwick-Plasma/epoch#496]
Dear developer,
i want to know if epoch can set the time series for a certain point, thus, i can know this point's Ex in different time. I want to collect electric field signals on a semicircle at different time.

**Comment by Status-Mirror** [comment]
Hey @USTCxiaoxixi

The easiest way to achieve this would be to use a separate [output block](https://epochpic.github.io/documentation/input_deck/input_deck_output_block.html) which only outputs the fields. You could choose to dump the whole grid of Ex as frequently as you like.

If you're only inteterested in a semi-circle of cells, then dumping all the field points may produce files which are far larger than you need. You can reduce the number of cells to dump using [subsets](https://epochpic.github.io/documentation/input_deck/input_deck_subset.html) (specifically the "Subsets of fields" section).

With subsets, you can choose to only output cells between an `x_min` and `x_max` limit (and you can set limits in higher dimensions if your simulation supports them). Using this, it would be very easy to isolate a single cell, or a line/rectangle/cuboid of cells. A semi-circle would be a little more challenging, but it may still be possible to construct a reduced grid.

If you have an input deck, I can probably give more detailed advice.

Cheers,
Stuart

**Comment by Status-Mirror** [comment]
I'm going to mark this as done for now, but if you have any other issues feel free to continue posting here!
