### ISSUE TITLE
Simulations frozen at onset

### ISSUE THREAD

**Issue by bzdjordje** [Warwick-Plasma/epoch#497]
I have recently been having issues where by simulations seem to freeze after the particles load but do not crash out, meaning the compute cycles are still being burned even though nothing is happening. It seems arbitrary, in that only simple variations are being made, e.g., foil thickness and laser intensity, but in some cases the simulation runs and in others it is frozen. This has been happening with versions 4.18 and 4.19. Our primary cluster Quartz recently underwent an upgrade from OS system TOSS 3 to TOSS 4, and so old compiled executables no longer work. Because of the upgrade it may not be Epoch that is the issue, but I am not sure how to debug this, is there a routine to see what the simulation is hanging up on?

**Comment by bzdjordje** [comment]
It seems to have something to do with either PROBE_TIME or PARTICLE_ID. A few test simulations seem are now running with those options removed from the compilation. However, some other simulations are now running into "forrtl: severe (174): SIGSEGV, segmentation fault occurred" regardless of how many nodes are used.

**Comment by Status-Mirror** [comment]
If you take an input deck which has froze, and attempt to re-run it, does it freeze again?

If the same input deck sometimes runs and sometimes fails, then this sounds like an issue with Quartz. I'd try running:

```
make cleanall
```

and then recompiling EPOCH.

If you can get a single input deck to reliably crash, can you send it here?

Cheers,
Stuart

**Comment by bzdjordje** [comment]
Hi Stuart, 
Thank you for your response. Unfortunately I am still running into the same issue, though sometimes EPOCH freezes at the first step and sometimes it freezes once particles start moving. I am seeing this for both collisional and collisionless plasmas, 1D and 2D. Attached is an example run.
[epoch_freeze.zip](https://github.com/Warwick-Plasma/epoch/files/11559220/epoch_freeze.zip)


Cheers,
Blagoje
@Status-Mirror

**Comment by Status-Mirror** [comment]
I'm going to mark this as done for now, as I'm not sure there's much more support we can give you on this. If the Quartz team comes back and tells us we're doing something wrong, then feel free to let us know.

**Comment by bzdjordje** [comment]
We found that with machines running mvapich2 the following flag seemed to help with hanged simulations:

setenv MV2_USE_SHMEM_COLL 0
