### ISSUE TITLE
how to make a solid sphere plasma density profile

### ISSUE THREAD

**Issue by MKR100** [Warwick-Plasma/epoch#498]
Hello,

How to make a plasma (means rather than filling the particles in a rectangular box), fill them in a solid sphere (in 3D) and circle (in 2D)?

Thanks

**Comment by Status-Mirror** [comment]
Hey @MKR100 

EPOCH allows the use of maths expressions when specifying grid-based quantities like the density. An introduction to this is given [here](https://epochpic.github.io/documentation/code_details/maths_parser.html).

Using this, I have created a 2D input deck where I have defined a variable `circ_r`, and I have initialised a plasma only where `circ_r` is less than a user defined circle radius. Below I show the created density profile, and the input deck I used to run this simulation.

![loaded_circle](https://github.com/Warwick-Plasma/epoch/assets/38282483/b51d0279-f729-4ae2-9234-1ff6710d6459)

```
begin:control
  nx = 100
  ny = 100
  t_end = 1.0e-15
  x_min = 0 * micron
  x_max = 20 * micron
  y_min = -10 * micron
  y_max = 10 * micron
end:control

begin:boundaries
  bc_x_min = simple_outflow
  bc_x_max = simple_outflow
  bc_y_min = simple_outflow
  bc_y_max = simple_outflow
end:boundaries

begin:constant
  circle_centre_x = 8.0e-6
  circle_centre_y = 0.0e-6
  circle_radius = 3.0e-6
  circ_r = sqrt((x - circle_centre_x)^2 + (y - circle_centre_y)^2)
  electron_number_density = 1.0e20
end:constant

begin:species
  name = proton
  charge = +1.0
  mass = 1836.2
  density = if(circ_r lt circle_radius, electron_number_density, 0.0)
  npart_per_cell = 100
end:species

begin:species
  name = electron
  charge = -1.0
  mass = 1.0
  density = if(circ_r lt circle_radius, electron_number_density, 0.0)
  npart_per_cell = 100
end:species

begin:output
  dt_snapshot = t_end
  grid = always
  number_density = always + species
end:output
```

**Comment by MKR100** [comment]
Hello, @Status-Mirror 

Thanks a lot.

**Comment by amarsarari** [comment]
Sir Can U please share Matlab script to see above electron denisty.

**Comment by Status-Mirror** [comment]
Sure thing. The MATLAB script requires the use of scripts found in the EPOCH folder `epoch/SDF/Matlab`. You'll need to copy and paste these scripts into your working directory first (or add the folder to the path). The main one of interest to us here is `GetDataSDF.m`, but this calls the other scripts so copy them all.

Once MATLAB can see these functions, run this script:

```matlab
% Read data
file_name = '0000.sdf';
data = GetDataSDF(file_name);

% Extract cell edges and reformat for surf function
x_edges = data.Derived.Number_Density.grid.x;
y_edges = data.Derived.Number_Density.grid.y;
x_centres = 0.5*(x_edges(2:end) + x_edges(1:end-1));
y_centres = 0.5*(y_edges(2:end) + y_edges(1:end-1));
[x_plot, y_plot] = meshgrid(x_centres, y_centres);

% Create plot
num_dens = data.Derived.Number_Density.electron.data;
surf(x_plot*1.0e6, y_plot*1.0e6, num_dens', 'EdgeColor', 'none');

% Format plot
ax = gca;
ax.FontSize = 16;
xlabel('x [\mum]');
ylabel('y [\mum]');
cbar = colorbar;
cbar.Label.String = 'Number density [1/m³]';
view(2);
```
