### ISSUE TITLE
Electron injection

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#50]
In GitLab by Andrei Berceanu on 14 Nov 2018, 20:07 UTC (GitLab issue GL#1868)

Is there a way to do a double-stage acceleration in EPOCH, with LWFA in the first stage an PWFA in the second, by extracting electrons that are accelerated in the LWFA stage and injecting them into the PWFA stage?

Example: https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.120.254802

**Comment by Status-Mirror** [comment]
This is now possible as of EPOCH 4.19, with enhanced particle probes to extract electrons from one simulation, and an inject-from-file features to insert them into a second simulation.
