### ISSUE TITLE
laser focus

### ISSUE THREAD

**Issue by USTCxiaoxixi** [Warwick-Plasma/epoch#501]
As you know. In experiments, we often focus the laser through a lens and then reuse it, but during the simulation, do I need to set the parameters of focusing, or I can directly set the simulated laser intensity as the focused laser intensity. Besides, i want to know if i set a slat target in epoch2D, doser the length of  z_direct  Infinite?

**Comment by Status-Mirror** [comment]
Hey @USTCxiaoxixi 

In EPOCH, you describe lasers by defining the intensity (with spatial and temporal profiles) on a simulation boundary. By following the [Gaussian beam example](https://epochpic.github.io/documentation/examples/basic_examples.html), you are able to inject a laser which focuses to a specific size and point.

In EPOCH2D, the cell-size in the $z$ direction is taken to be 1m when calculating macro-particle weights. In a 2D code, this size is arbitrary, as we assume no gradients in the $z$ direction.

Hope this helps,
Stuart

**Comment by USTCxiaoxixi** [comment]
thank you, and i have a question, In a 2D simulation, I set a rectangular area, but is it actually an infinitely long cuboid or a rectangular sheet?

**Comment by Status-Mirror** [comment]
As an example, if your rectangular area goes from $x=0$ to $x=5 \mu m$, and from $y=-2.5 \mu m$ to $y=2.5 \mu m$, then macro-particles will be given weights as if the square represents a cuboid volume of $5 \mu m \times 5 \mu m \times 1 m = 2.5\times 10^{-11} m^{-3}$.

You may think this 1m is arbitrary, but this only affects particle numbers. The EPOCH field solver depends on current densities, which have no dependence on the size of the omitted dimension. The physics would be the same if we chose a $1\mu m$ size in $z$, only the weights of macro-particles would be reduced by a factor of $10^{-6} $.

**Comment by USTCxiaoxixi** [comment]
Thank you, and i have anonther question.  I want to knnow how to add a ring magnetic field to a rectangular area in a 2D simulation? if my rectangular area goes from x=0 to x= 5um, and from y =-2.5um to y =2.5um,

**Comment by Status-Mirror** [comment]
I'm not sure what you mean by "ring magnetic field". However, you can initialise fields using the EPOCH [fields block](https://epochpic.github.io/documentation/input_deck/input_deck_fields.html).

**Comment by Status-Mirror** [comment]
I'm going to mark this issue as closed for now, but if you have any further comments feel free to leave them here.
