### ISSUE TITLE
How is the distribution function output from EPOCH normalised? 

### ISSUE THREAD

**Issue by nikichats** [Warwick-Plasma/epoch#509]
Hi!

I’m running simulations in EPOCH 1D, and I have a distribution function block like this: 

``` 

begin:control 

  # Global number of gridpoints 

  nx = 500 

 

  # Global number of particles 

  nparticles = 100 * nx 

 

  # Final time of simulation 

  t_end = 1.0e-9 

  nsteps = -1 

 

  # Size of domain 

  x_min = 0.0e-6 

  x_max = 100.0e-6 

end:control 

 

begin:dist_fn 

  name = electron_x_px 

  ndims = 2 

 

  direction1 = dir_x 

  direction2 = dir_px 

 

  range1 = (1, 1) 

  range2 = (1, 1) 

 

  resolution1 = 1 

  resolution2 = 200 

  include_species:Electron 

end:dist_fn 

``` 

I’m trying to understand how the distribution function differs from a Maxwellian, but I cannot work out the normalisation of the distribution function. The documentation says that it is normalised so that the value at every point of the distribution function is the number of particles within that cell. If I take a particular value of `x` and integrate over the `dir_px` direction, I would then expect to get the number of particles in that cell. However, I find that this is really different to the number density in that cell. How is the derived number density related to the distribution function output?

**Comment by Status-Mirror** [comment]
Hi @nikichats 

In epoch1d and epoch2d, our domain is composed of either a 1d or 2d grid - but these cells are supposed to represent 3d space. The EPOCH field solver only cares about current _density_, not the absolute charge in a cell - so the size of these cells in the omitted dimensions are arbitrarily set to 1m. Hence, when you give epoch1d a species density, the weights of the macro-particles are set assuming each cell has a volume of $(dx \times 1m \times 1m)$. In your case, the cell volume is $2.0\times 10^{-7} m^{3}$.

The distribution function gives the number of real particles in the cell. If you sum all the `dir_px` values for a given $x$, then I would expect this to equal the cell number density multiplied by $2.0\times 10^{-7}$. Is this what you observe?

Cheers,
Stuart

**Comment by nikichats** [comment]
Hi @Status-Mirror,

Thanks for your reply! I assumed this was the case. I’m finding that the number density calculated by summing all the dir_px values for a given x is actually the cell number density multiplied by a factor ~1/34. If I do the same thing for the ions, I find that it’s different a factor ~1/1400. I’ve set the mass of the electron species to 1.0 and the mass of the ion species to 1836.0, so this does seem a bit strange?

I am using the PER_SPECIES_WEIGHT compile flag, could it be that the distribution function doesn’t work with this?

**Comment by Status-Mirror** [comment]
That does seem unusual. Could you send me your full input deck and I can have a look myself?

Cheers,
Stuart

**Comment by nikichats** [comment]
Dear @Status-Mirror,

I’ve worked out this now! It was actually the combination of two things. I was using an old version of the input deck where my electrons were more massive than I thought they were, and I was also including the factor of dp when I was summing up the distribution function. Somehow these offset each other to give a weird factor of difference when I integrated.

Thanks for your help!

**Comment by Status-Mirror** [comment]
No problem - good job solving it!
