### ISSUE TITLE
SDF fails to compile with Intel compiler and HPE MPT

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#51]
In GitLab by Alexander Seaton on 03 Dec 2018, 14:28 UTC (GitLab issue GL#1882)

This is not so much a bug in EPOCH as a bug in the MPT MPI library as far as I can see, but in case this is an issue for others I am posting it here. This occurs on Cirrus with HPE MPT 2.16 and the Intel 2017 compiler, which is currently the recommended combination.

The functions MPI_File_get_errhandler and MPI_File_set_errhandler in the MPI library seem to be defined with the file handle as an INTENT(INOUT) variable rather than INTENT(IN). This causes compilation to fail when a constant is passed in:

```
mpif90 -c -O3 -g -fpe0 -mcmodel=medium -heap-arrays 64 -I/usr/include -Iinclude -Iobj -module include -o obj/sdf_common.o src/sdf_common.f90
src/sdf_common.f90(740): error GL#6638: An actual argument is an expression or constant; this is not valid since the associated dummy argument has the explicit INTENT(OUT) or INTENT(INOUT) attribute.   [0]
      CALL MPI_FILE_SET_ERRHANDLER(MPI_FILE_NULL, var%errhandler, ierr)
-----------------------------------^
```

This can easily be fixed by going through the SDF code and replacing arguments supplied as MPI_FILE_NULL with a variable set to MPI_FILE_NULL.

**Comment by TomGoffrey** [comment]
I'm closing this as the issue was due to a fault with MPT, not EPOCH. I also note that EPOCH does compile successfully with the currently installed version of MPT on Cirrus.
