### ISSUE TITLE
To apply  static magnetic filed in laser direction

### ISSUE THREAD

**Issue by amarsarari** [Warwick-Plasma/epoch#516]
Hi sir, I want to apply a static magnetic field of magnitude 1500Tesla  in the x direction(direction of laser), Could you please help me?

**Comment by Status-Mirror** [comment]
You can set-up initial fields in EPOCH using the [fields block](https://epochpic.github.io/documentation/input_deck/input_deck_fields.html). Note that this only sets initial fields - EPOCH will update the fields using the field-solver as the simulation progresses.
