### ISSUE TITLE
density defining

### ISSUE THREAD

**Issue by amarsarari** [Warwick-Plasma/epoch#517]
Hi sir
i want 1.0e20 * exp((x - 10.0e-6) / 2.0e-6) from 0 to 10 micron
then 1.0e20 from 10 to 5 micron
then rising from 1.0e20 * exp((15.0e-6-x) / 5.0e-6) from 15 to 25 micron
how I can do plz help me

**Comment by Status-Mirror** [comment]
You would use a species block with a density of the form:

```
begin:species
  name = Electron
  charge = -1
  mass = 1
  frac = 0.5
  density = if( x gt 0,  1.0e20 * exp((x - 10.0e-6) / 2.0e-6), 0.0)
  density = if( x gt 10.0e-6, 1.0e20, density(Electron))
  density = if( x gt 15.0e-6, 1.0e20 * exp((15.0e-6-x) / 5.0e-6), density(Electron))
  density = if( x gt 25.0e-6, 0, densty(Electron))
end:species
```

Here I have created an electron species with the name "Electron", and set the density in stages. The first line sets your first exponential starting at x=0, and sets the density to 0 below x=0. The second line sets a constant density above x=10 micron, but below this it uses the density values we have already set in the lines above. We repeat this pattern for the remaining two lines.

For more information on the functions used in the EPOCH input deck, check out the [maths parser](https://epochpic.github.io/documentation/code_details/maths_parser.html) documentation.

Cheers,
Stuart
