### ISSUE TITLE
Error : Unrecognised "x_min" boundary for species "electron"

### ISSUE THREAD

**Issue by Hnair13** [Warwick-Plasma/epoch#528]
Hello,
I was recently working with Epoch2d for my spherical target problem. While running the code I am getting following error:
![image](https://github.com/Warwick-Plasma/epoch/assets/124340089/397ccec1-e87d-42ec-a7b0-a1875fdba150)
I checked my input deck but doesn't seem to understand where the issue is. I have also attached the input deck in this [message.]
[input deck.txt](https://github.com/Warwick-Plasma/epoch/files/12103033/input.deck.txt)

**Comment by Status-Mirror** [comment]
Hey @Hnair13,

Your input deck is missing a boundaries block, try adding something like this:

```begin:boundaries
   bc_x_min = simple_laser
   bc_x_max = simple_outflow
    bc_y_min = simple_outflow
   bc_y_max = simple_outflow
end:boundaries
```

For more information, see the [boundaries block](https://epochpic.github.io/documentation/input_deck/input_deck_boundaries.html) documentation.

Cheers,
Stuart

**Comment by Hnair13** [comment]
Hello Stuart,
Thank you so much. Just realized that I was using the wrong input deck.

Thanks!
