### ISSUE TITLE
chirped laser pulse

### ISSUE THREAD

**Issue by rashid611** [Warwick-Plasma/epoch#544]
hi. I want to simulate a chirped laser pulse. can someone help me?

**Comment by Status-Mirror** [comment]
Hey @rashid611 

By "chirped laser pulse", do you mean a laser pulse which has a time-varying wavelength?

In the EPOCH input deck, you can include a laser using a [laser block](https://epochpic.github.io/documentation/input_deck/input_deck_laser.html), looking something like this:

```
begin:laser
   boundary = x_min
   intensity_w_cm2 = 1.0e15
   lambda = 1.06 * micron
   profile = 1.0
   t_profile = gauss(time, 40.0e-15, 40.0e-15)
end:laser
```

You can set the wavelength to a single number as done above, or you could write it as a time-dependent function using EPOCH [maths parser](https://epochpic.github.io/documentation/code_details/maths_parser.html) syntax.

For instance, if you wanted the laser wavelength to start at 1.0e-6, and to linearly increase to 2.0e-6 over 100 femtoseconds (remaining fixed at 2.0e-6 after 100fs), you could write:

```
  lambda = 1.0e-6 + if( time lt 100.0e-15, 1.0e-6 * time/100.0e-15, 2.0e-6)
```

Hope this helps,
Stuart

**Comment by rashid611** [comment]
Hi  STUART. 
I hope this will work for me. 
 
THANK YOU

**Comment by rashid611** [comment]
is it possible to simulate the propagation of two, three, or four,  ultrashort laser pulses with different foci? 
For this, what parameter should I change in the laser block?

**Comment by Status-Mirror** [comment]
Apologies for the delay. See the [basic example](https://epochpic.github.io/documentation/examples/basic_examples.html) for a focusing gaussian beam - this tells you how to set up a beam with a specific focal point. For multiple lasers, you can just add more laser blocks to the same simulation.

Hope this helps,
Stuart

**Comment by abigailalexjames** [comment]
Hi @Status-Mirror 

Could I please jump in this chat and ask a follow up question? 

I am trying to implement a chirp pulse, wavelength going from 380 nm to 420 nm over the duration of the pulse which is 167fs. 

I have tried to implement as described above, here is my laser block:

```
begin:laser
boundary = x_min
lambda = lambda_probe + if (time lt 167.0e-15, lambda_probe*time/167.0e-15, 0.42e-6)
intensity_w_cm2 = I_probe*(w0_probe/wx_probe)^2
pol_angle = probe_polangle
profile = gauss(y, 0.0, wx_probe)
t_profile = 1
t_start = 0 * femto
t_end = 167 * femto
end:laser
```
And this is the output I get
![image](https://github.com/Warwick-Plasma/epoch/assets/74933293/755b70a6-4432-4ef5-96a9-6f012eb67afa)

It doesn't look like there is a linear increase and I can't see what I might be doing wrong. Any advice? 

Many thanks,
Abi
