### ISSUE TITLE
sin2 laser

### ISSUE THREAD

**Issue by 2018-2025** [Warwick-Plasma/epoch#555]
Dear sir, i want to create a sin2 laser rather than a  gaussian laser, What should I do?

**Comment by Status-Mirror** [comment]
You can have sinusoidal profiles. Check the discussion in on [this old issue](https://github.com/Warwick-Plasma/epoch/issues/383).

This user asked for a sinusoidal profile, but the method could be adapted for any arbitrary profile.

Cheers,
Stuart
