### ISSUE TITLE
The ionization block does not work in parallel computing

### ISSUE THREAD

**Issue by 2018-2025** [Warwick-Plasma/epoch#556]
Dear sir, i found that the ionization block does not work in parallel computing. The result is below! The first picture is calculate by parallel computing. The second picture is calculate by command line. The have different size.
![image](https://github.com/Warwick-Plasma/epoch/assets/128032365/f3227b76-3581-48e1-bb2a-a3aaac4d7bca)
![image](https://github.com/Warwick-Plasma/epoch/assets/128032365/ef691c59-8051-4027-a4dd-5277ebb36932)

**Comment by Status-Mirror** [comment]
How are you running this - could you send the command lines and the input deck?

Cheers,
Stuart

**Comment by 2018-2025** [comment]
Thank you, Sir. I have solved this question~
