### ISSUE TITLE
Arbitrary Distribution functions

### ISSUE THREAD

**Issue by konghz** [Warwick-Plasma/epoch#567]
Hi,
I use the Arbitrary Distribution functions method to initialize the drift-ring-beam distribution of particles. Are there any other methods for initializing the drift-ring-beam distribution of particles? 

drift-ring-beam distribution: 
![image](https://github.com/Warwick-Plasma/epoch/assets/148170245/5d922b3c-9a59-41eb-b003-687bc13439e3)

input.deck
begin:constant
  malpha = 1836.0*4*me
  vp =malpha* 0.0431618 * c    #the unique perpendicular speed
  vpt=0.001*vp                         #the perpendicular velocity spread of the fast ions    
  vparat=malpha*1000             #the parallel velocity spread of the fast ions

  vrange =3.0* vp
end:constant

begin:species
   name =alpha 
   charge = 2.0
   mass = 1836.0*4
   npart = 100 * nx
   number_density = 1.e16
   
   #ring beam distribution in velocity space
   dist_fn =exp(-(sqrt(px^(2)+py^(2))-vp)^(2)/vpt^2)*exp(-pz^2/vparat^2)
  
   dist_fn_px_range = (-vrange, vrange)
   dist_fn_py_range = (-vrange, vrange)
   dist_fn_pz_range = (-3*vparat, 3*vparat)
end:species

**Comment by Status-Mirror** [comment]
I think this would be the easiest method for your distribution.

If you wanted to specify the start position, momentum and weight of each macro-particle, you could use the [particles_from_file](https://epochpic.github.io/documentation/input_deck/input_deck_particle_file.html) block, but this would be more involved than what you're currently doing.

Hope this helps,
Stuart

**Comment by konghz** [comment]
Thank you very much for your response! It has been very helpful to me. One more thing I need to confirm with you is whether the initialization distribution function does not include the normalization factor, like in the following form:
![image](https://github.com/Warwick-Plasma/epoch/assets/148170245/71a8fa84-a467-4aa3-9ed6-1f50442737dc)
