### ISSUE TITLE
Unable to set "use_qed=T" in the "qed" block.

### ISSUE THREAD

**Issue by H1mp** [Warwick-Plasma/epoch#575]
As a student, I'm interested deeply in how to use EPOCH. Now the question is, to use the qed block, I have changed the Makefile and deleting this '#' symbol in front of the '$(D)PHOTONS'. The manual reads ' To turn on the effffect controlled by a given preprocessor directive, just uncomment the appropriate “DEFINES” line by deleting this “#” symbol'. However, there still appears error and the deck.status tells me that:

***** ERROR *****
Unable to set "use_qed=T" in the "qed" block.
Please recompile with the -DPHOTONS preprocessor flag.

I don't know how to correct modify Makefile and what steps I'm missing.
Can` you give me some advice on what should I do if I want to use the qed block? Thank you very much!

My input file is as follows

begin:control

nx = 450 # in x
ny = 600 # in y

nparticles = 10 * nx * ny

t_end = 300.0e-15

x_min = -10e-6
x_max = 35.0e-6
y_min = -3.0e-6
y_max = 3.0e-6
end:control

begin:boundaries
bc_x_min = simple_laser
bc_x_max = simple_laser
bc_y_min = simple_laser
bc_y_max = simple_laser
end:boundaries

begin:laser
boundary = x_max
intensity_w_cm2 = 5.0e22
lambda = 1.00 * micron
pol_angle = 0.0
phase = 0.0
profile = gauss(y, 0, 1.1* micron)
#t_profile=gauss(t, 0, 1.1* micron)
t_start = 0.0
t_end = 200.0e-15
end:laser

begin:species
name = electron
charge = -1.0
mass = 1.0
fraction = 0.5

nparticles = 2000 * 100
number_density = 4.5*1.1e27
temperature = 1e6
number_density_min = 2e17
number_density_max = 5e17
identify:electron
end:species

begin:species
name = Carbon
charge = 4.0
mass = 1836.0 * 12
fraction = 0.5
number_density = 0.25 * number_density(electron)
temperature= 1e6
dumpmask = full
end:species

begin:species
name = positron
identify:positron
end:species

begin:species
name = breit_wheeler_electron
identify:breit_wheeler_electron
end:species

begin:species
name = breit_wheeler_positron
identify:breit_wheeler_positron
end:species

begin:species
name = photon
identify:photon
end:species

begin:qed
use_qed=T
#produce_photons=T
#photon_dynamics=T
end:qed

begin:output

use_offset_grid = F

Number of timesteps between output dumps
dt_snapshot = 1.0e-14

full_dump_every = 10
restart_dump_every = -1
force_final_to_be_restartable = T

px = always
py = always
pz = always

particle_weight = never

Properties on grid
grid = always
ex = always
ey = always
ez = always
bx = always
by = always
bz = always
jx = always
jy = always
particle_energy=always
particles_per_cell=always+species

average_particle_energy = always + species
mass_density = never + species
charge_density = always
number_density = always + species

temperature = always + species
distribution_functions = always
particle_probes = never
end:output

**Comment by qiqi77346** [comment]
hey  @H1mp,
I think you don"t open QED preprocessor in the Makefile. You need to open "DEFINES += $(D)PHOTONS" by deleting this “#” symbol' in Makefile, then, recompilation by "make COMPILER=gfortran"

**Comment by Status-Mirror** [comment]
Hey @H1mp and @qiqi77346 

I'd say you're both right. You can either delete the `#` symbol, or compile with the extra flag. However, before you do this, I would advise you to run:

```
make clean
```

before you attempt recompilation. See our documentation on [compiler flags](https://epochpic.github.io/documentation/basic_usage/compiler_flags.html), specifically on **Changing precompiler directives**.

Hope this helps,
Stuart

**Comment by Status-Mirror** [comment]
I'm going to mark this issue as closed, but let me know if you're still having troubles.

Cheers,
Stuart
