### ISSUE TITLE
Magnetic field is empty

### ISSUE THREAD

**Issue by DrakeWhu** [Warwick-Plasma/epoch#587]
Hi EPOCH Team,

I am trying to run some simulations concerning LWFA and I need the magnetic field to calculate the transversal wakefield amplitude. The problem is that the magnetic field arrays appear as empty. I tried both with Boris and HC pushers and there's no difference. Here is the deck:

```
begin:constant
lambda0 = 0.5 * micro
dif_x = 0.01 * micro
dif_y = 0.02 * micro
dt = 0.8*dif_x/c
n_steps_max = 5000
end:constant

begin:control
nx = 1536
ny = 384
t_end = dt*n_steps_max
x_min = 0
x_max = nx*dif_x
y_min = -ny*dif_y/2
y_max = ny*dif_y/2
stdout_frequency = 100
end:control

begin:boundaries
bc_x_min = simple_laser
bc_x_max = open
bc_y_min = open
bc_y_max = open
end:boundaries

begin:constant
plasma_density = 3.3176e26
omega_p = sqrt(plasma_density*qe^2/(me*epsilon0))
lambda_p = 2*pi/omega_p
end:constant

begin:constant
I_fwhm = 1.0e-6 #0.37*lambda0/c
I_peak_Wcm2 = 5.0e19
pulse_length = lambda_p * 0.5
foc_dist = 0.75*nx*dif_x
end:constant

begin:constant
las_k = 2.0 * pi / lambda0
w0 = I_fwhm/sqrt(2.0*loge(2.0))
ray_rang = pi * w0^2 / lambda0
w_boundary = w0 * sqrt(1.0 + (foc_dist/ray_rang)^2)
I_boundary = I_peak_Wcm2 * (w0/w_boundary)^2
rad_curve = foc_dist * (1.0 + (ray_rang/foc_dist)^2)
gouy = atan(-foc_dist/rad_curve)
end:constant

begin:laser
boundary = x_min
intensity_w_cm2 = I_boundary
lambda = lambda0
phase = 0 #las_k * y^2 / (2.0 * rad_curve) - gouy
profile = gauss(y, 0, w_boundary)
t_profile = gauss(time,1/3*foc_dist/c, pulse_length) # Pulse longitude L of the order of plasma density
end:laser

begin:constant # Plasma structure
width = 0.35823 * micro
gap = 0.28915 * micro
w_cell = ceil(width/dif_y)
g_cell = ceil(gap/dif_y)
total_cells = w_cell + g_cell
fraction = w_cell/total_cells
y_structure = if((iy/total_cells-floor(iy/total_cells) lt fraction) or (iy/total_cells eq fraction), 0, plasma_density)
end:constant

begin:species
name = Electrons
charge = -1.0
mass = 1.0
temp = 0
npart_per_cell = 4
number_density = y_structure
end:species

begin:window
move_window = T
window_v_x = c
window_start_time = (x_max - x_min)/c
bc_x_min_after_move = open
bc_x_max_after_move = open
end:window

begin:output
dt_snapshot = dt * 100

ex = always
ey = always
bx = always
by = always
number_density = always + species
end:output
```

Any clue what can be happening?

**Comment by Status-Mirror** [comment]
Hey @DrakeWhu,

I'm able to run your simulation, and I also don't see non-zero `Bx` or `By`. You do have a `Bz` though.

You do not specify a laser polarisation, so it defaults to a linearly-polarised laser with electric field of the form $\pmb{E} = E\pmb{\hat{y}}$. Such a field has no $B_x$ or $B_y$ component.

For more information on laser defaults, you can check out the [laser block](https://epochpic.github.io/documentation/input_deck/input_deck_laser.html) documentation.

Cheers,
Stuart

**Comment by DanRRRR** [comment]
Hi DrakeWhu,
I see you are using moving window option. I am stuck with this option for some time already because it causes my code to crash at the time of this window start. Can you please share your EPOCH version, compiler type, version, and makefile switches ?

**Comment by DrakeWhu** [comment]
Hi guys,

In response to @Status-Mirror, yes I do have a bz. I changed my codes and now I get some useful arrays, thank you for you help.

In response to @DanRRRR, I don't remember all the details, but I am using EPOCH 4.19, compiled with intel as I am using a cluster with intel processors, don't remember the version of the compiler but I can check, and the makefile switches shouldn't affect as I ran this deck with a base installation of EPOCH without flags and it worked. 

I'll close this issue, feel free to create a new one explaining your problem and sharing your deck, I'd be happy to help there.

Best regards,
Juan

**Comment by DrakeWhu** [comment]
Hi guys,

In response to @Status-Mirror, yes I do have a bz. I changed my codes and now I get some useful arrays, thank you for you help.

In response to @DanRRRR, I don't remember all the details, but I am using EPOCH 4.19, compiled with intel as I am using a cluster with intel processors, don't remember the version of the compiler but I can check, and the makefile switches shouldn't affect as I ran this deck with a base installation of EPOCH without flags and it worked. 

I'll close this issue, feel free to create a new one explaining your problem and sharing your deck, I'd be happy to help there.

Best regards,
Juan

**Comment by DanRRRR** [comment]
Juan,
I think i found the reason for my crashes. Just submitted the bug report. The reason is that EPOCH crashes if you change in Makefile from its default to 
DEFINES += $(D)PER_PARTICLE_CHARGE_MASS  
Code crashes when moving window starts. 
I used gFortran.

**Comment by DrakeWhu** [comment]
Great! If anyone wants to check, it is in #592.
