### ISSUE TITLE
Moving Window in 1D

### ISSUE THREAD

**Issue by TrumeAAA** [Warwick-Plasma/epoch#598]
Hi, Is it possible to use a moving window in 1D case? Any suggestions will be helpful.
Best regards,
Ai.

**Comment by Status-Mirror** [comment]
Hey @TrumeAAA 

Yes, you should be able to have a moving window in 1D, using the [window block](https://epochpic.github.io/documentation/input_deck/input_deck_window.html). I've been meaning to create a moving-window basic examples page, but I wouldn't expect this in the next week or two.

Cheers,
Stuart
