### ISSUE TITLE
Compilation code problem

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#599]
Hello, I want to run my simulation on a server, but I can't compile the code. I've found a problem with MPI despite it already being installed. Could you please help me?

`mimouna@ilil-hpc-1:~/epoch-4.18.0-2022-12-14/epoch2d$ make COMPILER=gfortran
make[1]: Entering directory '/home/mimouna/epoch-4.18.0-2022-12-14/epoch2d'
mpif90 -o bin/epoch2d obj/background_collisions.o obj/balance.o obj/bethe_heitler.o obj/boundary.o obj/bremsstrahlung.o obj/calc_df.o obj/collisions.o obj/collision_ionise.o obj/constants.o obj/current_smooth.o obj/custom_deck.o obj/custom_laser.o obj/custom_parser.o obj/deck.o obj/deck_boundaries_block.o obj/deck_bremsstrahlung_block.o obj/deck_collision_block.o obj/deck_constant_block.o obj/deck_control_block.o obj/deck_dist_fn_block.o obj/deck_fields_block.o obj/deck_injector_block.o obj/deck_io_block.o obj/deck_io_global_block.o obj/deck_laser_block.o obj/deck_part_from_file_block.o obj/deck_particle_probe_block.o obj/deck_qed_block.o obj/deck_species_block.o obj/deck_stencil_block.o obj/deck_subset_block.o obj/deck_window_block.o obj/deltaf_loader.o obj/diagnostics.o obj/dist_fn.o obj/epoch2d.o obj/evaluate.o obj/evaluator_blocks.o obj/fields.o obj/file_injectors.o obj/finish.o obj/helper.o obj/ic_module.o obj/injectors.o obj/ionise.o obj/iterators.o obj/laser.o obj/mpi_routines.o obj/mpi_subtype_control.o obj/numerics.o obj/particle_id_hash.o obj/particle_migration.o obj/particle_pointer_advance.o obj/particle_temperature.o obj/particles.o obj/partlist.o obj/photons.o obj/prefetch.o obj/probes.o obj/random_generator.o obj/redblack_module.o obj/setup.o obj/shape_functions.o obj/shared_data.o obj/shunt.o obj/simple_io.o obj/split_particle.o obj/stack.o obj/strings.o obj/strings_advanced.o obj/terminal_controls.o obj/timer.o obj/tokenizer_blocks.o obj/utilities.o obj/version_data.o obj/welcome.o obj/window.o obj/epoch_source_info.o -O3 -g -std=f2003 -ffpe-summary=invalid,zero,overflow -I../SDF/FORTRAN/include -Iobj -Jobj -I/usr/include -L../SDF/FORTRAN/lib -lsdf
/usr/bin/ld: cannot find -lmpi_usempif08: No such file or directory
/usr/bin/ld: cannot find -lmpi_usempi_ignore_tkr: No such file or directory
/usr/bin/ld: cannot find -lmpi_mpifh: No such file or directory
/usr/bin/ld: cannot find -lmpi: No such file or directory
/usr/bin/ld: cannot find -lopen-rte: No such file or directory
/usr/bin/ld: cannot find -lopen-pal: No such file or directory
/usr/bin/ld: cannot find -lhwloc: No such file or directory
/usr/bin/ld: cannot find -levent_core: No such file or directory
/usr/bin/ld: cannot find -levent_pthreads: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:387: bin/epoch2d] Error 1
make[1]: Leaving directory '/home/mimouna/epoch-4.18.0-2022-12-14/epoch2d'
make: *** [Makefile:441: commit] Error 2
mimouna@ilil-hpc-1:~/epoch-4.18.0-2022-12-14/epoch2d$ `

**Comment by Status-Mirror** [comment]
Hey @mimboch,

Unfortunately there isn't much help we can give for setting up on individual servers. I see the line `cannot find -lmpi_usempif08` which could be referring to missing an mpi library? I think this would be worth bringing up with the server team.

Sorry I couldn't be more helpful,
Stuart

**Comment by mimboch** [comment]
Thanks a lot Stuart
