### ISSUE TITLE
Real time of the simulation

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#604]
Hello,
Please may I know the real-time of the simulation? I looked in the manual but didn't find it.

Thank you in advance.

**Comment by Status-Mirror** [comment]
I'm not sure I understand what you mean by real-time. Do you mean the amount of time the computer has been running, or the time-value at the current time-step of the simulation?

Cheers,
Stuart

**Comment by mimboch** [comment]
Hello,

I apologize for the delayed response. Yes, I mean the amount of time it takes for the computer to run a simulation.

Thanks a lot.

**Comment by DanRRRR** [comment]
If what you ask is about what you see if you put into input.deck this line

"stdout_frequency = 100"

then 
variable "timestring"  - is elapsed time of the simulation, and 
eta_timestring - is ETA

**Comment by Status-Mirror** [comment]
Just to add to what @DanRRRR has said, each `SDF` file is automatically created with a `Walltime` variable, which tells you the real-time taken to reach the output file in seconds.

Cheers,
Stuart
