### ISSUE TITLE
Dump output for particular specie

### ISSUE THREAD

**Issue by dmargarone** [Warwick-Plasma/epoch#616]
Hi,
suppose I have two particle species in the simulation, for example, electron_1 and electron_2. 

In the output block, if I write 
``
particles = always 
``
``
px = always + species 
``
then I will have 'Px' values for both the species (electron_1 and electron_2). 

**Is it possible to dump the output for only electron_1  ??**

Thanks.
DM

**Comment by Status-Mirror** [comment]
Hey DM,

In the electron_2 [species block](https://epochpic.github.io/documentation/input_deck/input_deck_species.html) you can write

```
dump = F
```

This should prevent all outputs from this species, unless you're doing a restart dump.

Cheers,
Stuart

**Comment by dmargarone** [comment]
Hi @Status-Mirror, 

Thanks for prompt reply. This is really very helpful (at least for me). Now, the output file is reduced by several times. 
If there is any issue (most probably because of my mistake), I will let you know. 

Thanks again.
DM
