### ISSUE TITLE
Linear density Ramp

### ISSUE THREAD

**Issue by amarsarari** [Warwick-Plasma/epoch#622]
Dear Sir 

How we can build linear density ramp for any species. For refer
![1](https://github.com/Warwick-Plasma/epoch/assets/136510249/f4392124-11c2-49b8-b020-b8645ac39fb2)
ence i m attaching a pic.

**Comment by Status-Mirror** [comment]
Hey @amarsarari,

This can be done by modifying the [basic target](https://epochpic.github.io/quickstart/basic_examples/particle_load.html#basic-target) input deck. An example implementation has been included at the end of this message.

Here I have added the line: `density = if (x gt 10.0e-6, 1.0e24 * (x - 10.0e-6) / 5.0e-6, 0)` to the species block. This should set the density to linearly rise from 0 to $10^{24} m^{-3}$ between $x=10\mu m$ and $x=15\mu m$, using EPOCH [maths parser](https://epochpic.github.io/documentation/code_details/maths_parser.html) syntax. Note that this line actually makes the density rise linearly up to the $x_{max}$ boundary, but we override the behaviour after $x=15\mu m$ in the following lines.

```
begin:control
    nx = 500
    ny = 500
    t_end = 1.0e-15
    x_min = 0
    x_max = 25e-6
    y_min = 0
    y_max = 25e-6
    stdout_frequency = 100
    npart = 50 * (5.0e-6/(x_max-x_min)) * nx * ny
end:control

begin:boundaries
    bc_x_min = open
    bc_x_max = open
    bc_y_min = open
    bc_y_max = open
end:boundaries

begin:species
    name = Electron
    mass = 1.0
    charge = -1.0
    frac = 0.8
    density = if (x gt 10.0e-6, 1.0e24 * (x - 10.0e-6) / 5.0e-6, 0)
    density = if (x gt 15.0e-6, 1.0e24, density(Electron))
    density = if (x gt 20.0e-6, 0, density(Electron))
    temp_ev = 1000
end:species

begin:species
    name = Carbon
    mass = 22033.0
    charge = 6.0
    frac = 0.2
    density = density(Electron) / 6
    temp_ev = 1000
end:species

begin:output
    dt_snapshot = t_end
    number_density = always
end:output
``` 

![ramp](https://github.com/Warwick-Plasma/epoch/assets/38282483/3ad37822-7555-41d5-b2e3-16223ac28395)
