### ISSUE TITLE
Error in make file

### ISSUE THREAD

**Issue by amarsarari** [Warwick-Plasma/epoch#623]
Entering directory '/home/hp/Epoch/epoch-4.17.16/epoch2d'
make[1]: *** No rule to make target 'background_collisions.F90', needed by 'background_collisions.o'.  Stop.
make[1]: Leaving directory '/home/hp/Epoch/epoch-4.17.16/epoch2d'
make: *** [Makefile:444: commit] Error 2
 **Why this error is coming**

**Comment by Status-Mirror** [comment]
Try running:

```
make clean
make COMPILER=gfortran
```
