### ISSUE TITLE
How to set a self-consistent polarization direction of an obliquely incident laser?

### ISSUE THREAD

**Issue by Bellahra** [Warwick-Plasma/epoch#654]
Dear Epoch developers,

I am curious about if the electric field direction of an obliquely incident laser can be set as perpendicular to its wave vector but not the coordinate axes. That is, if I want to launch an obliquely incident laser on the x_min boundary, I have to give its `pol_angle` or `pol` to specify the polarization direction. However, the `pol_angle (pol)` is the angle clockwise about the coordinate axis but not the wave vector, but if so the electromagnetic wave is not a transverse wave any longer. So I want to know if is there any trick to set a self-consistent polarization of an obliquely incident laser. My Epoch version is 4.16. 

> If the laser is on x min then the default E field is in the y-direction and the B field is the z-direction. The polarisation angle is measured clockwise about the x-axis with zero along the Ey direction. 

Thanks in advance.
Bell

**Comment by Status-Mirror** [comment]
Hey Bell,

Does our [Injecting the laser at an angle](https://epochpic.github.io/quickstart/basic_examples/laser.html#angle_laser_injection) demo provide the functionality you're after? You're right that the `pol` key only rotates the direction of `E` and `B` about the wave-vector, without rotating the wave-vector itself.

Hope this helps,
Stuart
