### ISSUE TITLE
How to make me move the window in the negative X direction

### ISSUE THREAD

**Issue by feelingxxxxxxx** [Warwick-Plasma/epoch#655]
Dear Epoch developers： 
      The default direction for moving the window is the positive X-axis direction, but my current requirement is to make it the negative X-axis direction. Is there a good solution?

**Comment by Status-Mirror** [comment]
Hey @feelingxxxxxxx,

I've checked the source-code and I don't think EPOCH supports this. What's preventing you from using the positive $x$-motion window? Everything else in EPOCH should be able to be rotated.

Cheers,
Stuart
