### ISSUE TITLE
S polarized beam

### ISSUE THREAD

**Issue by amarsarari** [Warwick-Plasma/epoch#656]
Dear sir,
How we can generate s-polarized pulse.

**Comment by Status-Mirror** [comment]
Hey @amarsarari,

An S-polarised pulse propagates at an angle to the target, and has a polarisation such that the electric field oscillates in a special direction with respect to the target surface.

You can rotate the target by following the rotated target demo on [this page](https://epochpic.github.io/quickstart/basic_examples/particle_load.html).

And you can change the electric field oscillation direction by using the [pol_angle](https://epochpic.github.io/documentation/input_deck/input_deck_laser.html).

Hope this helps,
Stuart
