### ISSUE TITLE
The normalisations are used in EPOCH

### ISSUE THREAD

**Issue by Shihang-Hu** [Warwick-Plasma/epoch#658]
I see in the documentation that the SI units are used in EPOCH. Why not normalize the physical quantities? 
I think it will make computers calculate faster. And for our who study numerical calculation it is easier to understand.

**Comment by Status-Mirror** [comment]
When it comes to being "easier to understand", that depends who you ask. Experimentalists will often quote parameters in terms in SI units, so this helps quick conversion to input decks. It's useful to have a consistent unit set when sifting through source-code.

You could make the argument that normalised units improve the bit-precision, but we would have to involve physical scales at some point for physics packages like collisions and radiation. For the purposes of simplicity, we've opted for SI.

Cheers,
Stuart
