### ISSUE TITLE
Temprature parameter in input.deck

### ISSUE THREAD

**Issue by naokikatsura** [Warwick-Plasma/epoch#664]
Dear All,

I am currently using EPOCH2D version 4.19.2 to simulate the expansion process of high-density (n0 = 10^23 m^-3) and high-temperature (T0 = 1 keV) plasma in an external divergent magnetic field. Before conducting simulations involving the magnetic field, I performed two test calculations of plasma expansion without the magnetic field using identical parameters, except for the temperature settings. The temperature in the first simulation is set by:

number_density = if(sqrt(x*x+y*y) lt r0, n0*(1-sqrt(x*x+y*y)/r0), 0.0)
temp_ev = if(sqrt(x*x+y*y) lt r0, T0, 0.0)

In the second simulation, it is set by:

number_density = if(sqrt(x*x+y*y) lt r0, n0*(1-sqrt(x*x+y*y)/r0), 0.0)
temprature_ev = if(sqrt(x*x+y*y) lt r0, T0, 0.0).

The spatial distribution of electron number density shows differing characteristics between the two simulations (please see the attached figures).
![ne0005_temp](https://github.com/Warwick-Plasma/epoch/assets/153072401/2147130c-aa4d-4358-b468-47bdc457b5e0)
![ne0005_temprature](https://github.com/Warwick-Plasma/epoch/assets/153072401/e68da969-7e31-4969-a172-7fb8f19c165c)
 The distribution set by temp_ev demonstrates spreading over time, whereas in the second simulation, the electrons remain at their initial positions. I attach the input.deck of this simulation just in case. 
[input_deck.txt](https://github.com/user-attachments/files/15616603/input_deck.txt)

Could anyone explain why these differences occur?

Thank you for your assistance.

Regards,
Naoki Katsura

**Comment by TomGoffrey** [comment]
It's hard to tell without your full second input deck (the one which shows no expansion), but I suspect the issue you are seeing is due to the spelling of `temprature_ev` being incorrect. Try `temperature_ev`.

**Comment by naokikatsura** [comment]
Oh, I didn't notice that 'temperature' was mistyped as 'temperature.' That's so embarrassing!
Thank you for your comment.
