### ISSUE TITLE
t_profile from an external file

### ISSUE THREAD

**Issue by TrumeAAA** [Warwick-Plasma/epoch#667]
Hi,
    Is it possible to read the t_profile from an external file? Any suggestions will be helpful.
All the best
Ai

**Comment by TomGoffrey** [comment]
AFAIK this is not currently possible. I do note this has been requested previously #79 - but I can't currently provide an estimate on when it will be implemented.

**Comment by TrumeAAA** [comment]
Thanks for your kind reply



---Original---
From: "Tom ***@***.***&gt;
Date: Sun, Jun 16, 2024 18:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Warwick-Plasma/epoch] t_profile from an external file (Issue#667)




 
AFAIK this is not currently possible. I do note this has been requested previously #79 - but I can't currently provide an estimate on when it will be implemented.
