### ISSUE TITLE
After the end of the laser there are still electric field fluctuations, how to eliminate?

### ISSUE THREAD

**Issue by feelingxxxxxxx** [Warwick-Plasma/epoch#675]
![1](https://github.com/Warwick-Plasma/epoch/assets/141721838/ccc91819-fee5-4e4d-8a29-4ec2ca9d15ff)

Dear teacher: 
Hello, in the first picture of ey electric field diagram in my 1D simulation, the horizontal coordinate is X (laser propagation direction), and the vertical coordinate is amplitude. We can see that the laser peak electric field is on the order of 1e14, but after the laser pulse is over, there is still an electric field (red box in the figure), about 1e4-1e10 (close to the X-axis shown in the figure), which has caused great trouble to my simulation. Is there any way to remove this non-laser electric field? The second picture is me writing the laser code.

![2](https://github.com/Warwick-Plasma/epoch/assets/141721838/a9a43a9e-e784-49dc-8baa-283b5b4556ea)

**Comment by Status-Mirror** [comment]
Hey @feelingxxxxxxx,

In this example, your temporal profile `t_profile` is a gaussian distribution, which will not drop to 0 at any time. You might want to try using `t_end` to switch the laser off, which is discussed in the [laser block](https://epochpic.github.io/documentation/input_deck/input_deck_laser.html) documentation.

Hope this helps,
Stuart
