### ISSUE TITLE
A question about the collisional ionization.

### ISSUE THREAD

**Issue by xuwangwen** [Warwick-Plasma/epoch#677]
Hello, I found that when using ionization, considering only collisional ionization and not considering field ionization. Why there is no free electrons were produced. I used the epoch-4.19.3, there is my input.deck for the ionization setup:

begin:control
  use_multiphoton = F
  use_bsi = F
  field_ionisation = F
end:control

begin:species
  name = Ion
  mass = 27.0*1836.0
  npart_per_cell = 200
  temp_ev = 100.0
  atomic_no = 13
  ionise = T
  ionisation_electron_species = \
  (electron, electron, electron, electron, electron, electron, electron, electron, electron, electron, electron)
  density = dens_i
  bc_x_min = simple_outflow
  bc_x_max = simple_outflow
end:species

begin:collisions
  use_collisions = T
  collisional_ionisation = T
  ci_n_step = 1
  use_nanbu = T
  coulomb_log = auto
  collide = all
end:collisions

**Comment by TomGoffrey** [comment]
Is this your complete input deck?

**Comment by xuwangwen** [comment]
> Is this your complete input deck?

Thak you, this is a part of the input deck. I have found the soulution about this question.

**Comment by TomGoffrey** [comment]
OK. In the future, please include a full input deck, otherwise it's not possible for us to investigate the issue.
