### ISSUE TITLE
1D epoch simulation

### ISSUE THREAD

**Issue by Khatua03** [Warwick-Plasma/epoch#681]
Dear all,
I am simulating some 1D PIC using epoch to understand how it works. But, it is hard for me to understand the simulation as we are using only one dimension (let say x-axis), but all three velocity components. That's why we call it 1D3V PIC simulation. Can anyone please help me understand this? Why we need all 3 velocity components. I guess it is because of the gyroscopic motion of a charged particle in plasma and Ampere's law. If this is the reason, how do we limit the position of the particle only in the x-direction? Can someone please suggest some of the articles to understand 1D PIC? Can someone please suggest how exactly a 1D3V PIC simulation works?

I am also performing one 1D PIC simulation only with one electron. I found that the Ex field is moving only in one direction, i.e., along the direction of elctron motion, while Ey and Ez are symmetric, which is reasonable. My concern is that why Ex stays stationary at one position all the time while the charge is moving. I guess from the plot, it will be clear. I am attaching the plots of Ex, Ey, and Ez with the charge density and input.deck file. Can anyone please help me with this? In all the plots, the x-axis represents grid points, and the y-axis represents time in multiples of 5 fs.
![Cd](https://github.com/user-attachments/assets/6b7ff47a-014f-41de-9bea-2a013d1fbbbc)
![Ex](https://github.com/user-attachments/assets/2a04b028-4d92-4efb-b2fd-6f3f39d8c98f)
![Ey](https://github.com/user-attachments/assets/d891d768-5393-4986-9c68-00d95b068d0d)
![Ez](https://github.com/user-attachments/assets/66873563-54c5-4307-9e5a-62f72e731426)
[input.txt](https://github.com/user-attachments/files/16241485/input.txt)

Thanks,
DP Khatua.

**Comment by Status-Mirror** [comment]
Hey DP Khatua,

For 1D PIC simulations, you can think about it like this. Imagine you have a laser propagating through your 1D line of cells, with a sinusoidal wave in $E_y$. From the Lorentz force, we know that electrons will accelerate in the $E$ direction, so they gain a $v_y$. This in turn generates a current density along $y$, which iteracts with the laser fields through Maxwell's equations. In this way, the laser interacts with the plasma.

By restricting the simulation to 1D, even though particles have $v_y$, there is no particle push in the $y$ direction. Particles don't have a $y$ co-ordinate. Physically, this is the same as modelling an infinite sheet of particles, with a uniform laser profile in $y$ and $z$. Whenever a particle moves up in $y$, it is replaced by the particle below, as all particles are in the same environment along $y$ and $z$.

Your single electron $E_x$ buildup is a different issue. On initialisation, EPOCH assumes each cell is neutral - the code thinks there's an immobile positive charge in the cell your electron starts in. As it moves away, a space-charge field is established from Gauss' law. This is what you're seeing here.

Hope this helps,
Stuart

**Comment by Khatua03** [comment]
Dear Stuart,
Thank you for giving your insight into this issue. It helps a lot. Can you please suggest some publications to understand the 1D simulation in more detail? 3D and 2D are easier to understand. But to understand the working of 1D is a little more complicated.

Thanks,
with best regards, 
DP Khatua

**Comment by Status-Mirror** [comment]
Hi @Khatua03, 

There's no reference I'm aware of which discusses the limits of the 1D PIC approximation, or when it's best to use it. People run 1D simulations when they want a quick result, and they don't care about transverse structure. It's just uniform laser illumination of infinite area targets. Useful for tracking things like heat-flow in 1 dimension.

I'm going to mark this issue as closed for now, but let me know if you have any other questions about 1D PIC simulation.

Cheers,
Stuart
