### ISSUE TITLE
3D Gaussian laser

### ISSUE THREAD

**Issue by crazy-gif** [Warwick-Plasma/epoch#683]
Dear All,
I am new to EPOCH and have finished the example of 2D Gaussian laser. Now I am trying to transfer 2D laser to 3D laser. I add the grid nz and t_profile, then replace the y in profile with r=sqrt(y^2+z^2). However, the code can not run with the error that "no compile time options". I don't know how to tackle this question. Can anyone give me some advice? 

Thank you.
Regards,
crazy_gif
[input.deck.txt](https://github.com/user-attachments/files/16314637/input.deck.txt)

**Comment by Status-Mirror** [comment]
Hey @crazy-gif,

I'm not sure if this is your problem, but are you aware your t_profile can go negative? At $t=2.5$ fs, your `t_profile` is -1. This key is supposed to describe the _envelope_ of the laser, not the oscillation term.

Have a look at our [laser pulse example](https://epochpic.github.io/quickstart/basic_examples/laser.html#laser-pulse) to see how you might want to implement a temporal envelope. If you still have issues, let me know.

Cheers,
Stuart

**Comment by crazy-gif** [comment]
Dear @Status-Mirror，
 Thanks for your advice. Acording to it, I have correct the t_profile to make it  be positive. However, the code still can not run.If there are other error?
Thank you,
crazy_gif 
[3Dlaser.txt](https://github.com/user-attachments/files/16359617/3Dlaser.txt)

**Comment by TomGoffrey** [comment]
`no compile time options` is not an error. It's a message printed if EPOCH is compiled with default options. What makes you think the code can't run?

**Comment by crazy-gif** [comment]
Hey @TomGoffrey,
      Thanks for your help. When I try to  run it on the super computing  platform, there is no the sdf file that I usually  get. Then, I think the code have some errors so that it can not run.

**Comment by Status-Mirror** [comment]
Hi @crazy-gif,

A 3D EPOCH simulation like this will be slower than a 2D equivalent. Maybe you just need to run the simulation for longer?

You can make the code output its progress on every step by adding the line:

```
    stdout_frequency = 1
```

to your `control` block. As a quick warning, most groups find 3D simulations too computationally demanding to actually run, even on supercomputers. Most of the papers using PIC simulation keep to 2D.

Hope this helps,
Stuart

**Comment by TomGoffrey** [comment]
Might also be worth adding `dump_first=T` to an output block to check you have no I/O issues. The files are potentially very large.

**Comment by hoaithanhbk** [comment]
> Dear All, I am new to EPOCH and have finished the example of 2D Gaussian laser. Now I am trying to transfer 2D laser to 3D laser. I add the grid nz and t_profile, then replace the y in profile with r=sqrt(y^2+z^2). However, the code can not run with the error that "no compile time options". I don't know how to tackle this question. Can anyone give me some advice?
> 
> Thank you. Regards, crazy_gif [input.deck.txt](https://github.com/user-attachments/files/16314637/input.deck.txt)

can you contact with me via email "hoaithanhbk281113@gmail.com" thank you

**Comment by crazy-gif** [comment]
Dear @Status-Mirror,
Thanks for your advice  again.I have  solved the  proplem and gotten the sdf files quikly，after I change nx=500 to nx=200 and recompile the DevelopmentenEnvironment.
thanks again
crazy_gif

**Comment by crazy-gif** [comment]
hey @TomGoffrey ，
     thanks for  your  advice. Your guess is right. The output files are so  large  that I  have to change  it to nx=200 to  get the sdf files quickly. At the same time，I use more computer nodes to run it.Now，I have solved  this proplem.
thank you again
carzy_gif
