### ISSUE TITLE
First simulation with EPOCH

### ISSUE THREAD

**Issue by hoaithanhbk** [Warwick-Plasma/epoch#687]
Dear All member,
I am newbine using epoch. Now I am trying to run first simulation with Epoch. I have successfully installed Epoch. I am running first Epoch via "Quick start guide".

- step 1: I copy and change the name "**ionisaltion.deck**" in epoch1d/example_deck folder to "**input.deck**"
- step2:  I move to dictionary to epoch1d: cd epoch/epoch1d
- step3: I type the command " mpirun -np 4 ./bin/epoch1d <<</home/thanh/epoch/epoch1d/example_decks

the my result running

![epcoh](https://github.com/user-attachments/assets/d3197a89-3d00-4f60-b2b2-8787542b434a)

-step4: I saw three  new files (0000.sdf, deck.status, normal.visit)  appears in example_deck folder.

I want to ask you, my simulation do finish yet?

if yes, how to saw the my result. now I am using the "visit" software to visulize.

I was trying to open "visit" 
- step 1: I choose file/open the 0000.sdf file like the following picture and click "ok"
![visualize](https://github.com/user-attachments/assets/fc10cc0d-6b0c-4795-8e09-67b8624e0b7c)

- I got the error " Visit could not read from the file "0000.sdf"
![error](https://github.com/user-attachments/assets/2bc251af-52f5-40ce-bc2b-e88ddbbc3089)

one more thing when I read the userguide of epoch. the result of epoch will be so many sdf file like picture. But my result they are just have only one a sdf file (0000.sdf).

I know my question maybe very basic. I hope you can help me to run for first simulation in EPOCH.

thank you for any helps!

**Comment by Status-Mirror** [comment]
I know some other developers have managed to get EPOCH running on Visit, but I've never managed it myself unfortunately. Most users I know use MATLAB or Python to read SDF files - MATLAB uses the `GetDataSDF` function in `SDF/Matlab`, and Python can be setup according to the guide on [this page](https://epochpic.github.io/documentation/visualising_output/python.html).

I'll keep the issue open for now in case any Visit users would like to comment further.

Sorry I couldn't be more helpful,
Stuart

**Comment by hoaithanhbk** [comment]
Thank you for your reply!
the fist  what is the status of my first simulation by EPOCH. it is successful or not? Because I just saw a one SDF file (0000.sdf). it take about 0.02 second to run.

**Comment by Status-Mirror** [comment]
If you're getting SDF files, it probably ran successfully. The files in `example_deck` are mainly there to demonstrate input-deck syntax, they're not proper simulations. If you want to learn more about EPOCH, I think it would be better to go through the worked examples on [particle loading](https://epochpic.github.io/quickstart/basic_examples/particle_load.html), [laser injection](https://epochpic.github.io/quickstart/basic_examples/laser.html) and [ionisation](https://epochpic.github.io/quickstart/basic_examples/ionisation.html). The Ionisation demos are a bit more technical, but they're worth reading if you want to simulate ionisation.

Hope this helps,
Stuart

**Comment by Status-Mirror** [comment]
I'm going to mark this issue as closed for now, but feel free to re-open if you run into more problems.

Cheers,
Stuart
