### ISSUE TITLE
Clarification and Assistance Needed on `x_start` Definition and Gaussian Beam Profile in EPOCH

### ISSUE THREAD

**Issue by FeliciaHtt** [Warwick-Plasma/epoch#689]
Dear developers,

I am currently working on simulating a Gaussian beam using EPOCH and have come across a couple of points where I need your confirmation and assistance.

1. **Clarification on `x_start` Definition:**
In the user manual examples, I encountered the `x_start` variable. I suppose this refers to the laser focal length. However, when setting `x_start` to any length within the simulation domain, it seems to only accept the minimum or maximum values of the domain. For instance, with `x_min = -20 micron` and `x_max = 20 micron`, I receive an error if `x_start` is set to any value other than `x_min` or `x_max`. Could you please confirm if `x_start` is indeed the laser focal length and why it only accepts the boundary values of the simulation domain?

2. **Gaussian Beam Profile:**
Additionally, I would like to confirm the correct syntax for simulating a Gaussian beam. Should we use:
   `profile = gauss(y, 0, w0)`
or
  ` profile = gauss(y, 0, w_bnd)`
for the Gaussian beam profile?

Thank you in advance for your help and looking forward to your response.

**Comment by TomGoffrey** [comment]
1. `x_start` is a synonym for `x_min`, it has no impact on the laser. See the documentation: https://epochpic.github.io/documentation/input_deck/input_deck_control.html
2. I can't answer this without knowing what `w0` and `w_bnd` are, but you might want to consult the documentation on the `gauss` function: https://epochpic.github.io/documentation/code_details/maths_parser.html

**Comment by FeliciaHtt** [comment]
Thank you for your reply and sorry for not clarifying what w0 and w_bnd represent. 
w0 is the beam waist and w_bnd is the beam waist at boundary.

**Comment by TomGoffrey** [comment]
As the profile is evaluated at the boundary I would think the boundary value is the correct one to use. You could always perform a quick test run in a vacuum to check if the laser profile is as expected.

**Comment by FeliciaHtt** [comment]
Thank you for the suggestion.
