### ISSUE TITLE
Possible typo in the source code when evaluating the constant "r_xyz"

### ISSUE THREAD

**Issue by XiangyanAn** [Warwick-Plasma/epoch#700]
I just found that in epoch3d/src/parser/evaluator_blocks.F90, line 300-305, the code reads:
```
IF (parameters%use_grid_position) THEN
        CALL push_on_eval(&
            SQRT(x(parameters%pack_ix)**2 + y(parameters%pack_iy)**2 &
               + z(parameters%pack_iy)**2))
      ELSE
```
the index of `z` might probably be `parameters%pack_iz`. Otherwise the parser would give a wrong `r_xyz`.

**Comment by TomGoffrey** [comment]
@XiangyanAn thanks for bringing this to our attention. This has been fixed.
