### ISSUE TITLE
How to set up parabolic mirror reflecting laser in EPOCH.

### ISSUE THREAD

**Issue by ouyangchen666** [Warwick-Plasma/epoch#704]
Dear teacher
    Hello, teacher. I would like to ask how to set up a parabolic mirror (a mirror with a rotating parabolic surface) in the input.deck file in EPOCH. For example, how to set the position of the parabolic mirror and its focal length? For a sector-shaped plane mirror, how do I set its radius and sector angle?

**Comment by Status-Mirror** [comment]
Hi @ouyangchen666,

EPOCH isn't able to simulate structures which simply reflect the laser - just lasers and plasma. Lasers will correctly reflect off plasmas, but tuning a plasma profile to act as a mirror would be a difficult task.

Most users will simply inject a laser with the desired properties into the simulation, and have this hit the final target. To inject a focusing Gaussian beam, check out our [focusing beam demo](https://epochpic.github.io/quickstart/basic_examples/laser.html#focussing_a_gaussian_beam).

Hope this helps,
Stuart

**Comment by ouyangchen666** [comment]
Teacher, can multiple laser blocks be added in EPOCH, forming multiple sub-pulses by setting different time delays and profiles for the lasers? For example, I added 15 pulses. However, the problem is that during the simulation, even the sdf file at t=0 is not generated. I set dt_snapshot=10*femto. The simulation is still running, but no output files are produced. What could be the reason for this?"

**Comment by Status-Mirror** [comment]
I'm going to mark this issue as closed for now, but if you're still having a problem with those 15 pulses, feel free to start a new issue. Make sure to include your input deck, as EPOCH should be able to run with an arbitrary number of lasers.

Cheers,
Stuart
