### ISSUE TITLE
Can epoch output laser angular momentum and plasma angular momentum?

### ISSUE THREAD

**Issue by kwang12008** [Warwick-Plasma/epoch#714]
In my recent work, it is necessary to obtain laser angular momentum and plasma angular momentum. But the self-generated electromagnetic field of the plasma will affect the calculation of the angular momentum of the laser. Hope to get your answer.

**Comment by Status-Mirror** [comment]
There isn't a standard output for the plasma angular momentum, but you are able to output the positions and momenta of EPOCH particles. It should be possible to calculate angular momentum from this.

I'm less sure what the angular momentum of a laser pulse is. How would you calculate this?

Cheers,
Stuart

**Comment by kwang12008** [comment]
I interact a circularly polarized Gaussian pulse with the plasma. The angular momentum of the field is calculated based on the following formula
![image](https://github.com/user-attachments/assets/d68d078c-aec3-4ef6-86cb-6194e58d5fd1)
Obviously, the self-generated field of the plasma also affects the calculation of angular momentum.So that the angular momentum of the laser field itself cannot be accurately obtained.In addition, I calculated the angular momentum of the plasma by the following formula
![image](https://github.com/user-attachments/assets/e3f77605-de4f-4f28-8d18-897e023b6ebe)

**Comment by Status-Mirror** [comment]
If $g_x$, $g_y$ and $g_z$ refer to a generic field, then you should be able to calculate this from the simulation data. If you create an output block which rapidly outputs the field values, then you have fields and positions at multiple nearby time-steps.

If your $d\tau$ integral refers to a time-integral over some period $\tau$, and you force multiple outputs over the $\tau$ period, then you can calculate $xg_x - y g_y$ for each output, average this value, and multiply it by $\tau$. This would give you an angular momentum for the fields currently present in the simulation window.

Does this make sense?
Stuart

**Comment by kwang12008** [comment]
I'm sorry I didn't explain the formula. 
$M_x$,$M_y$ and $M_z$ refer to total angular momentum of the field .$g_x$, $g_y$ and $g_z$ refer to momentum density of electromagnetic field, so $r x g$ refers to the angular momentum density. $d\tau$ integral refers to a space-integral over some specified domain.Based on this formula, I can calculate the angular momentum of the field at a given time.

**Comment by Status-Mirror** [comment]
Right, I see. From a quick Google search, it looks like the momentum density of an electromagnetic field is equivalent to $S/c^2$, where $S$ is the Poynting flux. You can output the Poynting flux in each cell, for each $x,y,z$ direction, using the `poynt_flux` key in the [output block](https://epochpic.github.io/documentation/input_deck/input_deck_output_block.html). If you divide these numbers by $c^2$, you should get $g_x, g_y, g_z$ in each cell.

Over your specified spatial domain, you can calculate $x g_y - y g_x$ in each cell using the cell's $x$ and $y$ co-ordinates, and the previously calculated $g$, (or equivalent for $M_x$ and $M_y$). If you then average this value over all the cells in your region of interest, and multiply this by the volume of your region of interest, this is equivalent to taking the integral. This is how you would calculate $M$, if I interpret your equation correctly.

Hope this helps,
Stuart

**Comment by kwang12008** [comment]
Thanks for your reply!
But my problem is that the electromagnetic field of the plasma will interfere with my calculation of the angular momentum of the laser. I just want to get the angular momentum of the laser field.

**Comment by Status-Mirror** [comment]
EPOCH cannot distinguish between laser-fields and plasma-fields - there is only one set of $E$, $B$ fields in the code. The laser properties are modified through interaction with the plasma, so it wouldn't be obvious where the laser ends and the plasma begins. The label of "laser fields" would be pretty arbitrary here. Are you aware of any work which has separated laser fields from plasma fields in PIC simulation before?

If you have a laser incident on a solid target, maybe just consider the angular momentum in a region after the laser has reflected, where there is no plasma present.

If the laser passes through a plasma region, maybe include a vacuum layer after the plasma, and inspect the laser properties here after it has passed through the target?

For a more advanced technique, you could output the total angular momentum fields from many nearby time-steps, and then run a Fourier transform of the result. You could then filter out Poynting flux oscillations on the order of the laser-frequency, as any Poynting flux oscillating at the laser frequency should be the laser.

Hope this helps,
Stuart

**Comment by kwang12008** [comment]
I hadn't noticed the work of separating the laser field from the plasma field before. Thank you for your helpful advice.
