### ISSUE TITLE
Dear author: This is a problem I encountered while compiling the makefile file. How can I solve it? Looking forward to your answer, thank you very much.

### ISSUE THREAD

**Issue by bear-maker** [Warwick-Plasma/epoch#717]
Dear author:
This is a problem I encountered while compiling the makefile file. How can I solve it?
Looking forward to your answer, thank you very much.

![1727618732492](https://github.com/user-attachments/assets/f2c4d2ba-284d-4f07-b88e-399792defe53)

**Comment by TomGoffrey** [comment]
It appears that the build system couldn't find python, so falls back to an alternative method. The build appears to continue. Does the build eventually fail?

**Comment by bear-maker** [comment]
> It appears that the build system couldn't find python, so falls back to an alternative method. The build appears to continue. Does the build eventually fail?

Thank you for your response. The build will not fail, there is no Python in the system. I want to know if this is the reason why I use different MPI to run the same code with different results.

**Comment by TomGoffrey** [comment]
OK, but I am already addressing that question in your other issue.
