### ISSUE TITLE
mpirun -np 80

### ISSUE THREAD

**Issue by Garnet5867** [Warwick-Plasma/epoch#719]
Dear Author,

My question is: When running EPOCH, we initially used 80 threads, but after reinstalling EPOCH, it can only detect 40 threads. Could this be a compilation issue? No errors occurred during the compilation process.

Best regards.

**Comment by Status-Mirror** [comment]
I think an EPOCH domain needs a minimum of 5 cells. If your simulation has fewer than 400 cells, it won't be able to run with 80 threads.

Hope this helps,
Stuart

**Comment by Garnet5867** [comment]
Dear Professor,
Hello! We have resolved the issue and discovered that it was caused by an outdated version of the MPICH parallel library, which led to recognition problems. During testing, we noticed that OpenMPI could only recognize 40 threads. We’re not sure why this is happening and would greatly appreciate any insights you might have.Thank you for your assistance!

**Comment by Status-Mirror** [comment]
Hi @Garnet5867,

I'm happy you resolved the issue! I've noticed similar behaviour to what you describe before on some systems, and I think it's related to hyperthreading - where the system splits each core into 2, allowing MPI to run with effectively double the number of physical cores. Maybe this is something to look into for a better understanding.

Cheers,
Stuart
