### ISSUE TITLE
Inquiry on Real vs. Pseudo-Particles in Epoch Simulation

### ISSUE THREAD

**Issue by Garnet5867** [Warwick-Plasma/epoch#730]
Dear Professor,

I would like to inquire whether there are real particle positions and other information in the epoch PIC simulation, or are all real particles calculated based on pseudo-particles? If the real particles are calculated based on pseudo-particles, then why can the spectrum display all particles, or why can the density show the situation of all particles?

**Comment by Status-Mirror** [comment]
Hi @Garnet5867,

EPOCH simulates macro-particles, which represent large numbers of real particles. When you output a particle variable, you're given the details of a real particle "contained within" the macro-particle, and the number of real particles the macro-particle represents is the `weight`. When you output a derived quantity like `density`, the code sums the weights of all the macro-particles in each cell to find the total number of real particles present, then divides by the cell volume.

So yes, EPOCH does track computational pseudo- or macro- particles, but you can also use these to estimate densities or spectra of real particles, by using the macro-particle weights.

Hope this helps,
Stuart

**Comment by Garnet5867** [comment]
Dear Professor,

I apologize if I'm being slow to understand. Regarding your statement: "

> you're given the details of a real particle 'contained within' the macro-particle, and the number of real particles the macro-particle represents is the weight,

does this mean that I can pinpoint the location of each real particle? Or am I only able to estimate the real particles' positions based on the weights and the positions of the macro-particles? I would appreciate your clarification on this matter.

Thank you.

**Comment by Status-Mirror** [comment]
This depends on what you want to model, and there are different ways to think about it.

A macro-particle is a computational object which has a shape, extending over multiple cells. This is used for interpolating fields to the macro-particle position, and is discussed in our [developer documentation](https://epochpic.github.io/developer/core_structure/shape_functions.html). You can think of this shape as describing the distribution of real particles within the macro-particle.

I'd advise caution though, as PIC codes don't model the trajectory of every particle - we use macro-particles and grids. Using EPOCH to identify the position of all real particles within the plasma assumes a greater accuracy than EPOCH can provide.

For most analysis, it is sufficient to assume that the positions and trajectories of macro-particles correspond to the positions and trajectories of real particles, and the macro-particle weight tells you how many real particles follow that trajectory. Without knowing more about your specific needs, I can't make comments on the relevance of this way of thinking.

**Comment by Status-Mirror** [comment]
I'm going to mark this issue as closed for now, but feel free to re-open if you have more questions.
