### ISSUE TITLE
Module (sdf_helper) not found Error

### ISSUE THREAD

**Issue by Tar-phy** [Warwick-Plasma/epoch#731]
Hello , I cannot run python file to read SDF file , there is a Error "module not found". I'm facing this problem after updating my Ubutnu version 22 to Ubuntu 24  . 
Any one can help me to solve this problem
![Screenshot from 2024-10-23 11-01-30](https://github.com/user-attachments/assets/4a260a03-6784-4cd9-a6b5-8c889d278e6a)
![Screenshot from 2024-10-23 11-28-26](https://github.com/user-attachments/assets/e6f72b7d-f7cd-4a26-b8da-2e329f790faf)

**Comment by TomGoffrey** [comment]
I can't see the top of the second error message, but I'm assuming it's from you attempting to install the sdf python reader, which is failing due to how newer versions of python prevent global installs.

The easiest way to avoid this is to use a python environment.

**Comment by Tar-phy** [comment]
Thank you for Reply.........
but i have used python environment . It's showing same Error
![Screenshot from 2024-10-25 15-05-15](https://github.com/user-attachments/assets/1700e6be-bc04-4971-a4af-71a3c24ca6ea)

**Comment by TomGoffrey** [comment]
Start the python environment, build the sdf reader, and try again.

**Comment by Tar-phy** [comment]
Thank you. My problem has resolved.
