### ISSUE TITLE
Wigner transform

### ISSUE THREAD

**Issue by alexanatoly** [Warwick-Plasma/epoch#753]
Hi,

I am wondering if "Wigner transform" capabilities are included in the Epoch code ?
It could be a powerful tool, especially for high density plasma.

Best,
Alex

**Comment by Status-Mirror** [comment]
Hey Alex,

I'm not aware of such a capability with EPOCH. Is this something which other PIC codes are able to do?

Cheers,
Stuart

**Comment by alexanatoly** [comment]
Hi @Status-Mirror,

Yes, OSIRIS code has such capabilities. These simulates the laser pulse wavenumber transformation on interaction with plasma. At high density, laser pulse suffer strong compression, modulation etc. Wigner transform is quite powerful to see such transformation. 

For example, for low density cases see the articles below:
https://iopscience.iop.org/article/10.1088/1367-2630/14/2/023057/pdf
https://iopscience.iop.org/article/10.1088/0741-3335/56/8/084006
