### ISSUE TITLE
formation of fine lines in counter-propagating laser pulses

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#88]
In GitLab by Deep on 14 Sep 2020, 11:29  (GitLab issue GL#2248)

Dear Developer, 
 I am using two counter-propagating laser pulses in a finite plasma slab. this laser has a slight difference in wavelength(800nm and 760nm). When it meets at the center, it should create a potential well[Ex](../raw/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/7013de95f09221f76b6f4815dcefc08c/Ex.png). As you can see from the figure, it shows multiple fine lines in the Ex field. I am curious to know why I am getting these artifacts in my result. Is there a way to avoid them.
Waiting for your favorable reply.

**Comment by Status-Mirror** [comment]
This issue is quite old, and there appears to be insufficient information to reproduce this. It's not clear that this is a bug, so I'm going to mark this issue as closed.
