### ISSUE TITLE
gfortran version conflicts with mpi.mod

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#89]
In GitLab by Arka on 15 Sep 2020, 19:31  (GitLab issue GL#2249)

Hi,

I am trying to set up a fresh EPOCH installation, v4.17.12. I find the code compilation breaks down early when it tries to use the mpi.mod file. It seems to think that the gfortran version that compiled the mpi module and the one currently compiling it are different and terminates immediately. Did anyone else encounter such problems with conflicting gfortran versions? If so it would be very helpful if you can point me towards a solution.

**Comment by TomGoffrey** [comment]
Given there has been ~5 months since the request for further information, I'm going to assume this was resolved by the user.
