### ISSUE TITLE
How to track the ionization electrons

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#96]
In GitLab by linsen Yang on 30 Oct 2020, 13:09 UTC (GitLab issue GL#2269)

In lwfa using ionization induced electrons acceleration , so how to edit a script to track ionization electrons,does it work just using subset like name and include_species.

**Comment by Status-Mirror** [comment]
EPOCH has recently had it's ionisation routines updated, but you can still separate out the ejected electrons from specific ionisation levels.

Once you have them as a separate species, it will be much easier to track them. You can create an output block to output their properties at a specific time.

Cheers,
Stuart
