### ISSUE TITLE
Request to help answering some questions to get access in a supercomputer.

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#97]
In GitLab by Monira JK on 09 Nov 2020, 10:49 UTC (GitLab issue GL#2271)

To whom it may concern, 
I like to have accessed a super computer. While I am writing the project I am asked to answer the following question. I am a new user of epoch code. So I got confused. We are planning to use epoch code is to generate compact gamma source through laser-plasma interaction that requires full three-dimensional particle-in-cell simulations. Would you please help? 

Here are the following inquiries:  

---------------------
1. Does it use OSS (Open Source Software) and if yes, conditions for OSS

2. Does it use any other licensed Software

3. Is it an import substitution product and if yes, the equivalent commercial product)

4. Does it match or exceed in performance any of the commercially available product? If yes please give details

5. Expected performance metrics

6. Benchmark suites
--------------------

Thanks in advance.

Regards,
Monira

**Comment by TomGoffrey** [comment]
1. Yes. It's released under the GPL 3.0 license.
2. Yes. It uses the Warwick self describing file format, SDF.

I'm not sure what question 3 means, and questions 4-6 can only be answered by the applicant themselves. Benchmarking and performance metrics will depend on the problem being investigated, as well as the target architecture.
